### ISSUE TITLE
[Request] Custom spawn eggs

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#101]
Add additional spawn eggs for mobs that can be found in `/arena items`

- Charged Creeper
- Iron Golem
- Snow Golem
- Illusioner
- Wither
- Killer Bunny

**Comment by kangarko** [comment]
I am sorry, but CoreArena is not a plugin for that. 

By the way, I made a completely new plugin Boss from which eggs of such monsters can be placed to the Spawner menu in CoreArena. All suggested mobs are supported. Of course you don't have to buy it, but for these reasons I am not going to add it to CA. Thank you for your understanding.
