### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#103]
Placeholders for various things:

- Nuggets (Returns how many nuggets you currently have)
- Current Phase (Returns what phase you are currently on, returns null if not in mob arena or in lobby)
- Time till mob arena start (Returns how many seconds are left until arena starts, returns null if player isn't in a lobby)
- Total mob kills in current game (Returns null if not in a game, should just return 0 if in lobby)
- Total player kills in current game (Returns null if not in a game, should just return 0 if in lobby)
- Total player & mob combined kills in current game (Returns null if not in a game, should just return 0 if in lobby)

**Comment by kangarko** [comment]
Thanks, will consider!
