### ISSUE TITLE
Info Per-arena-start-message

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#104]
Hello! i'm here for submit a new feature but that is no so important. 

This idea is the Per-Arena-Start-Message. 

This feature is a message for any arena that the user has created. 

Obviously this message can be activated or disabled for a specific arena. 

An example is: 

&8&m-----------------------------------------
           &6&lGAME &7- &6Core&7Arena 
Survive to the various mob phases by killing them all!
If you are killed you lose a life, the maximum lives for each arena are 3 so do not be killed immediately to lose the game and be disqualified!

&7&o General Information:
    &7&oLives: 3/3
    &7&oPVP: &aON - &cOFF (&7Phase: &e&o{Phase_Number})
    &7&oBoss: &aON - &cOFF (&7Phase &e&o{Boss_Phase}) (NOTE: This line of message works only if that server own the Boss plugin.)
&8&m-------------------------------------------

Obviously this message is a simple example that is sent at the start of the game for each player.

Same for the Lobby, like: 

&8&m-----------------------------------------
                            &c&lALERT
 &7Note: The teaming in this &cArena &7is &cForbidden!
 &7If you do this you will get banned from the server.
&8&m-----------------------------------------

And this is the format of the config message: 

Per-Arena-Start-Message: 
        Enabled: true/false
        Permission: none or corearena.ArenaName.ArenaMessage
        Message:- 
       &8&m-----------------------------------------
           &6&lGAME &7- &6Core&7Arena 
Survive to the various mob phases by killing them all!
If you are killed you lose a life, the maximum lives for each arena are 3 so do not be killed immediately to lose the game and be disqualified!

&7&o General Information:
    &7&oLives: 3/3
    &7&oPVP: &aON - &cOFF (&7Phase: &e&o{Phase_Number})
    &7&oBoss: &aON - &cOFF (&7Phase &e&o{Boss_Phase}) (NOTE: This line of message works only if that server own the Boss plugin.)
       &8&m-------------------------------------------

Per-Lobby-Message:
        Enabled: true/false
        Permission: none or corearena.arenaname.lobbymessage
        Message:-
         &8&m-----------------------------------------
                            &c&lALERT
 &7Note: The teaming in this &cArena &7is &cForbidden!
 &7If you do this you will get banned from the server.
        &8&m-----------------------------------------

**Comment by kangarko** [comment]
Thanks, will consider.
