### ISSUE TITLE
Option to skip check for empty inventories.

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#108]
Due to the unknown issues some people (including me) are facing, I think there should be an option in the config to skip checking for empty inventories, allowing for servers to use CoreArena alongside a per-world inventory plugin if they desire.

**Comment by kangarko** [comment]
This won't be added as it would create massive confusion and lost of inventories.

I rather fix your issues, what are they?

Eventually, set "Allow_Own_Equipment" to true in each arena to not modify player's inventory.
