### ISSUE TITLE
Option to disable saving of xp/hp/hunger

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#109]
An option to disable CoreArena from saving xp/hp/hunger and restoring it.
The idea is that it will allow for per-world plugins to be used so server owners can have a workaround for the unknown problems related to xp not being restored properly.

**Comment by kangarko** [comment]
Let's talk at: https://github.com/kangarko/CoreArena/issues/69

First I try to fix it, if this won't succeed than this is the option.
