### ISSUE TITLE
[BUG] - Last bone/arrow stays in inventorie for infinity uses.

### ISSUE THREAD

**Issue by CancerCell** [kangarko/CoreArena#110]
![image](https://user-images.githubusercontent.com/41479613/43005976-57b66756-8c2c-11e8-918a-0cf5f8083db7.png)

People can use infinity amount of: Arrows, Bones ( to spawn dogs ).

Plugins taht may harm that plugin: BOSS, worldguard, fbasics

Error.log - https://pastebin.com/7vvV745m

settings.yml - https://pastebin.com/aWSWb3We

MyArena.yml - https://pastebin.com/sG3fnD3K

**Comment by kangarko** [comment]
Thank you for reporting this, I have fixed it. A new release will be available within 1-2 hours.
