### ISSUE TITLE
[Bug]  Next Phase doesnt start after after all monsters die.

### ISSUE THREAD

**Issue by CancerCell** [kangarko/CoreArena#111]
![image](https://user-images.githubusercontent.com/41479613/43006936-df318ea2-8c2e-11e8-8163-ef4d27e724b2.png)

Doesnt work ability to start next phase if all mobs are killed. (All mobs created with BOSS plugin)

Plugins taht may harm that plugin: BOSS, worldguard, fbasics

Error.log - https://pastebin.com/7vvV745m

settings.yml - https://pastebin.com/aWSWb3We

MyArena.yml - https://pastebin.com/sG3fnD3K

**Comment by kangarko** [comment]
I am sorry to inform you that the feature Require_No_Alive_Monsters is not included in CoreArena (yet). The config option is a left-over from a debug phase. The feature is scheduled to the next feature update.
