### ISSUE TITLE
Class permissions don't work

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#117]
As the title says, I have the permission uncommented in the class files and they can still be used.
Checked with luckperms verbose and it seems people aren't even being checked for the permission so it definitely isn't on my side.

**Comment by kangarko** [comment]
Not sure what you are trying to achieve, but it works for me:

![a](https://i.imgur.com/zueAICd.png)

Let me know what perm you used for what purpose (comment below, I still get the notification) and what did not work.

**Comment by TheWranger** [comment]
@kangarko I'm talking about the permission you set to restrict access to a class

**Comment by kangarko** [comment]
Apology for the delay, you are right, I fixed this.

**Comment by kangarko** [comment]
I solved class permissions not being taken into account when clicking a class sign, getting a random class when not having any, and in the class menu. I am pretty sure that's it, thank you for your patience.
