### ISSUE TITLE
Error On Entities for Corearena

### ISSUE THREAD

**Issue by MatheweB** [kangarko/CoreArena#12]
I am getting the following errors for Corearena whenever my server starts up:

https://hastebin.com/gomekagada.vbs

I am running the latest spigot 1.12.2, Corearena 1.3.4, and Spigotlib 4.3.

I also have Boss installed.

Let me know what you can do!

**Comment by kangarko** [comment]
Thank you, and I apology for a late reply. I will fix this (currently I am rewriting CoreArena to put automode into a separate plugin, that'll take a while but it will be fixed when it's ready).
