### ISSUE TITLE
Handling of players who leave while in arena

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#120]
Currently, if a player leaves while playing in the mob arena, they'll be teleported outside of the arena's region when they log back in.
This is a very large issue if we want to use void worlds as players can get kicked by an anticheat or just leave normally and they'll fall to their deaths, losing everything they have in their inventory.

If players leave while playing in an arena, they should be teleported back to their last location, like if they were to leave the mob arena via `/ma leave`

**Comment by kangarko** [comment]
You are absolutely right, I coded in this feature right away. Thank you for your patience.
