### ISSUE TITLE
"Buy Packs" Shop missing

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#123]
Upon updating to the latest GameAPI and CoreArena, the "Buy Packs" shop has disappeared from the rewards menu.
![image](https://user-images.githubusercontent.com/24642838/44295548-4a768e80-a2ee-11e8-8b3e-303aa1d8f5e5.png)
Running paper 1516 (MC 1.12.2)

**Comment by TheWranger** [comment]
@kangarko is there any chance you could release a seperate version of corearena that uses 1.12 worldedit and fixes this bug, considering how big this issue would be for some.

**Comment by kangarko** [comment]
You are on Minecraft 1.12.2?

**Comment by TheWranger** [comment]
Yes

**Comment by kangarko** [comment]
Should be fixed in the latest released version:

![a](https://i.imgur.com/OLW86R0.png)
