### ISSUE TITLE
Ability to use the Previous Tier of the Classes

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#126]
Hello!

I don't know if you can accept more Ideas but, for secure i'm creating it. xD

Basically when you buy a Tier on the Classes you can't use the previous levels, so with this issue i want to request the ability to use the previously kits when you select a Class in the Lobby

Good bye c:

**Comment by kangarko** [comment]
Hey,

thank you for suggesting, but I have to reject this because that would allow unfair advantage in case you have completely different items in lower tiers.
