### ISSUE TITLE
Questions before I get plugin

### ISSUE THREAD

**Issue by robotnikthingy** [kangarko/CoreArena#128]
I have some questions about the plugin before I decide to get it

1. Does the plugin work by spawning mobs in waves?
2. If so, can you specify what monsters are spawned each wave?
3. When a wave of mobs spawn, do es the next wave spawn only when the previous wave of mobs are killed?
4. Can you set a limit on waves (like 20 waves of mobs before you beat the arena and the game ends) or is it just endless waves?
5. Does the amount of monsters spawned change depending on how many players are playing in the arena?
6. Can you create boss monster waves?

**Comment by kangarko** [comment]
Hello robotnik!

1. Yes, mobs are spawned in waves.
2. Yes, you can specify what monsters are spawned by placing monster spawners and configuring them.
3. Nope, the next wave turns regardless of whether or not any monsters are still alive.
4. Yes, you can limit waves.
5. You can customize a monster spawner to only spawn when there are X or more players.
6. Yes, the Boss plugin is supported as well as special Boss waves.

Anyways, I suggest you watch these setup videos in which I believe I answered most of your questions:
https://www.youtube.com/watch?v=86z7ZbbpPhc & https://www.youtube.com/watch?v=CdHIIomQQ34
