### ISSUE TITLE
Mass edit mob spawn points

### ISSUE THREAD

**Issue by Miclebrick** [kangarko/CoreArena#129]
Is there a way to mass edit mob spawn points, changing the mob for all of the ones in an arena?

**Comment by Miclebrick** [comment]
Alternatively, I could use a method to just delete all mobs

**Comment by kangarko** [comment]
Hello,

you can use the Clone tool in `/ma tools` to rapidly place clones of a single mob spawner. Mass edits are not supported at the moment.
