### ISSUE TITLE
Poor menu configurability

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/CoreArena#130]
Hello,

There is a frustrating issue with /ma rewards - I only want to let players upgrade their classes, not purchase random sh*t like blocks and items for those "nuggets". Couldn't find anything by decompiling GameAPI, at least give me a method how to open directly that class upgrade menu.

Edit: also I cannot change any of /ma rewards item names, at least I could rename them "disabled" or whatnot, not possible DUE TO POOR MENU CONFIGURABILITY.

Thanks.

**Comment by TheIronMinerLv** [comment]
Oh right, couldn't find it first so I decompiled it.. Anyway in source code too I can't find a proper method to do what I need.

**Comment by Miclebrick** [comment]
By default there seems to be no blocks or items available for purchase (I haven't set it up yet so nobody can buy anything).

**Comment by TheIronMinerLv** [comment]
Yes, but that is not what I'm asking - I just don't need those two buttons (blocks and items) in rewards menu, cannot change where they are located.

**Comment by Miclebrick** [comment]
Yeah, this plug-in overall does not seem very configurable, nor meant to be used in a great variety of ways or integrated with an existing server's plugins

**Comment by kangarko** [comment]
I will look into it, thank you for pointing that out.

We are always expanding and adding new configuration options, recently added 3 different settings to each arena yml file.

**Comment by kangarko** [comment]
Added the option to disable material rewards.
