### ISSUE TITLE
Move to next phase when all mobs are killed.

### ISSUE THREAD

**Issue by Owizardo** [kangarko/CoreArena#132]
Hi there,

How do I set this up so that the next phase starts only when all mobs are killed?

**Comment by kangarko** [comment]
Currently not possible, leaving open as a suggestion

**Comment by Owizardo** [comment]
Ok i can understand that but could there be a work around? For example lets say add bosses every 10 phases, whhen the boss spawn it will trigger custom commands (maybe like pause phase). When you kill the boss it will let you run another command (unpause phase and continue).

Could that be something that would be easier to implement meantime?

**Comment by Owizardo** [comment]
I know javascript and typescript but thats about it lol. Ill check it out but most likely youll have something done before I can figure this out.

**Comment by Owizardo** [comment]
Well decided to give it a go and built my first plugin. Imported the GameAPI but looking trough it I see functions to stop and reset and start the phase but nothing to pause. Would you be able to point me int he right direction of how I would accomplish this?

**Comment by Owizardo** [comment]
Any updates on this?

**Comment by kangarko** [comment]
To be honest I had to disappoint a few people in the last few months because I honestly and sincerely got busy in real life stuff. Already got a paid dev for ChatControl, will be hiring more people so they will work on _all_ suggestions. Thank you for your understanding.

**Comment by kangarko** [comment]
I added 3 new requested features to today's release, but not this one yet. This will come in the next update.

**Comment by kangarko** [comment]
Added
