### ISSUE TITLE
After few "games", player starts picking up "experience"

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/CoreArena#133]
Hello!

I'm using CoreArena 1.7.2 with GameAPI 1.2.5 and Spigot 1.8.8. After a player plays few "rounds" of fully set-up CoreArena (not sure how many) - he joins, plays, arena ends and repeats - the "experience" that mobs drop breaks and player picks them up as normal items, no messages in chat, **no errors in console or whatever**. 

BUT when player reconnects, the bug "vanishes" for a few "rounds" and then it starts again. Could you resolve this?

Edit: **It seems like the bug only appears when I force start an arena (only then, without force starting the bug doesn't seem to appear).**

Edit2: Some players are still reporting that this occurs even without any force starts, soo not sure what triggers it.

**Comment by kangarko** [comment]
Seems platform specific, probably only on 1.8.x versions. Will follow up when we get the WorldEdit compatibility backported to that MC version.

**Comment by kangarko** [comment]
@TheIronMinerLv let me know if the issue still persist in PM when we fix your release
