### ISSUE TITLE
Mobs in the arena don't get effects applied (EG. fireaspect, poison ect)

### ISSUE THREAD

**Issue by RegencySolid** [kangarko/CoreArena#134]
As said in the title, using fire aspect mobs dont get set on fire and poison potions do not work.

**Comment by kangarko** [comment]
Set Mob_Burn_On_Sunlight to true in your arena yml file. That will make mobs burn on sunlight but also apply the enchant to them. We cannot split them due to the way Bukkit gives us instructions, sorry.
