### ISSUE TITLE
Boss support doesn't work 1.13.1

### ISSUE THREAD

**Issue by RegencySolid** [kangarko/CoreArena#135]
as stated in the title, Boss mob eggs dont work with spawn points

**Comment by kangarko** [comment]
Just testing but could not reproduce, any errors? Are the eggs there or they disappear when you reopen the menu?

Make sure to run very latest of CA + Boss.

Set Debug to [spawning] in settings.yml and report back the messages.

**Comment by kangarko** [comment]
Closing, comment below if still having issues
