### ISSUE TITLE
[Question] Some questions (again)

### ISSUE THREAD

**Issue by maxlehot1234** [kangarko/CoreArena#136]
Hi,

I just want to know if it possible to create an arena and give an item to the player that will spawn the boss.

When player use the item, a broadcast was send to the server and players can join this arena for the next 60 seconds, choose their class/kit and fight the boss.

They will have like 5 minutes to kill the boss.

If they are not able to kill the boss, boss disappear and they are kick from the arena.

If they kill the boss, they all get a reward.

Thanks again and let me know if it was possible thing ;)
Have a nice day

**Comment by TheWranger** [comment]
No, this isn't possible.

**Comment by kangarko** [comment]
Hello,

partially yes, mostly no.

It is possible to give player a Boss egg and configure the Boss to broadcast a message to the server.
It is not possible to keep joining to the arena once it has begun.
It is possible to set a timer for 5 minutes and kick all players if the Boss is not killed, but only via GameAPI if you are a developer with Java knowledge.
