### ISSUE TITLE
Functionality and Configurability

### ISSUE THREAD

**Issue by Wardalicious** [kangarko/CoreArena#137]
Hello,

I have a few concerns in regards to the plugin, and would like to address them here, if I may, in an attempt to get them resolved.

Firstly:
I noticed that there are grammatical errors, which would need to be fixed. I also saw several areas of the plugin (in red squares in the image, here: https://prnt.sc/l31xij) that I would like to change the wording of. Is this possible?

Secondly:
I've looked over the plugin on SpigotMC, and may just be missing it, but... can this plugin be kept on the same server, as the one the players are on? Also, can I give players items, outside the game, based on how well they did, inside? Or, is the plugin completely independent of anything else, and nothing can be given, to those who play?

.

Please advise,
Ward

**Comment by kangarko** [comment]
Hello,

I have to apology for any grammatical typos or inconsistencies. Now, you can translate these messages to your liking by creating a "localization" folder inside both CoreArena and AutoPlay, restarting your server and editing the newly-generated messages_x.yml files.

See https://github.com/kangarko/CoreArena/wiki/Localization for more information.

On your second concern: CoreArena definitely, AutoPlay possibly. The latter plugin only works isolated when set to World mode.

Players receive a reward in terms of Nuggets, that will be used when they buy items. You can place those items to your /ma rewards menu in /ma menu and play with the prices so the better players do, the better items they can afford.

Best,
Matej

**Comment by kangarko** [comment]
Yes, Nuggets can be purchased when players are not playing by accessing /ma rewards command.

Nuggets are awarded in-game, whereas item rewards outside of game.
