### ISSUE TITLE
[Suggestion] Intergration with SimpleClans 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#14]
https://dev.bukkit.org/projects/simpleclans

There is an API, the developer has some updated builds recently in his development builds.
Adding this would add an entire Clan system, with all of its amazing features, I have used it for years.
Clans could then battle against each other, it could be used to organise fights, or tournaments, there's no need to add a friends system, They can already set alliances and enemies in it, there is even a /war system that could be hooked into!

**Comment by kangarko** [comment]
Thank you!

How would you like CoreArena to integrate specifically into that plugin?

**Comment by FrozenBeard** [comment]
Hey! I will be getting my first arena setup for halloween, I will use this as a trial to completely figure out the plugin and then get back.

SimpleClans are clans of players, so they can work against other clans, so peokple in a clan would be put in a team together.

**Comment by kangarko** [comment]
Hello,

CoreArena does not support teams, all players are together and fight the monsters together as well. You can however, enable the PvP from a phase, if desired, however there's no team split. I am sorry, but that's a fundamental concept of the plugin.

**Comment by FrozenBeard** [comment]
No teamwork though. There could be a feature to allow teams, like battlefield has squads, so you can spawn on teammates, if there not tagged in PvP/PvE, you could also have Squad XP Boosts, you could also have getting XP for a medic class healing others.

**Comment by FrozenBeard** [comment]
"You Died!" -> Opens Menu with team mates you can spawn on with their heads. Those that are Tagged in PvP wont allow you to click, or are replaced with the barrier block etc. Then you spawn within a radius of them.

**Comment by kangarko** [comment]
Thank you, those are all great suggestions, but I don't know if I get to them soon because my plate is already full as it is.

**Comment by FrozenBeard** [comment]
No sweat, this isn't a biggie, this is just a suggestion for future. Throw them on the to-do :)
