### ISSUE TITLE
Global and per arena region flags

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#147]
is there a way to do custom arena worldguard region tags like
CUSTOM :: `entity-stacking` for stackmob so we can prevent arenas from stacking spawned mobs.
In worldguard: `exp-drop` to stop people from getting exp by killing mobs in the region.

By global i mean flags defined in the settings.yml file that apply to all arenas. Additionally, it would also be useful to have region flags per arena.

**Comment by kangarko** [comment]
I apologies, not possible and currently unplanned.

**Comment by LogGits** [comment]
Why close the issue unless the request was declined.

**Comment by kangarko** [comment]
We do not plan to implement, we have a large roadmap and new features incoming, have to sort them out on a weekly basis

**Comment by LogGits** [comment]
Ah ok maybe down the track. Out of curiosity have any of the #4 been completed? There is a checkmark box on the left hand side. I keep seeing the updates as one-liners usually small things. Does this mean Corearena will have 1 big update soon and If so any ideas on when?

**Comment by kangarko** [comment]
Yes and no, we usually either implement them right away or remove them from roadmap when they are implemented, so you only see the unimplemented features. Honestly, for the last few months I was busier with other priorities and could not take too many features on my shoulders.

**Comment by LogGits** [comment]
Ah ok. What about instead of worldguard flag support. Some individual things; e.g. a way to stop mobs from stacking in specific arenas from [stackmob](https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance.29999/) and also a way to prevent mobs from dropping exp when they are killed.

**Comment by kangarko** [comment]
Implemented StackMob support to prevent stacking.
