### ISSUE TITLE
disable arena

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#148]
Can you add a way to disable an arena without deleting it, so people cant /ma join <arena> name while its disabled. Unless they have a permission node to bypass. This feature should also allow us to edit the arena while its disabled.

**Comment by kangarko** [comment]
Currently, you can put the arena into editing mode or remove the Lobby which is a critical point so people won't be able to join.

Thank you for that suggestion.

**Comment by LogGits** [comment]
Can you put multiple arenas into editing mode at the same time because i want to disable multiple arenas while i'm working on them.

**Comment by kangarko** [comment]
Added
