### ISSUE TITLE
Commands outside those listed in settings.yml working

### ISSUE THREAD

**Issue by ApocalypseZenny** [kangarko/CoreArena#149]
As title says, people can use the /kit command while inside the arena... defeating the point of kitting for classes.

 # CoreArena 1.7.12

  Allowed_Commands:
  - /arena
  - /ma
  - /tell
  - /msg
  - /r
  - /ping
  - /tps
  - /lag
  - /warn
  - /kick
  - /tempban
  - /tempmute
  - /chc ach
  - /chc g

**Comment by kangarko** [comment]
Cannot reproduce. What plugin are you using for kits?

![a](https://i.imgur.com/ZslMJF5.png)
