### ISSUE TITLE
[bug] Player join Errors in console

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#15]
In the first 10 mins of setting up my first server I had a server crash after I created my first arena outline.
I checked the console and the only error was playerjoin errors
Here is from my error log https://pastebin.com/LWrFJBiw
Here is the console errors when a player joins (arena isn't even setup yet).
https://pastebin.com/6saFDaFK

**Comment by kangarko** [comment]
Hello,

I have attempted to solve this problem, please test out the next release, when released.
