### ISSUE TITLE
Dying in Arena causes players to spawn at worldspawn

### ISSUE THREAD

**Issue by ApocalypseZenny** [kangarko/CoreArena#151]
With CMI and Essentials installed... it's causing player's to spawn with two lives available at worldspawn.  I cannot find the command CoreArena is trying to issue which is forcing the player to worldspawn.

My previous issue with /kit, I have the following plugins:

Arconix, AutoMessage, AutoSaveWorld, Block_that_command, BuyCraftX, CMI, CoreArena, EpicSpawners, EssentialsX (Chat, GeoIP, Protect, Spawn), GameAPI, GriefPrevention, KitGUI, mcMMO, MythicMobs, NewItemNames, nuvotifier, PlayerVaults, PlugMan, ProtocolLib, QwickTree, ServerListPLus, ShopGuiPlus, UltraPermissions, Vault, VotingPlugin, WorldEdit, WorldGuard, XRayDetector.

**Comment by kangarko** [comment]
Please also update your GameAPI.

**Comment by ApocalypseZenny** [comment]
GameAPI is up to date.

**Comment by ApocalypseZenny** [comment]
The game does not finish as a result.  The player would still have two lives (out of three) remaining and would spawn at world spawn instead of respawn in the arena.

I started doing some troubleshooting and determined it has something to do with CMI.  We removed CMI from our server.  No more issues with the spawn point.

While I’ve got your time, is there a way to force the arena to restart after the game is over or when all players leave?  With a sign set near our spawn, we have to manually reload the plugin every time we want to reset the arenas.

**Comment by kangarko** [comment]
@ApocalypseZenny apology for the delay, may you please test on the next version? It will be up in a few hours.

**Comment by ApocalypseZenny** [comment]
Yes, I'll get some of our staff to test it.  Should be able to let you know in the next day or so.

**Comment by kangarko** [comment]
Closing as a part of general maintenance.  I assume that CMI caused it, if I am mistaken please comment below and I get back to you.
