### ISSUE TITLE
Players don't get rewarded if they disconnect

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#152]
If a player disconnects from the server while playing in the mob arena; they won't receive their nuggets when they reconnect to the server.
Would be cool if there could be a configurable chat message when they join back that can remind them about it and tell them how many nuggets they earned.
Thanks.

**Comment by kangarko** [comment]
This is counted as escaping and players are not rewarded for that.

**Comment by TheWranger** [comment]
But then can't people just use /arena leave to escape the mob arena?

**Comment by kangarko** [comment]
Bang, it's in there!
