### ISSUE TITLE
Disable categories on Rewards page.

### ISSUE THREAD

**Issue by Nioxed** [kangarko/CoreArena#154]
It'd be great if we were able to customize the categories on the rewards page. None of my rewards really fit into the Item, Block or Pack category.

Personally not having the categories there in the first place would be great, But being able to make your own would be even better.

I hope that at least we can get a config option to reduce the Categories to 2: Items & Upgrades.

**Comment by kangarko** [comment]
Thanks for the suggestion, I am leaving it open for a future implementation.

**Comment by kangarko** [comment]
I have added it so you can rename the titles and change the item materials :)
