### ISSUE TITLE
Classes and Upgrade Menu Bugged

### ISSUE THREAD

**Issue by Tomographix** [kangarko/CoreArena#155]
Hi,
We are in the middle of setting up CoreArena and having some trouble with the classes and upgrade menus. They aren't doing anything when clicked on in the /ma menu. We managed to setup the arena by doing /ma new <name> as the new arena menu items didn't work for us either. Both the plugin and the GameAPI are updated to the latest version on Spigot. 
Running 1.13.2 PaperSpigot. Any help would be appreciated :)

**Comment by kangarko** [comment]
Do you have any errors in the console? If unsure just post the startup log please.

**Comment by Imortalshard** [comment]
> Do you have any errors in the console? If unsure just post the startup log please.

There aren't any errors on the Startup or in the servers console. When trying to use the menus.

**Comment by kangarko** [comment]
Is any other plugin having the same command? Try running /corearena instead.

**Comment by Imortalshard** [comment]
I've just tired using /corearena and no difference. I do the command /corearena menu the click say classes, and the classes menu shows up but then when i click on return or create new, nothing happens. Same for Upgrades, 

The arena menu is the same when i try clicking on Create New or clicking on the current arena.

**Comment by jascotty2** [comment]
We will be looking into this shortly, sorry for the delay.

**Comment by jascotty2** [comment]
I'm unable to reproduce the issue.

Could I get a zipped copy of your CoreArena plugin folder?

You may send it in a message on spigot if you'd prefer not attach it to this ticket: https://www.spigotmc.org/members/jascotty2.3571/

**Comment by Imortalshard** [comment]
> I'm unable to reproduce the issue.
> 
> Could I get a zipped copy of your CoreArena plugin folder?
> 
> You may send it in a message on spigot if you'd prefer not attach it to this ticket: https://www.spigotmc.org/members/jascotty2.3571/

Just sent through the files via Spigot.

**Comment by kangarko** [comment]
@jascotty2

**Comment by jascotty2** [comment]
Was unable to reproduce using the configuration provided, most likely a plugin conflict. 

Have not received a reply since Dec 13, closing ticket for inactivity.
