### ISSUE TITLE
SUGGESTIONS TO MADE CA BETTER

### ISSUE THREAD

**Issue by shika258** [kangarko/CoreArena#161]
Hello i would like to know if you can add permission for join specific arena...
For exemple i have arena called "Castle"
So permission for join: corearena.join.<name>
so: corearena.join.Castle

And can you add an option so that the xp on the ground becomes an xp obtained instantly by the players who killed the monster to avoid the theft of XP on the ground and some incompatibility with the plugin "Magic" for example.

Cordially :)

**Comment by shika258** [comment]
And ingame on arena tnt does not damage mob, can you fix that to pls ?

But when i'am not in arena tnt work good

**Comment by kangarko** [comment]
Thanks, replied in Spigot.
