### ISSUE TITLE
Nashorn Depreciation

### ISSUE THREAD

**Issue by TheFlagCourier** [kangarko/CoreArena#163]
We've switched our development server over to using Oracle OpenJDK 11, and receive this notice when running the server, always popping up right after the CoreArena Ascii logo. Just thought it was worth bringing up.
`[17:28:13 WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release`

**Comment by kangarko** [comment]
Thanks, I am aware of this, will shade the libraries within the plugin or create a library like GameAPI for Nashorn after that.
