### ISSUE TITLE
Snapshot don't saving all

### ISSUE THREAD

**Issue by Sprungente** [kangarko/CoreArena#168]
I think it's a typical 1.13 bug. Sign are empty and skins wont be saved after the arena will regenerate. 

I don't have any Warnings or errors that occoured.

Corearena 1.7.23
Spigot 1.13.2

**Comment by JimBridger** [comment]
I'm getting something similar, items in chests don't save to the snapshots, and upgrade/class/leave signs all disappear though saved initially to the snapshot...and when the before snapshot is loaded the signs are gone.

**Comment by kangarko** [comment]
@Sprungente and @JimBridger , are you using the very cutting edge WorldEdit from http://builds.enginehub.org/job/worldedit/last-successful?branch=master ?

**Comment by JimBridger** [comment]
@kangarko I use the latest beta 4 from this:
https://dev.bukkit.org/projects/worldedit/files

**Comment by kangarko** [comment]
@JimBridger please use the latest build from the url above
