### ISSUE TITLE
[bug] Cant /ma reload.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#17]
/ma reload just spawns this error:
https://pastebin.com/YN1fkLsZ

**Comment by kangarko** [comment]
Hey,

I am sorry, this error requires you to look up the console for another error that is hiding behind this one (InvocationTargetException(**Unknown cause**)). Please see the console from that day, or try to re-attempt the error and post the full console output.

**Comment by FrozenBeard** [comment]
It happens every single time I do the command. Even without changing anything. My Syntax is fine.
I booted the server fresh and then run the command https://pastebin.com/kdUzs37N

Im using PaperSpigot if its not been tested with that.

**Comment by kangarko** [comment]
Please use the next upcoming version and set **Setup.Accept_Unsafe_Monster_Eggs** to true in settings.yml
