### ISSUE TITLE
Snapshot takes too long to restore

### ISSUE THREAD

**Issue by JimBridger** [kangarko/CoreArena#170]
I updated corearena a few days ago to the lastest update and now I'm having trouble actually using the arena's.  When right clicking the join sign there's the usual 'lag' then I am teleported to the lobby for a second and then teleported right back to the sign because the arena is over.  When I look in console it says the following:

> [06:16:31 INFO]: Arena // *-----------------------------------------------*
> [06:16:31 INFO]: Arena // Snapshot of arena DAF took too long to restore!
> [06:16:31 INFO]: Arena // Was restoring to stage: initial
> [06:16:31 INFO]: Arena // Took over: 10 seconds
> [06:16:31 INFO]: Arena // 
> [06:16:31 INFO]: Arena // Check your WorldEdit update.
> [06:16:31 INFO]: Arena // We have stopped the arena for safety
> [06:16:31 INFO]: Arena // *-----------------------------------------------*
> [06:16:32 INFO]: Arena // GG! The game in DAF has finished!

I'm using the latest worldedit snapshot, I can't believe this would be a hardware problem because I didn't have this problem before.  Thank you for your help!

Respectfully,
Jim

**Comment by kangarko** [comment]
Hey, if you have 1.13.2, make sure to use this latest snapshot: http://builds.enginehub.org/job/worldedit/last-successful?branch=master

Also, you can try installing FastAsyncWorldEdit to load the arena asynchronously.

**Comment by JimBridger** [comment]
Ty kangarko, this solved the problem :)
