### ISSUE TITLE
No Region Point Error

### ISSUE THREAD

**Issue by miniharry** [kangarko/CoreArena#178]
Hi,

I created an arena and set the region points correctly.

When I click a block to set the lobby (inside the region) it does nothing but gives this error:

console - https://hastebin.com/sawijalade.md
error.log - https://hastebin.com/pujasonava.rb

But when I click a block to set the lobby (outside the region) it says the selected point is outside the arena.

Swift resolution of this problem would be appreciated, I'm not sure if it something on my end, but I'm not sure what else to try.

Thanks

**Comment by kangarko** [comment]
Hey, apology for the delay.

Please update to the next version and set Debugger to `["region"]`. This will print out additional messages when that happens again so I am able to track down and fix the problem. Post me your console messages from than. 

Thank you.

**Comment by kangarko** [comment]
Should be fixed in the next version
