### ISSUE TITLE
[how] How do I set the players teleport locaton after the game ends?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#18]
If someone looses all their lives, how do i set where they get teleported too? I want them to go to my hub on the bungee (A different server on the bungee)

At present players are left lingering around in the arena.

How do I make the Damage, actually damage better? At present it take a hell of a lot of required damage to make blocks break, but I don't want to just set the strength of the bow higher! Then that'll cause more damage to players and mobs.

**Comment by kangarko** [comment]
Hello!

When players finish their arena, they are teleported back to where they came from. If this location does not exist, they are teleported to the server spawn. I will add a feature of running commands after an arena finishes in the next version (including bungee commands).

You can increase the damage in Procedural_Damage.Explosions.Power.Bow in settings.yml.

**Comment by FrozenBeard** [comment]
Good news about being able to set bungee commands. Then you can run things like /send current Hub or whatever. 

As for damage, what I meant to say was, I want to increase the damage to materials not players/mobs, I can fire a bow at a cluster of mobs and they will all die, I can fire a bow at a brick wall and it may damage 1 brick, it makes the procedural damage pointless. We need to set how strong blocks are to the damage, or at least a percent. Ive not once had any building actually fall down from this damage, I had to shoot 30 arrows into the the base of a small 4x4 tower just to remove the base blocks!

**Comment by FrozenBeard** [comment]
How about thinking of the design the other way around? So you bump the explosion damage, but at the same time, you track explosions to players/mobs. This way you could dampen the effect.

**Comment by kangarko** [comment]
Good idea! I have added it to the road map https://github.com/kangarko/CoreArena/issues/4
