### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by PinHsiu0628** [kangarko/CoreArena#180]
After the game finish the exp of players will be cleaned.

**Comment by kangarko** [comment]
Please ZIP me your CoreArena folder into the reply window below. What other plugins are you using on your server? What is your MC version?

**Comment by PinHsiu0628** [comment]
This is my CoreArena folder.
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/2849000/CoreArena.zip)

I the plugins used in my server are: ActionHealth. AgarthaLib. AncientGates-2.2. AuthMe-5.5.0-SNAPSHOT. Boss-1.8.20. ChestSort. Citizens. Clearlag. CoreArena-1.8.1. CoreProtect-2.15.1. Crazy Auctions[v1.2.7]. Essentials(all). FastLogin. GameAPI-1.3.5. HolographicDisplays. KillerMoney. LangUtils-v2.1.17-mc1.13.1. Lockette. mcMMO. mcMMO-TagAPI. Multiverse-Core-2.6.0. MyItems. NyaaCore-v6.3.308-mc1.13.2. OpenInv. ProtocolLib. Residence4.8.4.4. rpgitem-reloaded-3.6.569-mc1.13.2. ScoreboardStats. ServerSelectorX-3.2.4. SimpleRestart. SimpleSit. SkinsRestorer. Vault.

And the version of my server is 1.13.2.

**Comment by kangarko** [comment]
Thank you, should be fixed in the next version.

**Comment by PinHsiu0628** [comment]
uhh bro I think the bug didn't be fixed.

**Comment by kangarko** [comment]
Thanks, really fixed this time :)Thanks, really fixed this time :)
