### ISSUE TITLE
Suggestion: Duplicating Arenas

### ISSUE THREAD

**Issue by xDacon** [kangarko/CoreArena#182]
Creating all the spawn locations/mobs/etc. for a new arena takes a lot of time, being able to duplicate an arena in a new location would be very helpful

Currently you can only duplicate the settings, since everything else is saved in a shared .db file which is encrypted and not editable

**Comment by kangarko** [comment]
Thank you for your suggestion. Due to high load of suggestion tickets we are not accepting any more suggestions for the time being . You can edit data.db and duplicate the arena using Notepad++ or Atom text editor for now.
