### ISSUE TITLE
Players are losing the XP they had before playing the arena when they leave the arena.

### ISSUE THREAD

**Issue by FocaM8** [kangarko/CoreArena#188]
Hi. When players win/lose/leave the arena, they don't get back the XP they had before. We implemented this plugin on a story mode server as dungeons and we really need this feature.

Anyway, nice work and keep it up!

**Comment by kangarko** [comment]
Make sure you have the very latest CoreArena, we recently fixed that issue

**Comment by kangarko** [comment]
Closing, I really believe it is solved on the very latest CoreArena, comment below if not
