### ISSUE TITLE
Gui translation

### ISSUE THREAD

**Issue by Nedjii** [kangarko/CoreArena#189]
Hello, i suggest to add a gui translation feature, i think that's a must have.

**Comment by Nedjii** [comment]
Edit : A whole gui configuration would be nice as i don't want ppl to buy blocks or items and i can't remove these categories from reward gui.

**Comment by kangarko** [comment]
Hey, I am sorry but at present this is not possible. You can customize the in-game messages using the localization files, see wikipedia.
