### ISSUE TITLE
[how] How do I get rewards bought into my survival server?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#19]
My survival server is on Bungee, its technically on a separate physical server, I assume bought rewards are saved into the database, So is there a counterpart to this plugin to allow install onto the survival server to obtain your rewards? I don't get how you send the rewards from the mini-game to a survival server.

**Comment by kangarko** [comment]
Hey!

To synchronize rewards, you can install CoreArena on both of your servers and configure both of CoreArenas to connect to the same MySQL database (see MySQL section in settings.yml).

**Comment by FrozenBeard** [comment]
Ah right, I don't want any arenas at all on my Survival, Arenas are separate! it won't make any changes to the gameplay or effect the survival? All I want is for Rewards to work on survival. 
What happens if the player Buys the reward on the game server? I dont want them dropping, loosing it, duping it etc.

**Comment by kangarko** [comment]
CoreArena does not affect your server unless configured so. By default, without arenas, there's nothing the plugin does on its own unless commands are run (e.g. /arena rewards command).

You should deny access (via permission) to the rewards command on your game server and allow it on the survival server.

**Comment by FrozenBeard** [comment]
Isnt that how they upgrade their tiers for classes though? Seems a bit bonkers to have them go to survival to upgrade their tier on a minigame.

**Comment by kangarko** [comment]
Oh yes, you're right, actually the players would need to access /ma rewards on your game server to upgrade their classes. The tiers are not stored in the MySQL for the time being.

**Comment by FrozenBeard** [comment]
I suggest you separate them anyways, its a pain in the ass trying to understand the difference between a reward and a Tier upgrade, if they are put into the same category its confusing for the player.
It should probably be something like /ma rank, or /ma upgrade or /ma tiers.

**Comment by FrozenBeard** [comment]
So in the process of setting this up, all the Tier upgrades for the arena is saved in the database, not the "classes" folder. Which means why I come to setting this up on my survival (Just for rewards) and disable it on the Events server, there is no way for the player to upgrade their tiers. 
You need to separate the tier upgrades from the rest of the rewards, its confusing that they are combined.
So not possible at present without breaking the plugin

**Comment by FrozenBeard** [comment]
Actually thinking about this more.
if you are just saving the nuggets in the database. 
Wouldn't I just create rewards on the survival server and connect it to the database? Since its stored in the data.db thats local to the server. and they just share the MySQL. 
So:
Survival > Just setup rewards for items.
Events > Just setup the tier upgrades

If they are both connected to the same database, and I create new rewards for items in the survival it would populate the data.db right and use the nuggets from the MySQL database.

**Comment by kangarko** [comment]
Sorry for a late answer. Yes you could do it that way as you mentioned. I am working on repairing the mysql out-of-sync issue.

**Comment by FrozenBeard** [comment]
I had another thought about this, once the mysql sync is fixed you could instead of having the plugin on both servers (since its 2 plugins) you could just create a small plugin to interface with an existing shop plugin, that way you can have the shop/rewards separate by a fully fledged shop plugin.

**Comment by kangarko** [comment]
Good idea! Right now my plate in regards of development is pretty full (7 resources + few private ones), but if you meant to convert Nuggets into Vault and then into for example Essentials' Economy which would allow to buy items in any shop plugin, that is totally useful!
