### ISSUE TITLE
Sign update

### ISSUE THREAD

**Issue by Nedjii** [kangarko/CoreArena#191]
Hello, the join sign [arena] doesn't update at all its status when someone leave/join or if the arena is available or already in use. I got no error in logs.

**Comment by Nedjii** [comment]
Item frame are deleted each time the arena restores itself.

**Comment by kangarko** [comment]
That's awkward, but we were actually not updating signs on player leave. I will add that in 1 hour.

For item frames, I am sorry but we are relying on WorldEdit so make sure to grab the latest build from http://builds.enginehub.org/

**Comment by Nedjii** [comment]
" we were actually not updating signs on player leave" There is a player count "0/5" "1/5", that's what i'm talking about, anyway the whole sign isn't updating at all, the arena remains free on the sign even if someone is already playing it etc.

**Comment by Nedjii** [comment]
I can't use latest worldedit as i'm not running 1.13, i tried copying item frame with fast async worldedit and it works fine, what's the issue ?

**Comment by kangarko** [comment]
Hmm that's odd, everything's working fine here (https://i.imgur.com/SsGE5mV.gif).

What's your MC version? We should download KaWorldEditCompat library. If that older WorldEdit does not support tileentities in its API (that we are calling internally in our plugin) than I'm afraid there's nothing I can do.. for now.
