### ISSUE TITLE
Strange issue with mobs

### ISSUE THREAD

**Issue by Sinnikul** [kangarko/CoreArena#192]
Hi there. Having a strange issue where mobs, both vanilla and ones made with the Boss plugin, are behaving strangely within the Arena. Vanilla Skeletons and Wither Skeletons that are completely vanilla are spawning with enchanted bows, shooting fire arrows, and moving at absolutely INSANE speed. Baby zombie pigmen spawn with enchanted swords and one-hit you even thru full iron armor.

**Comment by kangarko** [comment]
Hi, can you please set Debug to ["*"] for CoreArena and watch the console on the first wave when it happens?

**Comment by Sinnikul** [comment]
Thanks for the reply. Here's a pastebin of the debug.
https://pastebin.com/4SFNH4vE

Wasn't sure what part would be useful for you so I took the entire thing, hope that's not a problem.

**Comment by Sinnikul** [comment]
https://gyazo.com/b5c9f577f987afce7cd173ade8d167b6

Here's a gif of the issue. Completely vanilla skeleton, spawning in full gold, enchanted fire bow, running around at breakneck speed. Kind of funny.

**Comment by kangarko** [comment]
I found that Boss did spawned the Boss correctly ("SUCCESS - handled in Boss" messages in the big log)

Can you try removing MythicMobs temporarily?

**Comment by kangarko** [comment]
Closing as per regular maintenance - if you still have this problem kindly let me know below.
