### ISSUE TITLE
Conflict with MyPet

### ISSUE THREAD

**Issue by Sprungente** [kangarko/CoreArena#194]
Hello guys

Today i found a bug related with MyPet.

In a roundbased Mobarena a MyPet prevent the moment to start the next phase... Until the Pet is away. So the issue is i think, that the Pet counted as a Mob that have to kill/die. 

I'm using Mypet 3.0 Build 1403
Corearena 1.8.11 
Spigot (Original) 1.13.2 

Maybe it is an issue an mypetside so i inform @xXKeyleXx , author from MyPet. If Mypet don't support CoreArena so this issue should be a suggestion to implement it. 

For Keyle: 
Pluginpage: https://www.spigotmc.org/resources/%E2%98%85-corearena-%E2%98%85-incredible-monster-arena-2-maps-1-7-10-1-13-2.42404/
Corearena use the GameAPI also by Kangarko: https://www.spigotmc.org/resources/gameapi-1-7-10-1-13-2.48556/
Sourcecode from GameAPI: https://github.com/kangarko/GameAPI

**Comment by kangarko** [comment]
Hey, I am sorry but I can't help you with that right now. You must remove your pets from your arena because they are counted as entities and so they will interfere with gameplay.
