### ISSUE TITLE
FastAsyncWorldEdit 

### ISSUE THREAD

**Issue by M4rtyn4** [kangarko/CoreArena#196]
Hi I got this error when using FAWE instead of normal WorldEdit.

> Error: Found class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat, but interface was expected

[https://pastebin.com/wG5cxj4e](url)
I have no idea what it means
I tried using latest WorldGuard with it but it just got worse.
:(

**Comment by kangarko** [comment]
Hey,

I am sorry but your FAWE version is incompatible. Either remove that plugin and use the latest WorldEdit official build from Bukkit or try changing your FAWE version.
