### ISSUE TITLE
Turning on bug

### ISSUE THREAD

**Issue by ali4own** [kangarko/CoreArena#197]
Hi every time i turn on the server corearena refuse to turn on and get me this error plsss help i am about to release thx

`[CoreArena] Enabling CoreArena v1.8.9 > [07:06:47 INFO]: Downloading KaWorldEditCompat.jar.. > [07:06:48 WARN]: java.io.FileNotFoundException: https://github.com/kangarko/GameAPI/raw/master/library/KaWorldEditCompat-1.0.0.jar > [07:06:48 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) > [07:06:48 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) > [07:06:48 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) > [07:06:48 WARN]: at java.net.URL.openStream(URL.java:1045) > [07:06:48 WARN]: at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460) > [07:06:48 WARN]: at me.kangarko.corearena.nul. .LPT8.llllIlllIIIllIIlllIllllIIIlllllIIlIlllIlIIIIlllIlIIlllIlIIIIIIlIIIIllIIlIlIIllllIlIlIIlllIllIIlllIllllIIIlIlIIllIlllIllIIIIlllIIllIlIIIlIIIllIIIlIIllIlIllIIIIIIIIIIlIlIlllIIlIlllllIllIlIlIIIllIIlIIllIIIllllIllIlIIIIlIIlIlllllIIIllIlIlllIIllIIlIIllIlllllllIlllllIlIIIlIlIllIlllIIlllllIlIllIllIIIlIlIlIlIlIIlllIIlllIllllIlIIIIIIIlIIIIllIllIlIIlIlllIIIllIIIIIIllIIllIIlIllIlIIlIllIIIllIlIIllIllllIllIIllIlIlIlllllllIIllIIIllIIIlIlIllllIllIIlllIlIlIIlllIllIlIIlIllIllIlIIlllllIIIlllIllIlIIllIlIllIIIIlIlI(SourceFile:156) > [07:06:48 WARN]: at me.kangarko.corearena.nul. .ak.onEnable(SourceFile:150) > [07:06:48 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) > [07:06:48 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) > [07:06:48 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) > [07:06:48 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) > [07:06:48 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) > [07:06:48 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) > [07:06:48 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) > [07:06:48 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) > [07:06:48 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) > [07:06:48 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) > [07:06:48 WARN]: at java.lang.Thread.run(Thread.java:748) > [07:06:48 INFO]: *-----------------------------------------------* > [07:06:48 INFO]: Fatal error downloading WorldEdit library, check your internet. > [07:06:48 INFO]: Plugin is now disabled. > [07:06:48 INFO]: *-----------------------------------------------* > [07:06:48 INFO]: [CoreArena] Disabling CoreArena v1.8.9 > [07:06:48 INFO]: CoreArena 1.8.9 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file. > [07:06:48 INFO]: java.lang.NullPointerException > [07:06:48 INFO]: at me.kangarko.corearena.nul. .aU.llIlIlIIlIlIIlIIllllIIlIIIIlIIIIllIllIIlllIlIIlllllIIlIlllIlIIlIIlIIIllllIIllIlIIIllIlllllIIlIllllIlllIIIlIlllllIIlIIIlIlllIllllllIIIIIllIIIIIIlllllIlIlIIlIIllIIIIllIIIlIIIIIlllIllIlIlllIIlIIlIlllIlIIIIIIIIIllllIIlllllllIIllIllIIIlllIIlIIIIllIllllIlIIlIIllIIIlIlllIIlllIlIIlIlIlIlIlIIIlIIIlIlIlIIIIllllIllIIlIIlllIIllIlIlIIIIIlIIIIlIIllllllIlllIlllIllIIlIIIllIlIIlllIllIIlllIIIlIlIlIllIlIIIlIIlIllllIIIIIlIIIlIlIlllIlIIlllllIIlIlIlIIIlllIIIIllllIIlIlIllIIIIllIIIIIllIllllIlIIlllIIlllllllIlIIIllIIlIIl(SourceFile:1125) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .aU.int(SourceFile:286) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .LPT8.lIIIllIlIllIIIllIIIIlIlIIlllIIIlIlIlIlIlIIllIlIllIllllIIIlIlllIIllIllllIIlllIlIIlIlIIlIllIlIIIlllIIllIlIllIlllIIIIIllIllIllIIlIlllIIlIIlllIIIllllIlIIIIlllIIIIIlIlIIlIIlIIlIIIlllllllIIIIlllIIlIIlllllIlIlIIllIlIIIllIlIlIlIlIlIIIIllllIIIllIIlIllIlIlIllIIllllIIIllIlIlIlIIlIlIlIllIIlIIllllIlIllIIIIllIIIlIIIIIlIIllIIIllIIIlIlIIIlIlIIIIlIlIIlIllllIlIllIllIlIIIllIlIllllIIlllIIllllIIlIIIIIIIllIlllIIllIIllIIlllIlllllIIlllIIlIlIlIllIlIlllllIIIIlllllIlIllIllIlIIlllllIllIllllIIIIIlIIllIIllIllIIllIIIIIlIIllll(SourceFile:289) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .LPT8.IIllIIlIlIIIllIlIlIlllllIllIlllllllllIIIlIIIIlIlllllIIIllIllIlIIIllIIIlIIIllIIlIIIlllIIIlIlIllllIlIlIlIIlIIlIIlllIIlIIIIIllIllllIIIlIlIllllIIlllIllIIIlllIIIIIIlIIIIlIIlIlIIIlIllIllIIIIIIIllllIlIlIIlllllllIlIIllIlIlIlIllllllIlIllIIlIlIlllIlllllIlllIlIlIllllllIIlIllllIllIlIlIIIIlIllIllllIllllIlllIIIllIIIllllIIlIIIIlIllllIllllIIlIIlllIIllllllllIIlIIllIlIIlIlIIlIIIIllIIIIlIllIIIlIIllIllIIIllIllllllIIIIlIllllIllIlIlIllIlllIlIlIlIllIIlIIIlllllIllIIIlllllIlIllIllIlIIlIllIIIlIIIllllIIIIIlIIllllIlIlIlllI(SourceFile:267) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .ak.onDisable(SourceFile:459) > [07:06:48 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) > [07:06:48 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) > [07:06:48 INFO]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .lpT2.nul(SourceFile:530) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .LPT8.llllIlllIIIllIIlllIllllIIIlllllIIlIlllIlIIIIlllIlIIlllIlIIIIIIlIIIIllIIlIlIIllllIlIlIIlllIllIIlllIllllIIIlIlIIllIlllIllIIIIlllIIllIlIIIlIIIllIIIlIIllIlIllIIIIIIIIIIlIlIlllIIlIlllllIllIlIlIIIllIIlIIllIIIllllIllIlIIIIlIIlIlllllIIIllIlIlllIIllIIlIIllIlllllllIlllllIlIIIlIlIllIlllIIlllllIlIllIllIIIlIlIlIlIlIIlllIIlllIllllIlIIIIIIIlIIIIllIllIlIIlIlllIIIllIIIIIIllIIllIIlIllIlIIlIllIIIllIlIIllIllllIllIIllIlIlIlllllllIIllIIIllIIIlIlIllllIllIIlllIlIlIIlllIllIlIIlIllIllIlIIlllllIIIlllIllIlIIllIlIllIIIIlIlI(SourceFile:161) > [07:06:48 INFO]: at me.kangarko.corearena.nul. .ak.onEnable(SourceFile:150) > [07:06:48 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) > [07:06:48 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) > [07:06:48 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) > [07:06:48 INFO]: *-----------------------------------------------* > [07:06:48 INFO]: Plugin shutdown malfunction: NullPointerException > [07:06:48 INFO]: *-----------------------------------------------*`

**Comment by kangarko** [comment]
Hey, I forgot to close it, please just update all plugins including WorldEditBridge: https://www.spigotmc.org/resources/worldeditbridge.65709/
