### ISSUE TITLE
arena will not start

### ISSUE THREAD

**Issue by kadika66** [kangarko/CoreArena#198]
11.04 18:33:02 [Server] INFO Arena // GG! The game in Nightfall has finished!
11.04 18:33:02 [Server] INFO Arena // -----------------------------------------------
11.04 18:33:02 [Server] INFO Arena // Stopping arena for safety.
11.04 18:33:02 [Server] INFO Arena // NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
11.04 18:33:02 [Server] INFO Arena // Error while spawning mobs in Nightfall
11.04 18:33:02 [Server] INFO Arena // -----------------------------------------------
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .CoM7.run(SourceFile:47)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .u.native(SourceFile:25)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .aC.startArena(SourceFile:334)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .aC.throw(SourceFile:384)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .X.startTimer(SourceFile:447)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .X.volatile(SourceFile:367)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .K.native(SourceFile:55)
11.04 18:33:02 [Server] INFO at org.mineacademy.corearena.short. .J.const(SourceFile:106)
11.04 18:33:02 [Server] INFO java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
11.04 18:33:02 [Server] INFO Arena // CoreArena 2.0.1 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.

**Comment by kangarko** [comment]
What is your MC version?

**Comment by kadika66** [comment]
Running the latest build of 1.13.2 as well as the latest builds mob Arena and boss

**Comment by kangarko** [comment]
Please update to the next version. Don't use any plugman or anything, restart. Make sure there is no other version of the plugin your plugins folder. If unsure just post me a screen of your plugins folder. I am closing this in faith this will be fixed, if not, comment below.

**Comment by kadika66** [comment]
I've made sure that core Arena boss and gameapi are updated
Even attempting to make a zombie with no modification causes this error on startup of the Arena adding one custom from monster to a Arena causes this error 17.04 21:02:10 [Server] INFO Arena // GG! The game in mob2 has finished!
17.04 21:02:10 [Server] INFO Arena // *-----------------------------------------------*
17.04 21:02:10 [Server] INFO Arena //  Stopping arena for safety.
17.04 21:02:10 [Server] INFO Arena //  NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
17.04 21:02:10 [Server] INFO Arena //  Error while spawning mobs in mob2
17.04 21:02:10 [Server] INFO Arena // *-----------------------------------------------*
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .CoM7.run(SourceFile:47)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .u.native(SourceFile:25)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .aC.startArena(SourceFile:334)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .aC.throw(SourceFile:384)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .X.startTimer(SourceFile:447)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .X.volatile(SourceFile:367)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .K.native(SourceFile:55)
17.04 21:02:10 [Server] INFO at org.mineacademy.corearena.short. .J.const(SourceFile:106)
17.04 21:02:10 [Server] INFO java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
17.04 21:02:10 [Server] INFO Arena // CoreArena 2.1.0 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
17.04 21:02:09 [Server] INFO Arena // The game in mob2 has begun (1/8)!

[test.zip](https://github.com/kangarko/CoreArena/files/3092412/test.zip)

**Comment by kadika66** [comment]
------------------------------------[ 18.04.2019 16:35:50 ]-----------------------------------
CoreArena 2.1.0 encountered a NoClassDefFoundError
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_111
Plugins: Boss v3.0.6, WorldEdit v7.0.0-SNAPSHOT;4141-99da55d, GameAPI v3.0.0, CoreArena v2.1.0, WorldGuard v7.0.0-SNAPSHOT;1840-0ebb4e0
----------------------------------------------------------------------------------------------

More Information: 
Error while spawning mobs in Nightfall
%error
Stopping arena for safety.
NoClassDefFoundError org/mineacademy/corearena/lib/boss/api/BossAPI
	 at org.mineacademy.corearena.short. .J.const(SourceFile:106)
	 at org.mineacademy.corearena.short. .K.native(SourceFile:55)
	 at org.mineacademy.corearena.short. .X.volatile(SourceFile:367)
	 at org.mineacademy.corearena.short. .X.startTimer(SourceFile:447)
	 at org.mineacademy.corearena.short. .aC.throw(SourceFile:384)
	 at org.mineacademy.corearena.short. .aC.startArena(SourceFile:334)
	 at org.mineacademy.corearena.short. .u.native(SourceFile:25)
	 at org.mineacademy.corearena.short. .CoM7.run(SourceFile:47)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks, I should have fixed this in the next ver
