### ISSUE TITLE
[how] Do I set custom XP for mythic mobs?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#20]
At present it allows setting custom XP for entities in the enittiy list, but my mobs are all mythicmobs, how do I set their custom Xp drops?

**Comment by kangarko** [comment]
Hello,

I am sorry but what you ask is not possible.

**Comment by FrozenBeard** [comment]
If the spawner is spawning the Mythic Mobs, it knows what mobs are being spawned, there are many ways this could be done. If it isn't already implemented, it needs to be. The plugin boasts Mythic Mobs integration, its the SOLE reason I bought the plugin, I don't want to use the crappy default mobs, whats the point, how is that Unique? how is that going to Keep players playing as you post all over your plugin page. Making the mobs unique is the sole purpose that makes this good. 
You could Assign ID's to each mob spawned, then drop XP based on that, you could Check the mobs name on kill to match that of the MythicMobs Mob name to drop XP appropriately. 
Mythic Mobs even allows an on-death event to happen.

**Comment by kangarko** [comment]
Allright, you convinced me, I am leaving this open but my focus goes at present on bug fixing and then suggestions.

I see an easy way to simply specify the name of the boss from MythicMobs or BOSS in the config. BOSS allows that, MythicsMobs should.

**Comment by kangarko** [comment]
Alright, I have searched the code and implemented it. Simply type the mythicboss' name to the "Kill" section 

    Kill: 
      #
      # The experience applied for all mobs if not specified below.
      #
      Global: "10 + (5 * {phase})"
      #
      # Experience for killing players
      #
      Player: "30 + (6 * {phase})"
      #
      # If you use Boss or MythicMobs, you can specify rewards for bosses you created there.
      #
      "Elite Skeleton": "100 + 10 * {phase}"

**Comment by FrozenBeard** [comment]
Dope. this is perfect thanks. 
Is there a way to get these dev builds?

**Comment by kangarko** [comment]
Will be up tonight.

**Comment by FrozenBeard** [comment]
Do I need to do the maths the same as CREEPER: "15 + (5 * {phase})", there are no round brackets in your "Elite Skeleton": "100 + 10 * {phase}" example.

**Comment by kangarko** [comment]
Normal mathematical rules apply. Use brackets to specify the priority of the calculated parts explicitly, or when unsure.
