### ISSUE TITLE
Couple More Suggestions/Improvements

### ISSUE THREAD

**Issue by Zer0ToHero** [kangarko/CoreArena#200]
So you recently added something that really helps me configure my arenas to be a lot easier on being able to catch up after losing so much health after a wave - being the wait time - but since then I've thought of a couple more features which I'm not sure that do exist, but would love to see.

1: Scaling with Player Amount
I'm using the MythicMobs plugin with CoreArena and was wondering if it's possible, or can ever be possible, to allow for the mobs to scale their damage/health/armour with how many players are in the lobby. This would make it so that the arena isn't too hard for only one player, but not too easy for say, five players. I've been told that this wouldn't be possible on MythicMobs' end, so I've come here to suggest that.

2: Spectators
With the current tools (Clone, Monster, Player, Lobby and Region), I was wondering if there's a possibility of a sixth tool, being a Spectator Area, where players spawn after they die in the arena in Adventure Mode to look down at what's happening in the arena but cannot fly around through blocks or break anything. (I haven't tested what happens when one of two players dies yet; just assuming that it would either take you back to the point before you joined the lobby or it would put you in spectator mode)

I am aware of these suggestions being added to the Roadmap, however they aren't from too recently so I just want to bring it up again to ask if they will be added and possibly when they could be; I understand that creating plugins and implementing these features can take time and have their drawbacks, but it's hard to not be curious :p

**Comment by kangarko** [comment]
Hi,

1: There's no scaling system in CoreArena directly but you can use MythicMobs or Boss to add spawners that spawn tougher mobs and configure them to run on higher phases or when there's at least a certain amount of players online.

2: Spectator mode has been on hiatus since 2018, due to amount of work required it is currently unplanned, sorry about this. It may come in the future.

Best
Matej

**Comment by Zer0ToHero** [comment]
alright, would love to see the spectator thing but i can be patient :)

thanks for the response! ^^
