### ISSUE TITLE
Arena Start Broadcast

### ISSUE THREAD

**Issue by PersephoneRosee** [kangarko/CoreArena#201]
I'm looking for a way to broadcast when someone has joined the arena, so that others know and can join as well. The start command only runs after the phase has started, and it is too late for people to join.

How can people know to join without being notified of the arena starting? Is this possible?

**Comment by kangarko** [comment]
Thanks for suggesting,

I added a new option, just write the following in your arena yml file and use as the other sections to run the command:

![a](https://i.imgur.com/ekHy6v4.png)
