### ISSUE TITLE
Prevent teleport to arena when playing

### ISSUE THREAD

**Issue by PersephoneRosee** [kangarko/CoreArena#203]
When phase 1 ends in the arena, it restarts again at phase 1 but without mobs. It continues in this loop each time phase 1 ends. It should progress to phase 50. This is the only error I get when someone joins the arena. 

https://hastebin.com/kejeyovuyi.java

Arena Settings: https://hastebin.com/ruxapuziza.shell
Settings: https://hastebin.com/xomudeyunu.coffeescript

Additionally, people are able to teleport into the arena, as a result of /marry tp (Marriage Master). Is there a way to prevent this from happening?

**Comment by kangarko** [comment]
Thanks, this will be fixed.

For the teleport issue, I am leaving this open as a suggestion for the future.

**Comment by kangarko** [comment]
Pulled to roadmap
