### ISSUE TITLE
CoreArena Kauf

### ISSUE THREAD

**Issue by Bluecube88** [kangarko/CoreArena#204]
Hallo Kangarko,

ich habe mir heute dein Plugin gekauft und würde gerne die zwei maps haben.
Habe es heute gekauft über Paypal mit folgender Transaktionscode: 0AF283194C103493P

Liebe Grüße
Bluecube
Email - theumbrella@t-online.de
Discord - Bluecube#3259

**Comment by kangarko** [comment]
Hi,

thanks, I've sent you the link via email.

Matej
