### ISSUE TITLE
Server lag on arena start

### ISSUE THREAD

**Issue by PersephoneRosee** [kangarko/CoreArena#206]
Hello - 
We are using multiple arenas at the moment, and one of the arenas is causing lag, where the server stalls for a few moments upon /ma join. I believe it is due to the snapshots/world edit, although we do not allow destruction of blocks on this particular map, and it doesn't need to be restored. [It's enabled for others, however].
Note: There's no errors or crashing.

Would it be possible to enable/disable restoring for only certain arenas? Or is there a way to remove the snapshots, so the arena will stop causing lag?

**Comment by kangarko** [comment]
Hi,

you can go to your WorldEdit/schematics folder and remove your arena schematic files of your arena, this will stop the lag and destruction:

Files are named like so: <arena>.schematic and <arena>_damaged.schematic

![a](https://i.imgur.com/5IuwVLe.png)
