### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by titidelaff** [kangarko/CoreArena#210]
Hello I get ` Error: Report / CoreArena does not have the localization: messages_fr.yml (try setting Locale to 'en')` 
![Screenshot_1](https://user-images.githubusercontent.com/23405363/59151897-0b5f2880-8a3b-11e9-9f31-e4ce9c496c0b.png)

**Comment by kangarko** [comment]
Sorry this does not work that way, you must use messages_en.yml and edit your custom messages in there.
