### ISSUE TITLE
Define on each spawnpoint spawn distance

### ISSUE THREAD

**Issue by titidelaff** [kangarko/CoreArena#211]
Can you add option define spawn distance in spawnpoint setting?

**Comment by kangarko** [comment]
Hi,

just to understand you clearly - you want a spawner to have a "spawning range" but per spawner? We already have this option globally for all spawners:

![a](https://i.imgur.com/SQgnChz.png) 

There is also another option you may find useful:

![a](https://i.imgur.com/vzaZYbR.png)

Thanks for your patience, last weeks have been quite busy.

**Comment by kangarko** [comment]
Pulled to roadmap
