### ISSUE TITLE
Title block on specific wave or boss

### ISSUE THREAD

**Issue by titidelaff** [kangarko/CoreArena#212]
It would be nice if we could have a block to define titles on specific phases or when a certain spawnpoint is activated to put forward a boss for example

**Comment by kangarko** [comment]
Hey,

I could expand the arena yml file to include custom commands for individual phases, would that be okay with you?

Current settings:

![a](https://i.imgur.com/GCgVrnc.png)

**Comment by kangarko** [comment]
Pulled to roadmap
