### ISSUE TITLE
HIGH-PRIORITY: Translateable player menus

### ISSUE THREAD

**Issue by kangarko** [kangarko/CoreArena#215]
As suggested many times, we should make it possible to translate all menus normal players can see such as the reward menu or class selection menu.

**Comment by Xwdit** [comment]
Yes that's it,please update as soon as possible

**Comment by kangarko** [comment]
We're currently rolling new trainings on MineAcademy.org, however I am looking forward for this update

**Comment by kangarko** [comment]
This will be added, however, due to time constrains we'll be focusing only on the menus your players can see, not on the administrative parts of the plugin.

**Comment by JavaFactoryDev** [comment]
Willl be implemented soon.

**Comment by lackoSK** [comment]
Hello,

This feature is going to be implemented during Xmas.

**Comment by kangarko** [comment]
@JavaFactoryDev @lackoSK did this get implemented?

**Comment by JavaFactoryDev** [comment]
Will be released on the next release:)
