### ISSUE TITLE
Bug Report on Join

### ISSUE THREAD

**Issue by PersephoneRosee** [kangarko/CoreArena#217]
Sorry for all the bug reports...

Now having a new issue with two of the arenas, upon doing /ma j [name] it immediately ends. CoreArena is on the latest version.

Console Error:  https://pastebin.com/HCdaPm6b

Error log: https://pastebin.com/NjSnzCPR

**Comment by kangarko** [comment]
Thank you, I attempt to fix this. This should be solved in todays new version but you can comment below in case you run into any more issues.

**Comment by kangarko** [comment]
I am sorry for that you discovered these errors and the inconvenience. Usually I test my plugins however I apology for failing to discover those before pushing a new release.
