### ISSUE TITLE
Bad performance issues

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/CoreArena#225]
Hello,

At first, you can check [my timings](https://timings.aikar.co/?id=843356b607314e26ba208afbb31b618a). I'm using on my skyblock server CoreArena as "Dungeons" implementation, and every monster spawn within is done with Boss plugin.

There are some random "lagspikes" every so often, I think it might happen when CoreArena spawns a bunch of mobs (in this case, Boss mobs) in some Arena.

Oh, and I'm having these random errors in my Boss plugin log: https://pastebin.com/j2MbY3KM

Could you please look into this? I'm not sure what causes these performance issues.

Using TacoSpigot 1.8.8 (basically paperspigot)
CoreArena v2.3.10
Boss 3.4.10

**Comment by kangarko** [comment]
Hello,

seems like it's coming from Boss, may I see your folder from Boss as a ZIP please?

**Comment by TheIronMinerLv** [comment]
[boss.zip](https://github.com/kangarko/CoreArena/files/3535389/boss.zip)
@kangarko

**Comment by kangarko** [comment]
I've solved a problem I found in your error.log file, please test the next version, if the lag arises again let me know and post a new timings, thanks.

**Comment by kangarko** [comment]
Closing in good faith it has been resolved, if not comment below
