### ISSUE TITLE
Pillagers turn to Sheep Eggs in Monster Spawn Points

### ISSUE THREAD

**Issue by Zer0ToHero** [kangarko/CoreArena#227]
I find it strange that Pillager Spawn Eggs don't work in the Monster Spawn Points, while Vindicators/Evokers do work. I've used this plugin with MythicMobs, and I tried to change some values of the Pillager, but that didn't work. So I removed the Pillager entirely from my MythicMobs' VanillaMobs.yml and they still turn to Sheep Eggs so I assume it's CoreArena being weird.

**Comment by Zer0ToHero** [comment]
Upon further testing I've noticed that the plugin probably doesn't support 1.14 Mobs (which is why Evokers and Vindicators work). Is there any possible ETA on the plugin getting an update to support them? (Or if there is a new version that I've just missed please correct me)

**Comment by Zer0ToHero** [comment]
I've done some testing with it and there seems to be an odd problem where, I put a Pillager and a Ravager spawn egg into my Monster Spawn Point and started the arena. It worked fine. I then ended the arena, started it again and on Wave 1 it spawned a Pillager and a Sheep, Wave 2 spawned a Ravager and a Sheep, and the rest of the waves were skipped due to having two Sheep spawn on each wave.

I have it set up so that there are a Maximum of 5 Waves, and on each wave there is meant to be spawned a Pillager and a Ravager. It spawns the Pillager and Ravager despite the fact that the spawn eggs in the Monster Spawn Points have changed themselves to Sheep Spawn Eggs.

It isn't a problem on the end of MythicMobs, as the console shows no errors when setting it into debug mode, so I assume it is on CoreArena's end.

**Comment by kangarko** [comment]
Hey,

if you're using any Boss plugin, we convert those eggs into Sheep Eggs but hook that plugin. If you remove the plugin or Boss, those eggs turn into their Sheep origin.

I don't know why Pillager spawn eggs don't work, are you using the vanilla eggs? Ensure no plugin is preventing them from spawning in that region or at all.

Try using the vanilla eggs not MythicMobs and see if the problem persist. CoreArena is future proof and I am strong in that it supports new eggs including 1.14.

**Comment by Zer0ToHero** [comment]
I'm not using Boss and they are just vanilla eggs - It might be another plugin that could be possibly outdated. I'll get everything updated and see what happens, if it doesn't work I could try reinstalling CoreArena to see if that helps anything.

**Comment by Zer0ToHero** [comment]
https://streamable.com/atvh1 <-- Here's a recording of what exactly happens. We aren't using the Boss plugin, nor are there any plugins that could interfere this way.

**Comment by kangarko** [comment]
Good news, I have tracked it down and it was not in CoreArena but in the underlying Foundation library!

Patched: https://github.com/kangarko/Foundation/commit/be14b6021d109da86a8a3a06cd5592a88b1981a5

**Comment by Zer0ToHero** [comment]
Amazing, thank you!
