### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Patrickprogramming** [kangarko/CoreArena#228]
Hey this plugin looks very promising and almost exactly what Im looking for after playing around with MobArena but missing a lot of features with it. However there is one thing holding me back from buying. I need to absolutely sure that this offers the same functionality as MobArena (for example being able to use ANY custom item in class setups, MMOItems, magic etc they all work in MobArena). Is this also possible with your plugin?

**Comment by kangarko** [comment]
I believe I answered something like that in the discussion.

Next time just ask here ;) If you run into issues open a ticket here.
