### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Panglosic** [kangarko/CoreArena#229]
Hi, will this plugin work with https://www.spigotmc.org/resources/mmoitems-premium.39267/ 
https://www.spigotmc.org/resources/%E2%9A%94-heroes-premium-%E2%9A%94.24734/
https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/ .

Also just wondering if I could remove stuff, all I want is the spawning feature to spawn mythicmobs/mobs

**Comment by kangarko** [comment]
Hello,

CoreArena should work with mcmmo items and Heroes, you can simply drag and drop your items to the classes. You can also use your own equipment if you want.

You can remove all you don't need except and use Boss or MythicMobs eggs directly in spawners.
