### ISSUE TITLE
[Request] Setting Worldguard parameters on start/stop.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#23]
I want to be able to set fire-spread on a WG region (Or the Arena region).
This could easily be accomplished by allowing commands to be run before/after an arena is started/stopped.

**Comment by kangarko** [comment]
What parameters do you need in those commands? I mean variables like location, region name, etc.

Example:

    /wg region <x> <y> <z>

**Comment by FrozenBeard** [comment]
`/wg flag -w Halloween2017 Halloween2017 fire-spread deny`

If its being run from console/plugin then you need to specify the world name, my world-name just happens to have the same name as the region name I gave my arena.

Best if we could set the command at start/stop then we have more options for triggering other things to happen too.

**Comment by kangarko** [comment]
Implemented.

**Comment by FrozenBeard** [comment]
Good job, thanks man.
