### ISSUE TITLE
Player/Mob spawnpoints dont work on some block?

### ISSUE THREAD

**Issue by HumanTarget** [kangarko/CoreArena#230]
Why can't i place player or mob spawn points on some blocks? Specifically for my case right now, any colored concrete. The entire map is made out of concrete is not being able to place these spawnpoint ruins everything. Is there a blackwhite/whitelist of blocks somewhere, or anyway to force a spawnpoint where i want it?

**Comment by kangarko** [comment]
Hey,

we have a hardcoded list of materials you can safely put spawn points on. 

I have greatly expanded that list to the next version :)
