### ISSUE TITLE
Arena Tools

### ISSUE THREAD

**Issue by austinprado** [kangarko/CoreArena#231]
Whenever using Arena Tools they do not do anything. I have no errors in console and have op and *. Any suggestions as to why they may not work. Using Paper 1.12

**Comment by kangarko** [comment]
What specific tools don't work? Just make sure you are actually editing the arena when using them. If you already have them give yourself them again as they may stop working over a restart if you retain them in the inventory.

**Comment by austinprado** [comment]
The issue was fixed when i went back one update before the update stated that you updated what blocks could be used as starting points or something. Must be something wrong with the last update.

**Comment by kangarko** [comment]
Thanks fixed! Was actually a problem in a library we are using.
