### ISSUE TITLE
Arena Ending

### ISSUE THREAD

**Issue by WarnDangerous** [kangarko/CoreArena#232]
I do not understand how to stop the arena when the players killed all the mobs of the last phases of the mob arena.
I set in the config :
  Arena_End: 10

But it doesn't stop the arena at the end of the 10th waves

**Comment by kangarko** [comment]
Hello,

you can use the Arena_End_No_Monsters instead of Arena_End option.

![a](https://i.imgur.com/ZHQ133o.png)
