### ISSUE TITLE
Couple Issues/Questions

### ISSUE THREAD

**Issue by austinprado** [kangarko/CoreArena#233]
1. How do you stop the mobs from stacking?
2. Does worldguard affect the TNT and TNT bow because neither are causing any explosions and you cant place the TNT.

**Comment by austinprado** [comment]
Also I am confused on perm nodes. Is there a complete -permission list. Especially perms for joining arenas/ picking classes

**Comment by kangarko** [comment]
Hello,

1. This is your stacking plugin, unfortunately we cannot "see" what it does and cannot prevent it.

2. Yes please disable those flags on your arena world.

This is our complete permission list, simply replace {plugin.name} with "corearena":
https://pastebin.com/Jpean8uk
