### ISSUE TITLE
Setting a Class to an individual arena

### ISSUE THREAD

**Issue by 8eeved** [kangarko/CoreArena#236]
Hi, I have been trying to sort this out for over a week now. when a player lands in the lobby of an Arena they are presented with a window offering ALL available Classes and can choose which ever they want. I don't want this to happen, seeing how we have a spleef arena and its kinda silly to be able to choose a class that has TNT when all you need is a shovel. 
All arenas have their own individual class signs on the wall that you are able to select ,which works fine, if there is a way to disable this window that opens automatically offering all the classes when you first enter the lobby I sure would appreciate being told how to do it.
I'm not sure if this is the correct place to be asking for help and I am truly sorry if it isn't, but I would be more than thankful if someone has a suggestion to get around my issue.
Cheers, Mark

**Comment by kangarko** [comment]
Thanks, I added "Open_Class_Menu" setting to your arena .yml file to the next version, you will be able to disable it.
