### ISSUE TITLE
CoreArena 2.3.10 is not working 

### ISSUE THREAD

**Issue by LegendCObra** [kangarko/CoreArena#239]
I am on 1.8 
and it says 
------------------------------------[ 16.09.2019 19:41:18 ]-----------------------------------
CoreArena 2.3.16 encountered a CoM1
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: EpicVouchers v2.0, NoHunger v1.0, FixIt v4.0, PlaceholderAPI v2.9.2, InviteSystem v1.1.0, PlugMan v1.8.1, Ninja v1.1.0, RewardPRO v3.17, KillReward v0.2, GameAPI v3.1.2, VolticGod v1.0-RELEASE, LiteBansGUI v3.1, ViaVersion v1.6.0, MVdWUpdater v1.6.0, StaffPlus v3.2.2, COM_Zombies v1.0.5, AIO-Jetpacks v1.0.7, CoreProtect v2.12.0, VoteRoulette v3.2.3, WorldEdit v6.1.7;dd00bb1, OpenInv v3.1.2, killStats v3.0, DragonMOTD v1.0, AltsRevealer v1.4.1, ClearLag v3.0.6, CrackShot v0.98.9, BuycraftX v10.1.4, Votifier v1.9, KillStreaks v1.4.0, The Multiverse-Core Plugin, ProtocolLib v3.6.4, Launchpads v1.8, MVdWPlaceholderAPI v2.5.1, DiscordLinkPlugin v1.0, DeluxeMenus v1.10.5, ColoredTab v1.1, TrollCommandsPlusPlus v7.29.56, PermissionsEx v1.23.4, TAB v1.7.0, AntiBuild v2.9.2, XP v1.0, Vault v1.7.1-b91, CrazyCrates v1.8.3, LastLoginAPI v1.1.1, StackableItems v1.0.5, Parties v2.6.0, EpicRename v3.4, Matrix v2.1.3, AntiCommandTab v3.4, MobArena v0.104, HolographicDisplays v2.3.2, WorldGuard v6.1, VolticClasses v1.21, ChatItem v1.3.6.2, VolticParty v1.0-SNAPSHOT, PlayerVaults v3.6.0-bSNAPSHOT, PartyHeal v1.0, CoreArena v2.3.16, GUIPlus v1.23, HeadHunter v1.4.1a, Essentials v2.15.0.20, LiteBans v2.3.18, Citizens v2.0.16-SNAPSHOT (build 1267), ColoredTags v2.1.3, KitPreview v1.0.2-SNAPSHOT, EssentialsChat vTeamCity, CombatTagPlus v1.2.3, TokenEnchant v14.1.6, CrazyEnvoy v1.2.8.3, Duels v3.2.2, CommandNPC v1.9.1, EssentialsSpawn vTeamCity, TitleManager v2.1.3, EnchantmentBook v9.1.0
----------------------------------------------------------------------------------------------

More Information: 
Please install WorldEditBridge from https://spigotmc.org/resources/65709
CoM1 Report / Please install WorldEditBridge from https://spigotmc.org/resources/65709
	 at org.mineacademy.corearena.short. .PrN.native(SourceFile:150)
	 at org.mineacademy.corearena.CoreArena.native(SourceFile:33)
	 at org.mineacademy.corearena.short. .bh.implements(SourceFile:43)
	 at org.mineacademy.corearena.short. .coM4.onEnable(SourceFile:235)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
----------------------------------------------------------------------------------------------

------------------------------------[ 16.09.2019 19:45:46 ]-----------------------------------
CoreArena 2.3.16 encountered a CoM1
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: EpicVouchers v2.0, NoHunger v1.0, FixIt v4.0, PlaceholderAPI v2.9.2, InviteSystem v1.1.0, PlugMan v1.8.1, Ninja v1.1.0, RewardPRO v3.17, KillReward v0.2, GameAPI v3.1.2, VolticGod v1.0-RELEASE, LiteBansGUI v3.1, ViaVersion v1.6.0, MVdWUpdater v1.6.0, StaffPlus v3.2.2, COM_Zombies v1.0.5, AIO-Jetpacks v1.0.7, CoreProtect v2.12.0, VoteRoulette v3.2.3, WorldEdit v6.1.7;dd00bb1, OpenInv v3.1.2, killStats v3.0, DragonMOTD v1.0, AltsRevealer v1.4.1, ClearLag v3.0.6, CrackShot v0.98.9, BuycraftX v10.1.4, Votifier v1.9, KillStreaks v1.4.0, The Multiverse-Core Plugin, ProtocolLib v3.6.4, Launchpads v1.8, MVdWPlaceholderAPI v2.5.1, DiscordLinkPlugin v1.0, DeluxeMenus v1.10.5, ColoredTab v1.1, TrollCommandsPlusPlus v7.29.56, PermissionsEx v1.23.4, TAB v1.7.0, AntiBuild v2.9.2, XP v1.0, Vault v1.7.1-b91, CrazyCrates v1.8.3, LastLoginAPI v1.1.1, StackableItems v1.0.5, Parties v2.6.0, EpicRename v3.4, Matrix v2.1.3, AntiCommandTab v3.4, HolographicDisplays v2.3.2, WorldGuard v6.1, VolticClasses v1.21, ChatItem v1.3.6.2, VolticParty v1.0-SNAPSHOT, PlayerVaults v3.6.0-bSNAPSHOT, PartyHeal v1.0, CoreArena v2.3.16, GUIPlus v1.23, HeadHunter v1.4.1a, Essentials v2.15.0.20, LiteBans v2.3.18, Citizens v2.0.16-SNAPSHOT (build 1267), ColoredTags v2.1.3, KitPreview v1.0.2-SNAPSHOT, EssentialsChat vTeamCity, CombatTagPlus v1.2.3, TokenEnchant v14.1.6, CrazyEnvoy v1.2.8.3, Duels v3.2.2, CommandNPC v1.9.1, EssentialsSpawn vTeamCity, TitleManager v2.1.3, EnchantmentBook v9.1.0
----------------------------------------------------------------------------------------------

More Information: 
Please install WorldEditBridge from https://spigotmc.org/resources/65709
CoM1 Report / Please install WorldEditBridge from https://spigotmc.org/resources/65709
	 at org.mineacademy.corearena.short. .PrN.native(SourceFile:150)
	 at org.mineacademy.corearena.CoreArena.native(SourceFile:33)
	 at org.mineacademy.corearena.short. .bh.implements(SourceFile:43)
	 at org.mineacademy.corearena.short. .coM4.onEnable(SourceFile:235)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
----------------------------------------------------------------------------------------------

------------------------------------[ 16.09.2019 19:48:09 ]-----------------------------------
CoreArena 2.3.10 encountered a lPT8
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: EpicVouchers v2.0, NoHunger v1.0, FixIt v4.0, PlaceholderAPI v2.9.2, InviteSystem v1.1.0, PlugMan v1.8.1, Ninja v1.1.0, RewardPRO v3.17, KillReward v0.2, GameAPI v3.1.2, VolticGod v1.0-RELEASE, LiteBansGUI v3.1, ViaVersion v1.6.0, MVdWUpdater v1.6.0, StaffPlus v3.2.2, COM_Zombies v1.0.5, AIO-Jetpacks v1.0.7, CoreProtect v2.12.0, VoteRoulette v3.2.3, WorldEdit v6.1.7;dd00bb1, OpenInv v3.1.2, killStats v3.0, DragonMOTD v1.0, AltsRevealer v1.4.1, ClearLag v3.0.6, CrackShot v0.98.9, BuycraftX v10.1.4, Votifier v1.9, KillStreaks v1.4.0, The Multiverse-Core Plugin, ProtocolLib v3.6.4, Launchpads v1.8, MVdWPlaceholderAPI v2.5.1, DiscordLinkPlugin v1.0, DeluxeMenus v1.10.5, ColoredTab v1.1, TrollCommandsPlusPlus v7.29.56, PermissionsEx v1.23.4, TAB v1.7.0, AntiBuild v2.9.2, XP v1.0, Vault v1.7.1-b91, CrazyCrates v1.8.3, LastLoginAPI v1.1.1, StackableItems v1.0.5, Parties v2.6.0, EpicRename v3.4, Matrix v2.1.3, AntiCommandTab v3.4, HolographicDisplays v2.3.2, WorldGuard v6.1, VolticClasses v1.21, ChatItem v1.3.6.2, VolticParty v1.0-SNAPSHOT, PlayerVaults v3.6.0-bSNAPSHOT, PartyHeal v1.0, CoreArena v2.3.10, GUIPlus v1.23, HeadHunter v1.4.1a, Essentials v2.15.0.20, LiteBans v2.3.18, Citizens v2.0.16-SNAPSHOT (build 1267), ColoredTags v2.1.3, KitPreview v1.0.2-SNAPSHOT, EssentialsChat vTeamCity, CombatTagPlus v1.2.3, TokenEnchant v14.1.6, CrazyEnvoy v1.2.8.3, Duels v3.2.2, CommandNPC v1.9.1, EssentialsSpawn vTeamCity, TitleManager v2.1.3, EnchantmentBook v9.1.0
----------------------------------------------------------------------------------------------

More Information: 
Please install WorldEditBridge from https://spigotmc.org/resources/65709
lPT8 Report / Please install WorldEditBridge from https://spigotmc.org/resources/65709
	 at org.mineacademy.corearena.short. .Com8.native(SourceFile:155)
	 at org.mineacademy.corearena.CoreArena.native(SourceFile:32)
	 at org.mineacademy.corearena.short. .bg.this(SourceFile:43)
	 at org.mineacademy.corearena.short. .Com3.onEnable(SourceFile:235)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
----------------------------------------------------------------------------------------------

**Comment by JavaFactoryDev** [comment]
Just do what he says. Install WorldEdit Bridge. (Not an official supporter or something like that, just read this)

Greetings,
Leonhard | EsGibtKeineMitte | JavaFactory

**Comment by kangarko** [comment]
Please install WorldEditBridge from https://spigotmc.org/resources/65709
