### ISSUE TITLE
HIGH-PRIORITY: CoreArena missing feature

### ISSUE THREAD

**Issue by mewter** [kangarko/CoreArena#243]
Hi there, i purchased the plugin CoreArena and it's missing 1 important thing and that is reward per wave, not just items but custom commands ran by server as well.

The only reason i purchased it was because it said "rewards" if i knew it was rewards **during** the waves i wouldn't have bought it.

please add this and then this plugin will be even greater, it's kind of useless for me without it.

**Comment by kangarko** [comment]
Hello,

we have a completely different logic from most arena plugins. In CoreArena, players earn soft currency called Nuggets during their arena play. Rewards are implemented as a separate menu /ma rewards that can be accessed outside of arena at any time. In that menu, players exchange Nuggets for items. There are therefore no rewards during the waves, but Nuggets given to players.

You can however place the [Upgrade] signs in the arena to enable players to obtain special items as they progress during the arena play. These items can only be used during the arena play and will be taken away when players leave the arena.

Commands triggered upon each wave are planned. Is this something that would be sufficient for you?

**Comment by mewter** [comment]
That is a good feature but i'd love to have a reward when they are done in the Arena's, for example give them a few blocks, a permission (through command), etc when X wave is done

The nugget feature is not a reward, it's simply a feature to upgrade throughout the arena.

**Comment by kangarko** [comment]
Alright so you mean the following:

Do the following after the game:
- Ability to run commands for players (that is already there, see your arena yml file)
- Give players specific items

Do the following upon each wave, or specific waves:
- Run commands (already there but for each wave, not for selected ones)
- Give players specific items

Let me know if I missed something!

**Comment by mewter** [comment]
not **_for players_** but console commands with a player variable, e.g "give %player% stone 1" or a other command. after the arena is over so they get **outside rewards** and it will sum up how many waves you have done then hand out the rewards you specified in the config and not arena nugget rewards.

Here is an example from the _free_ mob arena plugin which has this:

>     rewards:
>       waves:
>         every:
>           '15': iron_ingot:16, gold_ingot:8, diamond:1
>         after:
>           '13': iron_sword, iron_pickaxe, iron_spade

These rewards are given **after** they die/finish the arena so they get to keep this when they play normal.

**Comment by kangarko** [comment]
Thanks, this is a great suggestion and we will implement this.

**Comment by mewter** [comment]
Thank you so much for doing this, we had to revert back to the old arena plugin but after hearing this we will make sure to use yours as soon as the new reward features is added!

It was honestly the only thing missing from this plugin ^_^

**Comment by kangarko** [comment]
The MobArena free plugin? I am towards working on it, however due to me being the only one managing all plugin at this moment it'll come in the following weeks, but it's on the top list.

**Comment by JavaFactoryDev** [comment]
Will be implemented soon.

**Comment by lackoSK** [comment]
Hello,

This feature is going to be implemented during Xmas.

**Comment by kangarko** [comment]
@JavaFactoryDev @lackoSK did this get implemented?

**Comment by JavaFactoryDev** [comment]
Added:)
