### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by quantom16** [kangarko/CoreArena#249]
Hi I wanted to know if I can type a command that can make players able to break ice blocks 

let me explain more
I'm
 using a projectkorra plugin (it's an avatar/bending plugin) 
so players with water abilities can shoot ice into other players and make an ice sphere around them so I don't want the players to be able to destroy anything I just want them to be able to break new created blocks if it's possible
![Screenshot_2](https://user-images.githubusercontent.com/41945200/66271737-6cbcca00-e86a-11e9-9126-a40da7bda263.png)
(There is a screenshot of the ice sphere I was talking about)

looking forward to hearing from you, huge thanks! 

edit:
and I was wondering I could make it so the players will just type a costume command and be teleported to the arena.
and how do I disable the waiting option and the time options, I want it to be like kind of kit PVP when you teleport to the arena you just fight and if you die you'll be spawned in the spawn and then you can reconnect to the arena over and over again.

**Comment by kangarko** [comment]
Hello!

To enable breaking of ice blocks, add ICE or any other blocks you find [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) to Interaction.Allow_Breaking in your arena yml file.

Players cannot join the arena once it is started to be played. They can use /ma join command to enter the lobby while it is stopped or starting.

The entire plugin was not designed to offer an instant play experience, I apology. However, you can make a secret "debug.lock" file and then you can set the waiting delay to 0 or 1 seconds. Beware, adding debug will make players be able to execute commands during arena play, so I recommend you isolate your arena into a separate world where you remove their permission to run most commands.

Matej

**Comment by quantom16** [comment]
Hi, thanks for replying I created a debug.lock file and I put it inside the corearena and I don't know what to type there...
if you can help me with it I'll really gonna appreciate it
