### ISSUE TITLE
Rotate the arena automatically on server/world join

### ISSUE THREAD

**Issue by Andre601** [kangarko/CoreArena#256]
I set up an arena with a region, the initial and destroyed snapshot and classes and enabled it.
The setting to enable bungeecord in the config is set to true, yet even after server restart is the plugin still acting as if it is not in BungeeCord mode.
Is there any kind of permission that prevents me from joining the arena, when switching to the server?

**Comment by kangarko** [comment]
@Andre601 I apology for a so late reply!

There is no BungeeCord mode, the config option is unused for now. There was a plugin called AutoPlay that would rotate the arenas automatically as an extension of CoreArena but it was scrapped.

How are you looking forward to use CoreArena with BungeeCord specifically? You should not be automatically joined to the arena when you join the server, that is not any inbuilt behavior of pure CoreArena.

**Comment by Andre601** [comment]
> You should not be automatically joined to the arena when you join the server, that is not any inbuilt behavior of pure CoreArena.

But I want exactly that.
I want to keep CoreArena on its own separate server and when players join that server should they be automatically be sent into the lobby of the game, to play it.

**Comment by kangarko** [comment]
That was the purpose of the AutoPlay plugin, unfortunately it has been discontinued and we don't have the capacity to maintain it any longer, I apology.

**Comment by kangarko** [comment]
Maybe we bring AutoPlay back as a free plugin (it used to be originally a part of CoreArena before it got bigger). When I build a team of talented people we definitely improve what we have to offer right now.

**Comment by kangarko** [comment]
Leaving open as a mid/long-term suggestion

**Comment by Andre601** [comment]
The title isn't really what I was suggesting in that case.

It would honestly be fairly easy to implement BungeeCord support.
Just make a section like this in the main config;
```yaml
BungeeCord:
  Enabled: false
  Server: 'hub'
  Motd: # Change MOTD depending on game status.
    Lobby: 'lobby'
    Ingame: 'ingame'
    Ending: 'ending'
```

And when the option is enabled would CoreArena automatically join the player to an Arena (And perhaps to a random one if you have multiple ones).
When the player leaves or the game is over would CoreArena send them to the defined server with the help of the plugin message channel.
This is honestly not that hard to implement.

**Comment by kangarko** [comment]
Thank you.

I currently don't have time to implement this, but if you are a developer I can share the necessary code to achieve it.

**Comment by Andre601** [comment]
> Thank you.
> 
> I currently don't have time to implement this, but if you are a developer I can share the necessary code to achieve it.

I am indeed a developer.
I'm just not sure if I could bring up the time, to understand the code you're using (Like how you handle different things) and how I could/should implement such features.

**Comment by kangarko** [comment]
I understand. If you decide to have a look, email me at matej@mineacademy.org. Until then it stays as a suggestion
