### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by BluesephSounds** [kangarko/CoreArena#259]
What's the proper placeholder to return a player's username for this section of the arenas config? The one I currently have is not working, and I have also tried `%player_name%`. Thank you for your time!

   `Phase: 
    Player: []
    Console:
    - geco give {player} 1 ArenaXP`

**Comment by kangarko** [comment]
There is no {player} placeholder for the "Console" section, however you can use {player} for the Player section since it will be run for each player.
