### ISSUE TITLE
[Request] Spectate for players on continuing game 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#26]
Players have requested that they can spectate a game once they have died/ended/logged in during a game.

**Comment by kangarko** [comment]
Hello,

for the time being, there is no spectate mode for safety reasons.

Please describe how would you like the mode to be like? Should players obtain survival mode and be locked inside of a room, or be invisible and fly around the arena?

**Comment by FrozenBeard** [comment]
Spectate and fly around the arena. I run the mini-game on its own separate server specifically to protect against things like duping, spectate people escaping etc lol

The default spectate control sucks, like trying to use players heads in the hotbar to go to them is a horrible way to navigate. It would be easier with 2 buttons in the hotbar to cycle players. and an option to still click on them to go into their heads, or even better have a way to cycle from their heads, like when you punch someone when in gm3 you go into their head.

**Comment by kangarko** [comment]
Sounds good, I'll keep this in mind when implementing it. Thank you, appreciated your feedback.

**Comment by Miclebrick** [comment]
+1 this NEEDS to be a thing

**Comment by kangarko** [comment]
@kangobot
