### ISSUE TITLE
Nuggets do not get paid out properly to players

### ISSUE THREAD

**Issue by Dynamite99** [kangarko/CoreArena#260]
I have players report that nuggets are not properly being paid out to them at the end of games. Any ideas why?

**Comment by Dynamite99** [comment]
Any notes, updates, comments?

**Comment by JavaFactoryDev** [comment]
Hi Dynamite99,

Thanks for using CoreArena,

Please provide follow these report guidelines stated [here](https://github.com/kangarko/Boss/issues/432)
If there is an issue, we will of course fix it asap.

Regards,

Leonhard
