### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by T-Curry** [kangarko/CoreArena#262]
Hi, I was trying to make a map and do commands, but I'm not sure of the proper format on how to do phase-specific commands. So far, I have:
  Phase: 
    Player: 
    Console: 
    - 6 "jukebox region add frontyard https://od.lk/s/NzBfMTA2MTkzMjNf/night.mp4"
    - 11 "warp backyard {player}"
    - 16 "jukebox region add backyard https://od.lk/s/NzBfMTA2MTkyNTBf/fog.mp4"
    - 6 "Night"
    - 11 "Day"

If you could help me put it in the correct format, that would be very helpful. Also,  I included minecraft color codes (ex: &1 &2 &3 &4 etc) and I literally can't join the game using sings nor NPCs with commands. I tried changing the names of the maps by changing the names of the files, but that just deleted all the data

**Comment by JavaFactoryDev** [comment]
Hey T-Curry, 
thanks for using CoreArena.
Could you please send us your whole settings.yml so we could check it.

Regards,
Leonhard

**Comment by T-Curry** [comment]
#  -------------------------------------------------------
#  Welcome to the arena settings file. Here you can setup
#  individual arena properties.
#  -------------------------------------------------------

Lifes: 1
Required_Class_Tier: 1
Allow_Own_Equipment: false
Natural_Drops: false
Random_Respawn_Location: false
Open_Class_Menu: true
Player_Limit:
  Minimum: 1
  Maximum: 8
Mob_Limit: 50
Mob_Spread: 1
Mob_Burn_On_Sunlight: false
Duration:
  Lobby: 5 seconds
  Arena: 45 minutes
  Phase: 5 seconds
Interaction:
  Ignite_Tnts: true
  Spawn_Wolves: true
  Launch_Fireballs: true
  Allow_Placement:
  - STONE_BUTTON
  - WOOD_BUTTON
  Disallow_Auto_Repair:
  - GOLD_SWORD
  Allow_Breaking:
  - VINE
  - LEAVES
  - LEAVES_2
Phase:
  Max_Phase: 31
  PvP: 35
  Chest_Refill: 35
  Players_End: 0
  Arena_End: 31
  Arena_End_No_Monsters: 31
Next_Phase_Mode: monsters
Next_Phase_Wait: 5 seconds
Commands:
  Start:
    Player: []
    Console: []
  Lobby_Start:
    Player: []
    Console: []
  Phase:
    Console:
    - 6 "jukebox region add frontyard https://od.lk/s/NzBfMTA2MTkzMjNf/night.mp4"
    - 11 "warp backyard {player}"
    - 16 "jukebox region add backyard https://od.lk/s/NzBfMTA2MTkyNTBf/fog.mp4"
    - 6 "Night"
    - 11 "Day"
    Player: []
  Finish:
    Console:
    - jukebox region add frontyard https://od.lk/s/NzBfMTA2MTkyNTJf/frontyard.mp4
    - jukebox region add backyard https://od.lk/s/NzBfMTA2MTkyNDlf/Backyard.ogg
    - jukebox region add roof https://od.lk/s/NzBfMTA2MTkzMDlf/roof.mp4
    Player: []
  End:
    Player: []
    Console: []
  Player_Leave:
    Player: []
    Console: []

**Comment by T-Curry** [comment]
I also have some other questions:

Is there a way to add an in-game shop? Also, I would like to add support mobs where players could purchase them and they could be used to fight off mobs. However, every time I spawn one (not using a shop, I still need help with that), the mob's AI is overridden and they attack players. They also have to be killed in order for the waves to progress. Is there any way to make it so this doesn't happen?

**Comment by lackoSK** [comment]
Hi,

Thanks for your suggestions we will consider adding them to CoreAreana.

Can you tell me exactly what you're having problems with? 

Regards,
lackoSK

**Comment by T-Curry** [comment]
I said it several times and I don’t know why it’s so hard to understand.

Can you please tell me how to format a wave-specific command, for instance,
let’s say I wanted to change the time to night when the arena reaches wave
5. How do I code that correctly? As you can see, I attempted it above but
it doesn’t work.

Also, this is more of a fix but I need help with changing the name of
arenas because signs nor NPCs with commands work to allow players into the
arena. I think it’s because I included color codes. Is there a way to
change the name of the arena or get it to work with the colors? I tried
changing the config file but that just deleted all my progress in the arena.

Thanks and please respond sooner

**Comment by lackoSK** [comment]
Hey,

Sorry for the super delay. I miss looked at it.

>Also, this is more of a fix but I need help with changing the name of
arenas because signs nor NPCs with commands work to allow players into the
arena. I think it’s because I included color codes. Is there a way to
change the name of the arena or get it to work with the colors? I tried
changing the config file but that just deleted all my progress in the arena.

You can go into data.db (disable server first) and change the name here.

Again, apologies the delay.

**Comment by T-Curry** [comment]
What about the way to format the phase-specific commands?

**Comment by lackoSK** [comment]
Please, upload your setting on pastebin

**Comment by T-Curry** [comment]
https://pastebin.com/GEqd53RS

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

This might be helpful for you:
>#
# Commands that are run automatically.
# The 'Player' section contains commands run separately as each player (with their permissions),
# and the 'Console' section contains commands run at once from the console.
#
# Useful information for sending commands as the player:
# > Use "@tell <message>" to send messages to the player. Example:
#   Player:
#     - "@tell Hello there, {player}, thank you for playing in {arena}!"
#
# > There is a special command "@connect <server>" that will send player to another server,
#   if you have a BungeeCords network. Replace <server> with the target server.
#

**Comment by kangarko** [comment]
@JavaFactoryDev may you also please take a look? Thanks!

**Comment by lackoSK** [comment]
@T-Curry, so did it helped to you?

**Comment by JavaFactoryDev** [comment]
User is not responding.
