### ISSUE TITLE
I have difficulty to put armor in class

### ISSUE THREAD

**Issue by LordSiix** [kangarko/CoreArena#263]
![Captura](https://user-images.githubusercontent.com/48842692/70488675-216ba580-1abf-11ea-90f1-a0d8f236706a.PNG)
[mftp_zip_2019_12_10_01_58_20.zip](https://github.com/kangarko/CoreArena/files/3942649/mftp_zip_2019_12_10_01_58_20.zip)

**Comment by JavaFactoryDev** [comment]
Please see SpigotMC. We will reply there as you first requested support there.
