### ISSUE TITLE
No Auto-Mode.yml or tool to set waiting lobby

### ISSUE THREAD

**Issue by crazyeightlikesapples** [kangarko/CoreArena#264]
There is no auto-mode.yml folder or the golden shovel tool to set a waiting lobby as shown in the video. 

I am not sure how to get this to work, important for my server

**Comment by JavaFactoryDev** [comment]
Hey crazyeightlikesapples,

This issue is already known and will be fixed asap.

Regards,
Leonhard from MineAcademy.

**Comment by kangarko** [comment]
Hello,

the auto-mode was part of a plugin that later become AutoPlay and is no longer on sale. This feature was unpopular and had some difficult bugs so we decided to remove it permanently. Thank you for your understanding.
