### ISSUE TITLE
Base Health issue

### ISSUE THREAD

**Issue by PengBread** [kangarko/CoreArena#265]
Hello kangarko,
There is a major issue with Core arena. If a player enters the arena with Health Boost, his **base health** gets set to the amount you had with health boost upon leaving the arena.

So for example,
- I have 10 base healths. My health boost gives me extra 2 health = 12 health.
- Joins an arena and leave
- Now i have 12 base health and my boost gives me extra 2 health again which means i have 14 health .

This bug gives u infinite base health as long as you enter the arena with health boost.
No errors or anything. V 2.4.6 because 2.4.7 generated a class error for me.
Server version 1.14.4

**Comment by JavaFactoryDev** [comment]
Hello PangBread,

thanks for using CoreArena.
If we can confirm this issue we will fix it asap.

Regards,
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Hello PangBread,

can you please send us your CoreArena folder as a .zip file?

Regards,
Leonhard from MineAcademy
