### ISSUE TITLE
Missings functions with power signs

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#268]
Hey,
Thanks for at great plugin.
I was thinking, is it possible to make the power sign tricker on a specified phase?
I would like to be able make it like:
First line: [power]
Second line: from phase 3

And then the power signal will first be active at phase 3 and onwards.

Maybe like the spawners, that can be set as "from" "on" "between". 

Can you make it do that?

Thanks in advance
Sune Richardt

**Comment by lackoSK** [comment]
Thank you for your suggestion.

We will consider adding it. However, it's not our most significant priority these days. (We will have a look after the new year)

Thanks!
