### ISSUE TITLE
CoreArena + Boss Spawning

### ISSUE THREAD

**Issue by EnZiiK** [kangarko/CoreArena#269]
//SK
Zdravím.. Dnes som sa pokúšal na svojom Prison servery skombinovať CoreArenu a Boss plugin.. Tak som si založil arénu, nastavil ju na 1 Phase, pretože ju chcem použiť čisto iba na 1 boss wave.. Aréna teda úspešne založená.. Potom som si vytvoril bossa skrz Boss Menu povolil mu spawn v regione arény (ale regiony som musel urobiť 2, 1 s boss regionom a 1 s WorlGuard pretože na servery má úplne vypnutý spawn mobov tak v tomto regione som dal flag že sa môžu mobovia spawnovať).. Ale keď som už chcel bossa v aréne spawnúť vajíčkom nebolo to možné, písalo to stále iba "Unable to spawn Test in this location!", nuž povedal som si že keď to dám do spawneru z arény tak to pôjde, ale mýlil som sa, portlo ma to do arény a hneď "Game Over".. Tak mi to celé akosi nedávalo zmysel a išiel som si spraviť region bez arény tak isto ako v prípade s arénou a tam mi boss išiel spawnúť úplne v pohode, tak som skúšal ešte hodinu experimentovať s tou arénou a nič.. stále dokola ten istý problém.. Tak nakoniec mi ostalo sa obrátiť tu na podporu, snáď mi teda dokážete dajako pomôcť, pretože ja už si fakt neviem stým dať rady.. Vopred ďakujem za odpoveď.

//ENG
Hi.. Today I tried to combine CoreArena and Boss plugin on my Prison server .. So I created arena, set it to 1 Phase, because I want to use it only for 1 boss wave.. So arena was successfully completed.. Then I created a boss through the Boss Menu to allow him to spawn in the arena region (but I had to do 2 regions, 1 with boss region and 1 with WorlGuard because the servers have completely turned off spawn mobs so in this region I put a flag that mobs can spawn). But when I wanted to spawn boss with egg in the arena it doesnt work, in chat appear only "Unable to spawn Test in this location!" But I thought if I put it in the arena spawner it would work but I was wrong , it put me into the arena and immediately "Game Over" .. So it doesnt made any sense to me and then I tried to make a region without the arena as well as in the case with the arena and there boss spawn works without problem, so I tried to experiment with it one more hour but nothing works.. same problem all the time..

// Best Regards
// EnZi

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting this issue and adding such a good description. I will do testing during the weekend. 

Thanks!

**Comment by lackoSK** [comment]
Hello,

So, out of my testing, I am not able to restimulate it. Please provide us exact steps! 

Thanks!

PS: @JavaFactoryDev, you might also have a look. 

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

You will be able to download the fixed CoreAreana in the next update. 

Thanks to you for reporting the issue. 

Regards,
lackoSK
