### ISSUE TITLE
The last help of Autoplay

### ISSUE THREAD

**Issue by TNG-China** [kangarko/CoreArena#270]
Sorry for this issue, Cause I can't find any place to get support, I know you are not long support Autoplay, But our network still using it over 2 years. Anything is perfect just the scoreboard is caused lag that I must restart server per 4 hours, So sad you give up your plugin.
You are my last hope to fix this bug, I know it's a personal request, And I'd love to pay for it about $20, But If you are really really busy, send me the source code please.

Your fans
TNG_From

![image](https://user-images.githubusercontent.com/21065884/72236122-80699080-3610-11ea-9352-18d464888c7f.png)

**Comment by lackoSK** [comment]
Hello,

We are sorry but the support for the autoplay ended. 
We do not offer a source code to download. 

You might try to contact us in a spigot PM. Kangarko must decide to.

Regards,
lackoSK

**Comment by kangarko** [comment]
Hi,

Can you turn off the scoreboard completely? I can make a small edit in the code that will shut off scoreboard completely.

We can't give away source code because it requires another libraries which are used in other premium plugins and we would need to give you a complete training on how to get things compiled

**Comment by TNG-China** [comment]
@kangarko Yes I can, but without a scoreboard, this plugin is no longer useful, I can't see when the game starts and ends, so must enable to get a better experience, It's very important for my network.

If you have time, fix this please, And leave your PayPal account, I'll pay for it, It's very very important for my network, I can't find the same plugin in spigot.

please kangarko.

**Comment by JavaFactoryDev** [comment]
We will have a look soon:)

**Comment by TNG-China** [comment]
Thank you very very much, That helps me a lot.

**Comment by TNG-China** [comment]
@JavaFactoryDev Hello, I still waiting for the fix, please check this.

**Comment by TNG-China** [comment]
@JavaFactoryDev @kangarko 
This is the timing when I enable scoreboard:
[https://timings.aikar.co/?id=51f5ceee85314a72b33f004f23ea0410](url)

Check this plz, I been waiting for a month.

**Comment by TNG-China** [comment]
@kangarko @JavaFactoryDev @lackoSK 

Are you guys even have no an hour to fix this bug that you made?

I been wating for two month check this issue everyday bro!

No respones No reply,

I told you I'd love pay for it, But It's not about money, It's about my server over 50 players, I told them you would fix it, 

what are you guys doing?

If you abandon your old users, close this issue and I will never use your plugin again.

**Comment by lackoSK** [comment]
Hi there,

I am really sorry, but we forgot... Adding this to our dashboard so we will have this always on our eyes.

Thanks, bro.

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hi there @TNG-China,

I have started working since I saw your message and now I am bringing you big updates :)
Worked all day to finish Packet scoreboard and now... It is done..

Contact me over discord please: lackoSK#0001

PS: Our communication will continue on discord: Will close it here.

Regards,
lackoSK
