### ISSUE TITLE
Issue when playing mob arena

### ISSUE THREAD

**Issue by joguerreiro** [kangarko/CoreArena#271]
hi when i click to play a mob arena game the count down happends and i can select the kit but when i get teleported to the arena and do any interaction like click with a sword on the air or a mob hits me or i hit a mob the mob arena stops

when i put the debug on this is shown in the console

>.... [16:08:01 INFO]: The game in spawnarena has begun (1/5)!
>.... [16:08:01 INFO]: [spawning] #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
>.... [16:08:01 INFO]: [spawning] #-#-#-#-#-# Launching spawners for phase 1 #-#-#-#-#-#
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{on 20 phase, 1 ItemStack{WITHER_SKELETON_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn UnholyGladiator, lore=[ , < Left click for menu, > Right click to summon], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4A/Ny8jPqXTPSUzJTCzJL2JgAACPkJoKJgAAAA==}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{from 10 phase, 25% chance, 2 min. players, 5 ItemStack{ZOMBIE_SPAWN_EGG x 5, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn GladiatorZombie, lore=[ , < Left click for menu, > Right click to summon], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4HfPSUzJTCzJL4rKz03KTGVgAABqbCP4JgAAAA==}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{from 10 phase, 25% chance, 2 min. players, 5 ItemStack{ZOMBIE_SPAWN_EGG x 5, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn GladiatorZombie, lore=[ , < Left click for menu, > Right click to summon], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4HfPSUzJTCzJL4rKz03KTGVgAABqbCP4JgAAAA==}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{on 10 phase, 1 ItemStack{WITHER_SKELETON_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn DementedGladiator, lore=[ , < Left click for menu, > Right click to summon], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1lEHRJzU3NK0lNcc9JTMlMLMkvYmAAAFijfg4oAAAA}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{on 20 phase, 3 min. players, 1 ItemStack{WITHER_SKELETON_SPAWN_EGG x 1, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn UnholyGladiator, lore=[ , < Left click for menu, > Right click to summon], enchants={DURABILITY=1}, ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4A/Ny8jPqXTPSUzJTCzJL2JgAACPkJoKJgAAAA==}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{from 5 phase, 75% chance, 4 ItemStack{SKELETON_SPAWN_EGG x 4, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn GladiatorSkeleton, lore=[ , < Left click for menu, > Right click to summon], ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1lEHTPSUzJTCzJLwrOTs1JLcnPY2AAANjBnEooAAAA}}, 2 ItemStack{ZOMBIE_SPAWN_EGG x 2, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn GladiatorZombie, lore=[ , < Left click for menu, > Right click to summon], ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4HfPSUzJTCzJL4rKz03KTGVgAABqbCP4JgAAAA==}}}
>.... [16:08:01 INFO]: [spawning] FAIL - invalid phase
>.... [16:08:01 INFO]: [spawning] 1 ::: Activating Spawner{from 1 phase, 3 ItemStack{SPIDER_SPAWN_EGG x 3, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn ArenaSpider, lore=[ , < Left click for menu, > Right click to summon], ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4HYsSs1LDC7ITEktYmAAACfaJ+YiAAAA}}}
>.... [16:08:01 INFO]: [spawning] Iterating through slot: 3 ItemStack{SPIDER_SPAWN_EGG x 3, SPAWN_EGG_META:{meta-type=SPAWN_EGG, display-name=Spawn ArenaSpider, lore=[ , < Left click for menu, > Right click to summon], ItemFlags=[HIDE_ENCHANTS, HIDE_ATTRIBUTES, HIDE_UNBREAKABLE, HIDE_DESTROYS, HIDE_PLACED_ON, HIDE_POTION_EFFECTS], internal=H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4HYsSs1LDC7ITEktYmAAACfaJ+YiAAAA}}
>.... [16:08:01 INFO]: CoreArena 2.4.9 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
>.... [16:08:01 INFO]: java.lang.NoClassDefFoundError: org/mineacademy/corearena/lib/boss/api/BossAPI
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .double.const(SourceFile:106)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .synchronized.native(SourceFile:55)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .o.protected(SourceFile:402)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .o.startTimer(SourceFile:490)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .N.throw(SourceFile:397)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .N.startArena(SourceFile:340)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .do.native(SourceFile:25)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.lib.fo.model.Com2.run(SourceFile:71)
>.... [16:08:01 INFO]: at java.lang.Thread.run(Thread.java:748)
>.... [16:08:01 INFO]: java.lang.ClassNotFoundException: org.mineacademy.corearena.lib.boss.api.BossAPI
>.... [16:08:01 INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>.... [16:08:01 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
>.... [16:08:01 INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
>.... [16:08:01 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>.... [16:08:01 INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .double.const(SourceFile:106)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .synchronized.native(SourceFile:55)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .o.protected(SourceFile:402)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .o.startTimer(SourceFile:490)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .N.throw(SourceFile:397)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .N.startArena(SourceFile:340)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.short. .do.native(SourceFile:25)
>.... [16:08:01 INFO]: at org.mineacademy.corearena.lib.fo.model.Com2.run(SourceFile:71)
>.... [16:08:01 INFO]: at java.lang.Thread.run(Thread.java:748)
>.... [16:08:01 INFO]: !-----------------------------------------------------!
>.... [16:08:01 INFO]: Error while spawning mobs in spawnarena
>.... [16:08:01 INFO]: ClassNotFoundException: org.mineacademy.corearena.lib.boss.api.BossAPI
>.... [16:08:01 INFO]: Stopping arena for safety.
>.... [16:08:01 INFO]: !-----------------------------------------------------!
>.... [16:08:01 INFO]: GG! The game in spawnarena has finished!

**Comment by JavaFactoryDev** [comment]
Hey joguerreiro,

Thanks for using CoreArena & Reporting this issue.
Please follow: https://github.com/kangarko/Boss/issues/432

Regards,
Leonhard from MineAcademy
