### ISSUE TITLE
Suggestion - Mobwaves from wave x - y

### ISSUE THREAD

**Issue by gaRt3n** [kangarko/CoreArena#277]
Is it possible to implement this feature? Right now it's only possible to create spawner from wave X and spawner which spawn till X

**Comment by Ekute-hub** [comment]
hi, you can TILL, FROM, but also ON for spawn on one phases and BETWEEN for x - y

**Comment by JavaFactoryDev** [comment]
Already possible as stated by @Ekute-hub.
- Thanks to @Ekute-hub
