### ISSUE TITLE
[bug] MySQL communications link failure 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#28]
MySQL is working I can see the table being populated, but it seems to die at end game. its like the connection isn't kept open.
https://pastebin.com/2tup1VQc

**Comment by kangarko** [comment]
Hey,

from my and many other users' testing, it is most likely something with your database. I only had one user reporting the same issue and he also reported it being the case with a few other plugins.

Please see https://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai/2985169#2985169 or contact your server hosting support.

Thank you.

**Comment by FrozenBeard** [comment]
IP address or hostname in JDBC URL is wrong.
Hostname in JDBC URL is not recognized by local DNS server.
Port number is missing or wrong in JDBC URL.
DB server is down.
DB server doesn't accept TCP/IP connections.
DB server has run out of connections.
Something in between Java and DB is blocking connections, e.g. a firewall or proxy. 



I setup the database, Its not my hosting, as I setup the dedicated servers.
IP is fine, as its connecting and working, its direct IP so no worry about the hostname, DB server is 100% up, DB server is accepting TCP connections, The firewall is setup to allow connections from the correct server.

Data is being populated, so its working and setup.
