### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#280]
No issue here just some questions.

1) What gamemode should be in the server settings - survival or adventure. or does it matter because it automatically sets when the game starts?

2) Should hunger be turned on in the game? I saw in the video that the developer gave apples as a class perk.

 Regarding this:
✰ Explosive Bow that shoots Explosive Arrows that explode when the hit the surface. This can be used to procedurally damage the arena. Accessible via "/ma items".

✰ Hell-fire! Right clicking with a fireball in your hand will launch it. Just like the fire-ball from a Ghast, the hell-fire damages the ground when it hits.

3) My arrows don't explode, it seems like a regular bow. Do I change a server setting? Or do I need to enable it?

4) About the fireballs feature, how does one actually get the fireballs since they aren't in items?

Thanks!

**Comment by Equity7** [comment]
And I also had the issue where players couldn't see the class kits when they joined but that was solved when I gave them the permission corearena.class.*

**Comment by Ekute-hub** [comment]
hi, 1) it's automatic  
2) hunger it's on by default but you can modify your gamerules in the world i think
3) You need explosive bow and throw Explosive Arrow (only)
4) you can for example create a upgrade for buy firball in the arena or make a class start with it
5) You can put corearena.class.* but if you want add class one by one try corearena.class.[Name of class]
