### ISSUE TITLE
Question about using rewards

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#281]
I just want to be sure I am doing this right.  If players use /ma rewards when they aren't in game, the item they are buying goes to their hotbar but disappears with the rest of their inventory when they join the lobby.  If they buy the reward in the lobby while waiting, it goes to the hotbar but when the game starts, it disappears. So the only way to buy a reward and keep it, is in-game and by then you are dead.
I am probably missing something?

**Comment by JavaFactoryDev** [comment]
Hi Equirty7,

Thank you for using CoreArena & asking this question here.

As far as I know, this is normal.
However, you could change your server to a single game-server to fix it. You can find out more about it [here](https://github.com/kangarko/CoreArena/wiki).

I will contact you when I've found any news on this.

Regards,
- Leonhard from MineAcademy
