### ISSUE TITLE
1.15.2: When i kill a mobs...

### ISSUE THREAD

**Issue by Ekute-hub** [kangarko/CoreArena#282]
Hi, sorry for my ugly english
1) When a kill a boss he dosen't drop CoreArena xp but vanilla drop/xp i have config the Settings.yml modify the gamerules DoMobsLoot but he drop nothing now and i have this in console : https://pastebin.com/RfM917Ec

2) When a players die all they stuff are drop i have try to test to put the option doEntityDrop but he still drop haven't any message on console for this.

Use Spigot 1.15.2 / CoreArena 2.5.5 and i have boss but i try to make only with vanilla mobs. 
CoreArena Folder :
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4232694/CoreArena.zip)

Thanks for read !

**Comment by JavaFactoryDev** [comment]
Hey Ekute-hub,

thank you for using Boss & reporting this issue.
I will have a look soon.
Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Thank you for reporting this issue,

We have fixed it in on the latest release.

Regards,
- Leonhard from MineAcademy
