### ISSUE TITLE
Arena still auto ends

### ISSUE THREAD

**Issue by MagicPenguin720** [kangarko/CoreArena#283]
I am running version 2.5.5 of CoreArena. When I do /ma join (arena name) I get put in the lobby and I wait the time that it says. Once I get taken out of the lobby the game teleport's me back to spawn and says game over. I will attach a google drive link in another comment. In that link will contain my updated server files.

**Comment by MagicPenguin720** [comment]
https://drive.google.com/open?id=15YXHyroz0YltJ6Zqtpkhb5XKJNrHhZbX

**Comment by Ekute-hub** [comment]
Do you have config the number max and mini for play ? by default it's 2 Mini and 8 Max so change this in each arena config line 42

**Comment by JavaFactoryDev** [comment]
Hey MagicPenguin720,

Thank you for reporting this issue again,
however, did Eketu-hub's idea fix it?

Regards,
- Leonhard from MineAcademy

**Comment by MagicPenguin720** [comment]
It works! Wow that was an easy fix! Thanks Ekute-hub for the help! Also thank you JavaFactoryDev for helping me these past 2 weeks with this problem!
