### ISSUE TITLE
Mob Arena Not Starting 

### ISSUE THREAD

**Issue by TheMysticalPoe** [kangarko/CoreArena#285]
Hey, whenever I start my game on core arena it lags the whole server a bunch for like 10 seconds and then it starts and when we exit the lobby and go into the arena, all I see is the mobs spawned but they are like just still there and dont move and it lags once more and you die in 5 seconds. The server has 10 GB and is only using 3 GB.

**Comment by JavaFactoryDev** [comment]
Hey TheMysticalPoe,

Thank you for using CoreArena & Reporting this issue here.
You can fix this using FastAsyncWorldEdit #275 

P.S.
For reporting issues please follow: 

Regards,
- Leonhard from MineAcademy
