### ISSUE TITLE
Spigot 1.15.2 - CoreArena Mobs wont spawn

### ISSUE THREAD

**Issue by Answerings** [kangarko/CoreArena#286]
CoreArena 2.5.5
Hi, whenever I join the lobby sequence goes fine, but when it starts it just ends completely. It is saying no mobs are spawning. Here is my error file.

Here is my error,
https://pastebin.com/T7VDfPwj

**Comment by TheMysticalPoe** [comment]
It has been four days and I have this problem too.

**Comment by JavaFactoryDev** [comment]
Please follow #275

**Comment by Answerings** [comment]
> Please follow #275
Here is the plugin folder, 



[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4271304/CoreArena.zip)

**Comment by JavaFactoryDev** [comment]
Hi Answerings,

We hope to fix this issue in the next release.

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Please update to CoreArena 2.5.6
