### ISSUE TITLE
1.15.2 - Arena won't start (ClassNotFoundException)

### ISSUE THREAD

**Issue by hvrry** [kangarko/CoreArena#288]
CoreArena will not start. Mob Spawners have eggs from the Boss plugin.

**Versions:**
CoreArena version 2.5.5
Author: kangarko

GameAPI version 3.1.2
Author: kangarko

Boss version 3.6.8
Author: kangarko

01.03 14:35:25 [Server] INFO This server is running Paper version git-Paper-122 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
01.03 14:35:25 [Server] INFO Checking version, please wait...
01.03 14:35:26 [Server] INFO Previous version: git-Paper-51 (MC: 1.15.1)
01.03 14:35:26 [Server] INFO You are running the latest version

**Error**

Console: https://hastebin.com/vasesikise.sql
error log: https://hastebin.com/pubonudati.cpp

**Comment by JavaFactoryDev** [comment]
Already known,  will be fixed until the next release
