### ISSUE TITLE
Mobs drop & nugget issues 

### ISSUE THREAD

**Issue by MagicPenguin720** [kangarko/CoreArena#289]
I have CoreArena 2.5.5. Mob drops are disabled for all arena's but mobs keep dropping items. Every time a player finishes an arena there only rewarded with 1 nugget.

**Comment by JavaFactoryDev** [comment]
Please follow #275

**Comment by MagicPenguin720** [comment]
Here's my plugins folder and also i'm running minecraft 1.15.2 
https://drive.google.com/open?id=1zKakhso0sSm_-ucdxLekhU9By_JM9yq_

**Comment by MagicPenguin720** [comment]
Here's an updated li

**Comment by MagicPenguin720** [comment]
You alive? or did you get covid 19?
