### ISSUE TITLE
BossAPI error

### ISSUE THREAD

**Issue by mikedoor** [kangarko/CoreArena#291]
Hi there
If I get the spawn eggs from the Boss plugin in the Spawner pack, the error message comes up during testing.
Server runs on 1.15.1 Spigot.

Everything works without.

[error.log](https://github.com/kangarko/CoreArena/files/4284224/error.log)

**Comment by JavaFactoryDev** [comment]
Hey mikedoor,

this issue is already known and will be fixed until the next release.

Regards,
- Leonhard from MineAcademy
