### ISSUE TITLE
MythicMobs problem

### ISSUE THREAD

**Issue by SskyWorms** [kangarko/CoreArena#292]
I have issue when i put MythicMobs egg into CoreArena Spawner
Error log
https://pastebin.com/KJTNUjuV
Error.log
https://pastebin.com/AhBkjFUa

**Comment by SskyWorms** [comment]
https://pastebin.com/Y1rvy9v6
Here is my MythicMobs config

**Comment by JavaFactoryDev** [comment]
Please follow #275

**Comment by SskyWorms** [comment]
ok
