### ISSUE TITLE
Error loading configuration in settings.yml!

### ISSUE THREAD

**Issue by mikedoor** [kangarko/CoreArena#294]
Hi there

Sorry that I have to report again today. Unfortunately there was an error loading the plugin. No error log was written. I have now attached an extract from the server log.

[latest.log](https://github.com/kangarko/CoreArena/files/4289136/latest.log)

Mfg Mikedoor

**Comment by JavaFactoryDev** [comment]
Hey mikedoor,

We have already fixed this issue in the latest release:)

Regards,
- Leonhard from MineAcademy
