### ISSUE TITLE
1.12.2: Placeholder for PlaceholderAPI not work

### ISSUE THREAD

**Issue by SskyWorms** [kangarko/CoreArena#295]
So, i try parse all placeholder variables in https://github.com/kangarko/CoreArena/wiki/PlaceholderAPI
but all of that not work in my server 
my PlaceholderAPI is 2.10.4
my CoreArena is 2.5.9
This is image
![image](https://user-images.githubusercontent.com/54969382/76144880-022ce600-60b7-11ea-8a6c-fe2ea454058a.png)

**Comment by JavaFactoryDev** [comment]
HI SskyWorms,

we will have a look soon:)

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Can you please send us your corearena.zip & the output of the startup when you set the debug-section in the config to Debug: ['*'].

**Comment by SskyWorms** [comment]
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4332207/CoreArena.zip)

**Comment by SskyWorms** [comment]
[latest.log](https://github.com/kangarko/CoreArena/files/4332209/latest.log)

**Comment by lackoSK** [comment]
Hi there, as far I know placeholderapi takes %%placeholder%% not {} or %

**Comment by SskyWorms** [comment]
> Hi there, as far I know placeholderapi takes %%placeholder%% not {} or %

Not work /papi parse me %%corearena_nuggets%% return to %%corearena_nuggets%%

**Comment by JavaFactoryDev** [comment]
Can you tell me whether this is fixed with the latest version, please

**Comment by JavaFactoryDev** [comment]
Fixed

**Comment by SskyWorms** [comment]
still not work

**Comment by JavaFactoryDev** [comment]
Yeah, this is caused by changes in the PlaceholderAPI.
We will fix it.

**Comment by kangarko** [comment]
@JavaFactoryDev is this fixed?

**Comment by JavaFactoryDev** [comment]
Works fine on the latest version.
