### ISSUE TITLE
NBT Tags

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#296]
Might it be possible to add the ability to use NBT tags in the "commands that are run automatically" section?

**Comment by JavaFactoryDev** [comment]
Hey Equity7,
thank you for asking this question here.

Can you please further clarify what you mean by "NBT Tags" and how you wish us to include them?

Regards,
- Leonhard from MineAcademy

**Comment by Equity7** [comment]
I wonder if you can just tell me if this is already possible and I might just be configuring things wrong.

**Comment by Equity7** [comment]
Can you give me the status of my issue since I put it in a month ago?

**Comment by JavaFactoryDev** [comment]
I am sorry for not responding here.
Of course this is possible.

If you have any issues please reopen this ticket.

Regards,
- Leonhard from MineAcademy

**Comment by Equity7** [comment]
Well how exactly do I do it. I enter it  to the arena's .yml file as a console command but it doesn't work.

**Comment by kangarko** [comment]
Cannot you just run the command having the nbt tags right now? What happens? You have to surround the whole command with "" or '' to oppose the brackets used in:

```
Commands:
  - "/summon horse 37 20 66 {Tame:1, SaddleItem:{id:'saddle',Count:1}}"
```

```
Commands:
  - '/summon horse 37 20 66 {Tame:1, SaddleItem:{id:"saddle",Count:1}}'

```

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by Equity7** [comment]
Do you mean put that in the cfg and reload/restart?

**Comment by Equity7** [comment]
Thank you that fixed it!
