### ISSUE TITLE
Class permissions don't work

### ISSUE THREAD

**Issue by MrSuricate2** [kangarko/CoreArena#297]
I added to my player the permission "corearena.class.soldat4" so that it is enough to tier 4 of the "soldat" class but the player remains at tier 1.

[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4334579/CoreArena.zip)

**Comment by JavaFactoryDev** [comment]
The permissions work pretty fine.

Please read the wiki for the  futher information
