### ISSUE TITLE
Mobs don't show up

### ISSUE THREAD

**Issue by GLB-114514** [kangarko/CoreArena#298]
Every time the arena starts
Mobs don't show up (until i die once)
But they can still attack
Including dynamic effects, there is no flight process, only blocks are placed
(When I closed the arena destruction, these problems were solved)
what should I do?
paperspigot 1.12.2

**Comment by JavaFactoryDev** [comment]
Please follow #275

**Comment by JavaFactoryDev** [comment]
User is not responding - Closing
