### ISSUE TITLE
NBT Tags #296 issue was closed without resolution?

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#301]
I can't find a way to reopen it. But my issue was closed after a month and not answered. Again, how can I put the following in an arena .yml file for the console to execute it on start? I have tried many times and it doesn't seem to work.
/summon horse 37 20 66 {Tame:1, SaddleItem:{id:saddle,Count:1}}

**Comment by kangarko** [comment]
I apology, this is our fault that you did not get the support. I have replied over your old commit.
