### ISSUE TITLE
When using, Players_End: 1 - for a pvp arena - If last two players die at the same time the arena breaks.

### ISSUE THREAD

**Issue by P-paj** [kangarko/CoreArena#302]
As title says - I wanted a pvp and pve arena, and it seemed the Players_End setting was the perfect way to accomplish that, so there can be a last player "winner".

But if the last two players die at the same time (im talking same tick possibly, or just a tick or two apart) The player who died second stays "stuck" in the arena (even if they were teleported out properly) - The arena stays running, and broken, despite it reaching its time limit, no one can join without doing an /arena reload

When doing the /arena reload - the player who died 2nd will have their inventory reverted to what it was before they joined the arena, as if they were still in it the entire time.

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
So sorry for the delay - I didnt get notified: Please follow #275

**Comment by JavaFactoryDev** [comment]
Will be reopened on reply
