### ISSUE TITLE
AdvancedSpawners Support

### ISSUE THREAD

**Issue by kacperleague9** [kangarko/CoreArena#306]
GC added egg system recently. I would love to see custom pets from As in corearena!

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
