### ISSUE TITLE
Corearena error

### ISSUE THREAD

**Issue by imachunt** [kangarko/CoreArena#309]
Hi guys,

I'm having two issues arise of recent, one is passing events during a match in Corearena and the second is a Power Sign issue it then disappears with air. I see that its possibly and issue with W.G and Mythicmobs, but any help would be greatly appreciated.

Here is the link for the error codes regarding events [Event Pull](https://pastebin.com/2tzjD3hk)
Here is the error log file from Corearena error.file  [Error Power Sign](https://pastebin.com/dZqa2KW4)

**Comment by JavaFactoryDev** [comment]
Please follow #275
