### ISSUE TITLE
Suggestion: Minimum amount of players required for arena to start

### ISSUE THREAD

**Issue by MatheweB** [kangarko/CoreArena#31]
Could you add a feature that only starts the countdown timer for the arena once a specified amount of people have joined the arena?

Thanks!

**Comment by kangarko** [comment]
Thank you, I assume the lobby period should be indefinite or with a timer in which players wait for sufficient players to join.

Either way, I have written it down to the road-map. I cannot give you an ETA now, in the exams month however.
