### ISSUE TITLE
Mmocore Plugin

### ISSUE THREAD

**Issue by 7SINS7** [kangarko/CoreArena#310]
Seems when you use mmocore and your arena plugin, when you go in the arena and come out in the world it double stacks your health, and it will keep doing so until you log. Please can we get a fix for this?

**Comment by JavaFactoryDev** [comment]
Hey 7SINS7 ,

Reporting this issue here.

Have you tested it without mmocore / was it working probably then?



Regards
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
User doesn't respond.
