### ISSUE TITLE
Minecraft Version: 1.15.2 xp bonus for the next phase

### ISSUE THREAD

**Issue by Seneclor** [kangarko/CoreArena#312]
My server is 1.15.2 and plugin is 2.6.5

I'm having a problem with the next phase bonus.
It activates randomly.
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4752352/CoreArena.zip)

**Comment by JavaFactoryDev** [comment]
Hi Seneclor, 
thanks for reporting this issue here, we will have a look today.

Regards
Leonhard from MineAcademy

**Comment by Seneclor** [comment]
5 days to fix a minor bug?
if it's not fixed today, I'm asking for a refund.

**Comment by JavaFactoryDev** [comment]
Fixed
