### ISSUE TITLE
1.15.2: No Monsters Spawning During Play

### ISSUE THREAD

**Issue by ljdavis501** [kangarko/CoreArena#313]
My desired situation is I want the spawners to spawn during play. My current situation is it is not spawning at all. Before reporting this issue I went through my arena and replaced all the spawners. What I am doing wrong?.  There is no information about this in the WIKI.

[NoMobSpawningIssue_CoreArena.zip](https://github.com/kangarko/CoreArena/files/4753434/NoMobSpawningIssue_CoreArena.zip)

Thank you.

**Comment by JavaFactoryDev** [comment]
HI ljdavis501,

CoreArena has nothing todo with spawning monsters.
Also spawning is prohibited in arenas.

Regards,
Leonhard from MineAcademy
