### ISSUE TITLE
Paper 1.15.2 (Build #345): EXP is only awarded every 2 phases (starting from the 3rd phase)

### ISSUE THREAD

**Issue by NightFuryStrike** [kangarko/CoreArena#314]
In all arenas, EXP is not awarded on every phase like it's supposed to. Instead, it starts giving EXP on the third phase and then every second phase after that. (Phase 3, 5, 7, 9, 11, etc.)

Expected Behaviour:
EXP should be awarded for each phase, not every 2 phases.

Recording showing the issue, watch the chat: (Can be streamed, no download needed)
https://1drv.ms/v/s!AknzfCjeCluIqbB8QzCH6PyAXGBrqQ?e=wnSQS7

**Comment by JavaFactoryDev** [comment]
Duplicate #312
