### ISSUE TITLE
Pressure Plates/Redstoning Issues

### ISSUE THREAD

**Issue by Thiborr** [kangarko/CoreArena#315]
I am trying to setup an arena with dispenser traps using arrows, but I am unable to activate pressure plates or tripwire hooks inside of the arena area.  The dispenser also does not fire arrows; it will make the particle effect, but the arrow itself will disappear immediately.  The dispenser is able to drop items, it is just any kind of projectile shot out of the dispenser that does not work.  Is there a way to turn either of these on inside of the arena?

The server is version 1.15.2 and I have attached the plugin folder below.

Thank you

[CoreArena.zip](https://github.com/kangarko/CoreArena/files/4770961/CoreArena.zip)

**Comment by JavaFactoryDev** [comment]
HI Thiborr,

thank you for asking this question here.
In the latest version of CoreArena things like TripWires should work.

Disabling some of the restrictions for arenas is not (yet) supported.

Regards
Leonhard from MineAcademy

**Comment by Thiborr** [comment]
How would I go about enabling the tripwires and pressure plates?  Currently they are not working while inside of the dungeon and I was unable to find anything that would effect it in the configuration.

Thank you
Thiborr

**Comment by Thiborr** [comment]
Apologies, I now see it in the update log and it seems I missed a few updates without realizing it.

Thank you for your time!

**Comment by JavaFactoryDev** [comment]
Np! You're welcome
