### ISSUE TITLE
Minecraft 1.15.2: Fail - Invalid Phase and Info fail

### ISSUE THREAD

**Issue by ljdavis501** [kangarko/CoreArena#316]
Hello,
I am trying to work through on figuring out why the plugin works and then fails.  Here is a sample of the Console Report:

12.06 23:15:54 [Server] INFO Iterating through slot: 6 Pillager
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-905, 64, -823]
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-905, 64, -821]
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-906, 64, -823]
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-905, 64, -821]
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-907, 64, -821]
12.06 23:15:54 [Server] INFO FAIL spawning PILLAGER at DarduraSheva_City [-906, 64, -823]
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 7 phase, 4 Witch}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 3 phase, 4 Cave_spider}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 3 phase, 75% chance, 5 Wolf}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 7 phase, 4 Wither_skeleton}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 10 phase, 15% chance, 4 Wither_skeleton}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 3 phase, 14 Skeleton}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{on 4 phase, 10 Zombie}
12.06 23:15:54 [Server] INFO FAIL - invalid phase
12.06 23:15:54 [Server] INFO 8 ::: Activating Spawner{from 1 phase, 8 Skeleton}
12.06 23:15:54 [Server] INFO Iterating through slot: 8 Skeleton
12.06 23:15:54 [Server] INFO SUCCESS spawning SKELETON at DarduraSheva_City [-960, 64, -804]
12.06 23:15:54 [Server] INFO SUCCESS spawning SKELETON at DarduraSheva_City [-957, 64, -807]
12.06 23:15:54 [Server] INFO SUCCESS spawning SKELETON at DarduraSheva_City [-957, 64, -806]
12.06 23:15:54 [Server] INFO SUCCESS spawning SKELETON at DarduraSheva_City [-959, 64, -807]

[Fail_Invalid_phase_and_InfoFail_CoreArena.zip](https://github.com/kangarko/CoreArena/files/4774179/Fail_Invalid_phase_and_InfoFail_CoreArena.zip)

Please let me know if you need more information.
I have listed the error also in the Discord Channel: CoreArena

**Comment by JavaFactoryDev** [comment]
HI ljdavis501,

thank you for asking these questions here.

First of all: "Invalid phase" means that the spawner is configured to not work on this phase.

Monsters not spawning is usually caused by plugins like WorldGuard (protected areas, etc) and its hard to replicate for us.

We would recommend you to test it on a server with only CoreArena and its dependencies enabled, and then start to re-enable all the plugins you need.

Regards,
Leonhard from MineAcademy

**Comment by ljdavis501** [comment]
Leonhard,
I see. What exactly is it in Worldguard that may be cause this.  I have not yet set any regions with world guard.  Does that Plugin Automatically apply region protections?

**Comment by JavaFactoryDev** [comment]
Maybe flags in the default-region can be an issue.
Is worldguard the confirmed cause?

**Comment by JavaFactoryDev** [comment]
Please respond.
