### ISSUE TITLE
1.15.2:Error Log

### ISSUE THREAD

**Issue by SskyWorms** [kangarko/CoreArena#319]
https://paste.helpch.at/rupebogisi.md
I got this error

**Comment by SskyWorms** [comment]
Also ping me on Discord if you answear ( SskyWorms#1716 )

**Comment by kangarko** [comment]
Thanks, I changed something and I believe it has fixed the issue. Also ensure to run on latest ProtocolLib: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by kangarko** [comment]
@SskyWorms sorry, I am not available on Discord
