### ISSUE TITLE
CoreArena 1.4.8 encountered a NullPointerException!

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#32]
To do with MySQL, full log.
https://pastebin.com/4kWaeiJt

**Comment by kangarko** [comment]
Hello,

it appears that you have problems with connection to the MySQL database itself - this is not CoreArena's fault. I can see also other plugins complaining about it, like LuckPerms:

`[com.zaxxer.hikari.pool.PoolBase] luckperms - Failed to validate connection com.mysql.jdbc.JDBC4Connection@ece8ea0 (No operations allowed after connection closed.)`

Please contact your server host.

**Comment by FrozenBeard** [comment]
I KNEW you would reply with that and not take responsibility. 
As with #29 and and #28 you are not using the JDBC4
I't connects just fine, as you can see when the plugin first boots up, its entirely fine until the server is idle for a bit and then you do not re-connect to the database when the conenction times out
Like I have already sent you https://www.reddit.com/r/admincraft/comments/7bdw64/can_someone_please_look_at_my_mariadbmysql_config/dphbh4j/
Read that reply.

> 
Is just due to you not using a DB Connection in over x milliseconds, and that time is past the 'wait_timeout' configured so mysql automatically closes the session thinking its inactive.

"contact your host" is not a valid answer for an issue with the programing logic. As I have stated in previous tickets, I run my own servers, and there are no restrictions on the database. Other plugins also use this exact same MySQL connection too.

**Comment by kangarko** [comment]
If you knew then you could save us time and give me that information or explanation beforehand.

There is no specification of the database driver in the code (here is the full class: https://pastebin.com/mGwyzaPE), and, if the connection is closed, we try to re-open it before failing (see line 99).

The full configuration of how we connect to the database is at the following line in settings.yml:

  Connector_Advanced: "jdbc:mysql://{host}:{port}/{database}?autoReconnect=true"

As you can see from there as well, the autoReconect flag is enabled, the jdbc driver is in use. You can change it to whatever you prefer or completely write a new connection statement.

Thus I am of a strong believe that something in your MySQL database is causing this to happen. I don't have sufficient competence in databases, but for this year I only had two cases of this happening (the first was solved by the user).
