### ISSUE TITLE
1.16.1: WorldEdit/Initial Snapshot recovery Error

### ISSUE THREAD

**Issue by benevolent2012** [kangarko/CoreArena#321]
Hello, it seems every time I enter the arena, the server lags behind and leaves this trail of errors on the console.
I am using WorldEdit along with AsyncWorldEdit, which seems to be causing the issue. Is there anything that can be done on CoreArena's side to optimize/reduce the arena's reload time?

https://pastebin.com/eR7an3nL

**Comment by jiajunmao** [comment]
Issue has been resolved. Duplicate installation of WorldEdit and FastAsyncWorldEdit causes is the culprit.
