### ISSUE TITLE
ScoreBoard Setup Help and can I use TNT in arena snapshots?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#324]
Hey, sorry to bombard you with questions but I figured I would make this as a question on GitHub in case others have the same question. I have been setting up snapshots and collateral damage with our arenas and I was hoping to use TNT to blow up parts of the map but CoreArena prevents TNT Damage from happening inside arenas. I have confirmed that it is not WorldGaurd causing the issue. Is it possible to turn this "anti-TNT" feature off? 
Also one other question, do you have any advice on how to setup Scoreboards with CoreArena? I am not very familiar with scoreboards but I would love to have a scoreboard on players screens telling them how many lives they have and how many lives there team mates have / HP of there team mates have and possibly other custom placeholders. Whats the best way to make a scoreboard show up when players are in an Arena? Would this be possible with "on game end" and "on game start" commands? I'm really unsure. I appreciate your replies.

Thanks!

**Comment by kangarko** [comment]
You can light up a TNT and it will explode in CoreArena, that is actually an inbuilt feature.

Scoreboards are not yet implemented, thanks for your suggestion!

**Comment by LeehamElectronics** [comment]
Oh okay, what I mean is, when I am editing an arena, I would like to use TNT to explode parts of the map so I can save a snapshot of the damaged arena for the procedural damage feature. Using TNT is much easier than breaking blocks by hand. Would it be possible to allow TNT explosions to damage arenas while in /ma edit mode?
Thanks

**Comment by NightFuryStrike** [comment]
I would try temporarily moving the arena borders, using the TNT and then putting the borders back exactly where they were, then saving the damaged snapshot

**Comment by LeehamElectronics** [comment]
> I would try temporarily moving the arena borders, using the TNT and then putting the borders back exactly where they were, then saving the damaged snapshot

Yeh great suggestion that's what we started doing.
Thanks!
