### ISSUE TITLE
Arrow Explosion hurt players per arena settings

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#325]
Hi, would it be possible to make arrow explosions only hurt players for certain arenas? This would be really great for my server and I'm guessing wouldn't be to hard to implement. 
Thanks

**Comment by kangarko** [comment]
Just to clarify you want the option to disable player damage when the explosive bow's arrow lands and explodes? Meaning it would still explode and ruin the map but without killing players?

**Comment by LeehamElectronics** [comment]
> Just to clarify you want the option to disable player damage when the explosive bow's arrow lands and explodes? Meaning it would still explode and ruin the map but without killing players?

Yes exactly, I would like the arrows to only "harm players" on certain arenas.
Thanks so much!

**Comment by kangarko** [comment]
Cool, done. Next release will bring the "Explosive_Arrows_Damage_Players" option you can just put into your arena yml file and set to false to prevent arrow player dmg.
