### ISSUE TITLE
CoreArena Rewards does not do what I thought it could.

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#326]
So I was hoping to have a shop that allows you to use nuggets to buy items such as explosive arrows and building blocks to use inside an Arena. I use the upgrade classes for upgrades at the moment but it would be nice to allow players to buy specific items that are given to them on the next Arena they join.

For example, a players open the rewards and purchases some Explosive arrows with nuggets, then the next Arena they join they will be given those items, and if they don't use all of them the remainder will be given to them on the next arena and so on. Or if that is to hard to do, could the player purchase items in the Arena waiting lobby which is then carried on into the game? Either one would work but the way the rewards is at the moment is mostly useless for me since I only use classes and not survival items. 

Another option, I could make an NPC inside the arena that runs a command as OP using citizens that takes nuggets from the player and gives them an item in return. I would love to do this however there is no command for "if {player} has nuggets_x take nuggets_y and give item_name" if you know what I mean.

Thanks!

**Comment by kangarko** [comment]
Awesome, just to clarify :

1. Player in the lobby can use /rewards to purchase items
2. Those items are only given in the arena and removed after the arena play together with the player's class

Yeah that is possible as a future improvement ;)

**Comment by LeehamElectronics** [comment]
> Awesome, just to clarify :
> 
> 
> 
> 1. Player in the lobby can use /rewards to purchase items
> 
> 2. Those items are only given in the arena and removed after the arena play together with the player's class
> 
> 
> 
> Yeah that is possible as a future improvement ;)

Yes, perhaps a better approach would be with a different command, such as "/arena shop" which only runs once a player has joined an arena. When they run the command a GUI appears with options to buy "arena items" that help them play in an arena. How difficult do you think that would be to add? The most valuable thing about this is that it would let players buy as many explosive arrows as they want with their nuggets, which I think would improve the usefulness of the explosive bow.

Thanks Matej!

**Comment by kangarko** [comment]
Nice suggestion, thanks. Right now my plate is blowing up so may take weeks or a few months to get added. I will be rewriting ChatControl and CoreArena.

**Comment by LeehamElectronics** [comment]
I am going to close this because I have mostly fixed the issue myself by using ShopGUI+ plugins that I run while CoreArena is running so players can use their money to buy items mid game, however the only thing left to fix is adding a Vault hook to CoreArena which I mentioned in a different issue so theres no point keeping this one open.

If anyone wants to know how to make custom shops and GUIs for players to use in CoreArena, use the ShopGUI+ plugin from Spigot and the UltraCustomizer plugin from Spigot:
https://www.spigotmc.org/resources/ultra-customizer.49330/

Thanks, I hope to see a proper Vault hook added to CoreArena with the option to replace the nugget system soon.
