### ISSUE TITLE
Procedual damage / gravity only applies to Explosive Bows?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#327]
I got Procedural Damage and Gravity working with CoreArena which I am very happy with, but the "gravity" and physics only apply to explosions from the Explosive Bow. Is it possible to make it work with other explosions such as creepers and TNT?

Thanks

**Comment by kangarko** [comment]
Thanks, leaving open for future consideration

**Comment by LeehamElectronics** [comment]
How difficult would this be to implement? Gravity already works fine with the 'explosive bow', could we just make all explosions call the same method that explosive bows do, by checking the gravitational range?

Thanks!

**Comment by kangarko** [comment]
Done!
