### ISSUE TITLE
AsyncWorldEdit

### ISSUE THREAD

**Issue by benevolent2012** [kangarko/CoreArena#329]
Yes, CA works with AWE and WE.  However, like you mentioned, when joining the arena, corearena causes a thread deadlock, so the server thread literally just freezes, along with the massive TPS drop, which makes it impractical for any server to use this combination of plugins (CA+WE+AWE).

Using FAWE works fine for initial snapshot recovery, except there's way too many little bugs with FAWE, I would much prefer to use AWE if possible.

The thread deadlock and the massive global tps drop is a huge issue with CA. Since I don't have the source code, I can't really look into exactly how CA deals with WE either... so we need @kangarko 's help!

_Originally posted by @benevolent2012 in https://github.com/kangarko/CoreArena/issues/248#issuecomment-674551391_

**Comment by LeehamElectronics** [comment]
Agreed!!

**Comment by kangarko** [comment]
Please do not double post

https://github.com/kangarko/CoreArena/issues/248
