### ISSUE TITLE
Instant Food / Potions / Soup

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#33]
Can you add a configurable thing per arena that allows users to instantly eat foods and potions by right clicking them (Configurable to the max so a variable for food and potion or even make it so the user can make it determine which foods/potions that can be instant consumed/used independently).

**Comment by kangarko** [comment]
Sounds like a great suggestion, I may add it after exams!

**Comment by LogGits** [comment]
That's great to hear, are your. When do your exams finish?

**Comment by kangarko** [comment]
I quit college so... actually should be within few weeks now.

**Comment by kangarko** [comment]
I paused college so... actually should be within few weeks now.
