### ISSUE TITLE
Arena rewards

### ISSUE THREAD

**Issue by LegendOfPeanuts** [kangarko/CoreArena#331]
in #243 , arena reward was added. However, I did not receive any rewards after finishing the arena. Is this the plugin's problem or is it my problem configuring the arena?
Here is the arena config:
https://pastebin.com/f1BzMNkz

**Comment by AngellitoX** [comment]
Hello, do you receive any console error logs when finishing the arena? or any messages or sight about when you're supposed to get the reward item?

This might be an issue on our side, but it's best to check everything up.

Thank you for bringing this up!
Angel from MineAcademy.org

**Comment by LegendOfPeanuts** [comment]
Just checked the console after finishing the arena, no errors, only the GG message

**Comment by kangarko** [comment]
Unfortunately the developer did not implement this at all. He is no longer associated with MineAcademy and us, I will do this myself to the next release.
