### ISSUE TITLE
CoreArena MMOItems and Mythic Items Artifact support

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#333]
Hey Matej,
just got a quick question, does Mythic Items  or MMOItems work with CoreArena? I was hoping to place custom Mythic Items into my classes in CoreArena, however I am not sure if I should buy Mythic Items because I don't know if CoreArena will accept those items into its classes. I know CoreArena supports MythicMobs eggs, and since Mythic Items is an add on (artifact) to MythicMobs I'm assuming those custom items will work in classes but I'm not sure.
Here are the links to the plugins:

https://mythicmobs.net/index.php?resources/artifacts-mythic-items-and-enchantments-early-access-25-off.37/

https://www.spigotmc.org/resources/mmoitems-premium.39267/

Thanks Matej, waiting for your reply.

**Comment by kangarko** [comment]
Never tested to be honest. Your best bet is to give it a try. We use Bukkit way of saving ItemStacks so if they use custom tags they should be saved, and then applied normally.

For MythicMobs, we have a custom integration thought.
