### ISSUE TITLE
1.16.2 Paper: Animals/mobs spawn in arenas

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#334]
Paper 1.16.2 just came out and I am now updating. I kept my files from 1.16.1 and deleted gameapi. I checked my region points. Everything from my 1.16.1 ftp transferred perfectly. However, animals and mobs from outside the arenas keep spawning in the arenas and I can't figure out why. This didn't happen in the 1.16.1 version of Paper. I have the same plugins as I did before the update.  I checked my server paper.yml, server properties, etc and even my level.dat file in the world.  Can you give me guidance as to how I might fix this? Thanks.

**Comment by LeehamElectronics** [comment]
Please upload your latest.log and any other files that may help us diagnose the issue

**Comment by LeehamElectronics** [comment]
Also why do you have natural mob spawning enabled in that world anyway? Are your CoreArena maps in there own seperate world? If so, just set the game rule to "domobspawning false", or you can use world guard to prevent natural mob spawning...

**Comment by Equity7** [comment]
I assumed turning off that gamerule would stop arena mobs from spawning. Anyway I see what the problem was. The mob spawnpoints moving from Paper 1.16.1 to Paper 1.16.2 worked perfectly. However something went awry and many of the eggs that worked before are "invalid types" so sheep spawn instead. I redid it so it seems to work now. Thanks!
