### ISSUE TITLE
Arena Rewards added, can they work with nuggets?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#336]
I noticed you added arena rewards in version 2.7.9

Would it be possible to go the next step further and add a "/ca shop" so players can buy rewards such as explosive arrows by purchasing them with nuggets while they are in an arena? If you don't have time to make a /ca shop GUI that's okay, at least would you be able to make a "/ca purchase explosive bow/arrow" that way I can make my own GUI for players to buy explosive arrows with their nuggets? It shouldn't take too much time to do, all the command has to do is check if the player has enough nuggets for the item like so:
does %player% have {arrow_nuggets_cost}:
    If Yes: Give player {explosive_arrow}
    If Not: message_player: "You don't have enough nuggets!"

Thanks in advanced.

**Comment by kangarko** [comment]
Yes, thank you, I think you suggested something similar so that when I am implementing in-game rewards menu I will definitely add that. No ETA yet, I must finish ChatControl first.
