### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by elijahskingdom** [kangarko/CoreArena#337]
-

**Comment by AngellitoX** [comment]
Hello there! I believe that for your first suggestion, it could work as long as you use a Helmet re-textured that can be placed in the specific slot. Another item might not work for now.

For the Arena modes, it sounds a bit tricky as CoreArena is mainly focused on PvE, but I believe it can be considered for future releases.

Thanks a lot for the suggestions!
Angel from MineAcademy.org

**Comment by elijahskingdom** [comment]
Hello,

Actually when applying custom model data to helmets, and upon wearing it, it doesn't appear on the head as a custom hat, only a helmet. Which is why i have it set to sticks.json. Although it's not that big of a deal considering it can also be worked around by allowing the /hats command in game from my hat plugin, it would still be a nice option though.

For the 2nd suggestion: I wasn't thinking so much as integration for CoreArena, but rather a whole other separate plugin. 

Appreciate the response,
Regards,
Elijah

**Comment by kangarko** [comment]
Thanks for your suggestions! Not working on them now since I am out of workspace, then I'll have to focus on ChatControl 9 but I'll return to it eventually.
