### ISSUE TITLE
MythicMob Eggs not working

### ISSUE THREAD

**Issue by whoshenry** [kangarko/CoreArena#34]
I am putting Mythic Mob eggs into the spawners and it is not saving, the egg just disappears when I place it into the spawner.

Using the latest 1.4.13 CoreArena and MythicMobs 4.3.2

**Comment by kangarko** [comment]
Any errors in console? Do you have Setup.Accept_Unsafe_Monster_Eggs to true in settings.yml ?

**Comment by kangarko** [comment]
Hello,

please set Debug to [setup] in settings.yml and post me the console messages when placing eggs into the spawner menu and then closing the menu.

**Comment by kangarko** [comment]
Hello, this has been resolved. Please let me know if anything happens again.
