### ISSUE TITLE
1.16.1: Enum 'Material' does not contain 'LEAVES'

### ISSUE THREAD

**Issue by realonesc** [kangarko/CoreArena#340]
I can not use the plugin; whenever I create a new arena, I get errors in the log. On restart, the plugin will be disabled on launch until I delete the arena yml file.

Here is the error pastebin.

https://pastebin.com/9r9kTmU0

**Comment by fmohican** [comment]
same issues here.

**Comment by jiajunmao** [comment]
can confirm, same issue

**Comment by christaylor201** [comment]
We've got the same issue, too.

I guess there were some internal changes in version 2.7.10 which no longer support legacy IDs anymore, such as `LEAVES` or `LEAVES_2` used in the default arena configuration?

**Comment by ThaiWRV** [comment]
yup same issue here as well

**Comment by kangarko** [comment]
Thanks, will get fixed asap.
