### ISSUE TITLE
PaperSpigot 1.8.8 | Doens't create Arena Snapshots with Core Arena

### ISSUE THREAD

**Issue by NessunoMC** [kangarko/CoreArena#343]
I created the Arena and selected the region with /ma tools. Using the function to save arena snapshots it doesn't save the snapshots.

**Comment by kangarko** [comment]
Do you have WorldEdit installed? What server version are you running?

**Comment by LeehamElectronics** [comment]
Does it generate more errors or provide any other information in the console? We need more info

**Comment by NessunoMC** [comment]
> Do you have WorldEdit installed? What server version are you running?

Yes, World Edit is version "Bukkit-Official (6.1.3;7a097ca)".
I'm running World Edit on lastest version of PaperSpigot 1.8.8.
Boss is running on 3.8.4.

**Comment by kangarko** [comment]
Update Boss to 3.8.8 and CoreArena to latest and use this worldedit: https://ufile.io/v7o2m5qd

**Comment by NessunoMC** [comment]
> Update Boss to 3.8.8 and CoreArena to latest and use this worldedit: https://ufile.io/v7o2m5qd

It doesn't work.

**Comment by kangarko** [comment]
What do you mean 'does not work'? Any console errors?
