### ISSUE TITLE
Version 1.16.3 Paper: Odd arena error

### ISSUE THREAD

**Issue by Equity7** [kangarko/CoreArena#344]
I have been using the 2 arenas that came with the plugin for many many months with no problem. Now they are screwed up with signs going the wrong way, tree tops on the ground, etc. I have other 1.16.3 servers with no issues like this. It only occurs inside the arena schematics. I am getting an odd error in the console when procedural damage is true. I don't get an error when it is false but the arenas are still screwed up.

14.09 11:42:08 [Server] INFO Loading arenas (2) ..
14.09 11:42:08 [Server] INFO > Loading CSS
14.09 11:42:08 [Server] INFO Update CSS.yml at 'Procedural_Damage' -> 'true'
14.09 11:42:08 [Server] WARN Schematic was made in a newer Minecraft version (2578 > -1). Data may be incompatible.
14.09 11:42:09 [Server] WARN Schematic was made in a newer Minecraft version (2230 > -1). Data may be incompatible.
14.09 11:42:09 [Server] INFO DiscordSRV is up-to-date. (930605a68cca8d2823d67ba4bfb20706b5c90ddf)
14.09 11:42:09 [Server] INFO > Loading Traditional
14.09 11:42:09 [Server] INFO Update Traditional.yml at 'Procedural_Damage' -> 'true'
14.09 11:42:09 [Server] WARN Schematic was made in a newer Minecraft version (2578 > -1). Data may be incompatible.
14.09 11:42:09 [Server] WARN Schematic was made in a newer Minecraft version (2230 > -1). Data may be incompatible.

The schematics are certainly not from a newer version, I am running the newest version. Any idea how this could happen? I desperately don't want to redo the arenas. Also, my snapshots aren't working either.

**Comment by kangarko** [comment]
I apology, but this error is not coded in CoreArena. This is likely coming from WorldEdit, you may want to ask for help on their side. I am going to test it in 1-2 days myself.

**Comment by Equity7** [comment]
Yes you are right. There isn't an official release of W.E. 1.16.3 but the latest dev build solves it. Thanks for the tip!

**Comment by kangarko** [comment]
Thanks!
