### ISSUE TITLE
1.16.1: locking arena's

### ISSUE THREAD

**Issue by 4kets** [kangarko/CoreArena#350]
Hi i want to have some arena to be locked for players so that you need a certain permission to play that arena, is this possible?

**Comment by LeehamElectronics** [comment]
You can do this with permissions nodes or if your using an NPC you can make custom permissions that players need in order for commands to run when clicking an NPC. Can you just use the CoreArena join permission per arena?

**Comment by LeehamElectronics** [comment]
Okay I just checked I am using:
`Perm: corearena.command.join`
Per arena and it does not work, for example using CoreArena.command.join.arena_1 does not do anything, perhaps Matej could add this functionality when he has time?

**Comment by kangarko** [comment]
Yeah sounds like something I can add, thanks.

**Comment by 4kets** [comment]
Allright then i will use that and if in the future the per arena permission is added ill refactor it to that thank you

**Comment by kangarko** [comment]
Still haven't had to chance to add it, but I hopefully should within the next few days.

**Comment by kangarko** [comment]
Added! Next release is up in 1h
