### ISSUE TITLE
1.16.1 - No chest refill

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#351]
Hey there,
I can't make the refill chest work. I have tried both the "on phase" and the [2, 4, 6] metode. None off them works. The chest is filled at arena start, but it won't refill. I get no errors and I have updated to the newest version of CoreArena.
Hope you can help me out.

Sune

**Comment by kangarko** [comment]
Please send me your plugins folder as a ZIP and I will test it out.

**Comment by SuneR-what** [comment]
I don't know if you need all of the plugins, but here you go.

[plugins.zip](https://github.com/kangarko/CoreArena/files/5294324/plugins.zip)

Thanks in advance

**Comment by kangarko** [comment]
Thanks, have you saved the arena initial snapshot with those chests being filled?

**Comment by SuneR-what** [comment]
Yeah, and they are filled up at the start of the arena, that works fine, but the refill never comes...

**Comment by kangarko** [comment]
So sorry for delay, I've put a note and will get back to you in 24h

**Comment by kangarko** [comment]
Hey, I fixed that! Next version of CoreArena will come within 60 minutes.
