### ISSUE TITLE
1.16.1 - A Victory screen?

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#352]
Hey,
Is it possible to make another end screen than the "Game Over"? I would like to make at "Victory!" I you make it to a specified phase (like kill the boss or something). Is that possible? 

Thanks in advance.
Sune

**Comment by kangarko** [comment]
Not possible, sorry.

**Comment by LeehamElectronics** [comment]
Perhaps we could add it to the roadmap for a future release?
