### ISSUE TITLE
Vault hook and disable economy management

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#353]
Using 'nuggets' as the currency is servery limiting, I would like to use my ShopGUI plugins so players can buy the permission nodes to join arenas and so forth, but there is no way to do this with 'nuggets'

Would it be possible to make 'nuggets' use Vault as a link for its currency and disable CoreArena from handling the currency? This would give us soo many more possibilities with our own custom shops which means you don't need to worry about improving the current CoreArena shop because I can do that myself. I know procedural damage is basically unusable for the time being, but having this Vault hook would certainly help in the mean time to make CoreArena much more customizable.

Thanks

**Comment by kangarko** [comment]
Hi,

We have an option to use the Gold item, which, upon right clicking, will convert itself into a Vault-compatible currency. See /arena items 

Matej

**Comment by LeehamElectronics** [comment]
That doesn't really answer my issue, I also want to use the vault currency to purchase core arena classes and items so I really need to completely replace nuggets with vault. Is this possible??
Thanks

**Comment by kangarko** [comment]
Thanks for explaining, I have received and replied to your email. Reopening. I promise you, once ChatControl 9 is stable and cooled down, my second priority will be updating Project Orion (takes 1 day) and then going right into adding this and FAWE to CoreArena.

**Comment by kangarko** [comment]
Of course if you have a reliable developer I can have him sign NDA and access the sources to help us implement it as soon as possible.

**Comment by kangarko** [comment]
Pulled to roadmap, will be done by someone who'll be taking over this project

**Comment by LeehamElectronics** [comment]
Oh nice, whose taking over if you don't mind me asking?
Thx

**Comment by LeehamElectronics** [comment]
oh what! I was not expecting it to go open source, that's crazy.

**Comment by LeehamElectronics** [comment]
I am unable to fork the wiki for CoreArena, using the link https://github.com/kangarko/CoreArena.wiki.git
just returns error 404 page not found. and ofc when forking the entire repo the wiki does not get cloned too, which seems odd.

**Comment by kangarko** [comment]
You can just edit the page directly or not? Ensure you clicked on the invitation link in your email. I am unable to help you with this since I have no idea what's causing it, I simply added you to collaborators.

**Comment by kangarko** [comment]
It says pending invite, click here: https://github.com/kangarko/CoreArena/invitations

**Comment by LeehamElectronics** [comment]
Ah sorry I just saw the email, I will have a look now. Thanks!
