### ISSUE TITLE
1.8.8: What does 1.8 will not render setup blocks due to lacking libraries.

### ISSUE THREAD

**Issue by ethsmith** [kangarko/CoreArena#354]
The title pretty much says it. Want to buy this plugin but it would be for a 1.8.8 server and I am not exactly sure what I stated means

**Comment by LeehamElectronics** [comment]
Where is this written? Can you provide a link to where you read this? I may be able to help if I see this in more context.
Thanks

**Comment by ethsmith** [comment]
On the main plugin page, near the bottom it says this.

**Comment by kangarko** [comment]
It will not render the glowing edges around your region blocks, but you will still see a block changed after you place a spawnpoint. You can still use it on 1.8.8
