### ISSUE TITLE
Procedural damage doesn't work.

### ISSUE THREAD

**Issue by NessunoMC** [kangarko/CoreArena#355]
I am using Paperspigot 1.8.8 #443 with these plugins.

CoreArena - Lastest version on SpigotMC.org
EssentialsX 2.18.1.0
Vault
World Edit 6.1.9.

Plugin doesn't get the Arena's snapshots. Clicking on "Take the initial snapshot" it says "Took the inital snapshot of the arena" but it's still not set.

NO ERRORS IN CONSOLE.

![image](https://user-images.githubusercontent.com/67857828/95337130-d6264d00-08b1-11eb-8651-f140ad3e4a6a.png)

**Comment by kangarko** [comment]
Procedural damage requires Minecraft 1.13 because only WorldEdit 7 is supported.

**Comment by LeehamElectronics** [comment]
Hmm I got procedural damage working on 1.16 fine with the latest version of WorLdEdit, however FAWE is having issues at the moment but everything else was fine
