### ISSUE TITLE
1.16.1: How to stop the plugin giving random class

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#357]
Hey there,
I have made different classes for different arenas. I have placed signs in the lobby so players only can pick the classes I want them to (they dont have the permission to use the class-command).
My problem is, that if a player does not choose a class, he will be given a random class. How can I disable that function? It would rather, that they were kicked at arena start, or something (I think I remember that has happend earliere, but I can not find anything about it in the config files?

Thanks in advance.
Sune

**Comment by kangarko** [comment]
Thanks, I will add that as a new toggle to the next version tonight.

**Comment by LeehamElectronics** [comment]
You could also use world guard to set permissions per region and just set certain class permissions on the regions you would like them to have those classes for.
