### ISSUE TITLE
1.16.3: how to run multiply commands from the console?

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#358]
Hey there,
I'm trying to run a 2-3 commands on a phase, but I cant seem to get the syntax right:

  Phase:
    Player: []
    Console: [effect give @a minecraft:slow_falling 999 100 true]; effect give @a minecraft:slowness 999 1 true]

This is what I have tried out, but it does not work. If I delete the last effect, it works fine.

Can you show me in the right direction?

Thanks in advance
Sune

**Comment by LeehamElectronics** [comment]
Have you tried using a comma to seperate commands?
Like this:
Give mail2002 dirt, give mail2002 water

**Comment by kangarko** [comment]
Hey there, something like that could work:

```
Console:
- /effect give {player} minecraft:slow_falling 999 100 true
- /effect give {player} minecraft:slowness 999 1 true
```
