### ISSUE TITLE
Player Leave Command /tp Not Working

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/CoreArena#36]
First of all trying to setup the Finish arena command..

[20:56:18] [Server thread/INFO]: Arena // GG! The game in Desert has finished!
[20:56:18] [Server thread/INFO]: CONSOLE issued server command: /tp {player} -41 95 -27
[20:56:18] [Server thread/INFO]: Info // Player not found.

They do not work. Placeholders dont seem to work. Also tried other placeholders and they dont work. My players can /back into the arena, I would like to get the finished command working. Also when a player dies before the arena the Finish command is not being send to them. and they are able to /back into the arena and pickup all items. Hope u can get it solved i would like to use the plugin in my server. but like this its not possible

**Comment by kangarko** [comment]
Hey,

I have added a new option in "Arena" section of settings.yml, enable it and it will work.

![a](https://i.imgur.com/cMTlvQo.png)

**Comment by AmazedMender16** [comment]
It still is not teleporting me when the arena finishes.. Even tho it comes into the console as a command......

ALSO: When you die earlier in the arena then it ends you wont get teleported either (No commands shown...)

hope u can get it to work!

**Comment by kangarko** [comment]
Please post me your arena .yml file with the commands.

**Comment by AmazedMender16** [comment]
https://pastebin.com/EAjUYq2v

**Comment by kangarko** [comment]
Hey,

try changing 

`     - "tp {player} -41 95 -27"`

to

`     - "tppos {player} -41 95 -27"`

**Comment by AmazedMender16** [comment]
Already treid it it doesnt apply to people who die in arena before it ends.... + the command is still not teleporting

**Comment by kangarko** [comment]
You're right,

I have added a new section that is effective for EACH TIME a player leaves the arena, check it out:
![a](https://i.imgur.com/dLhp6A8.png)

**Comment by AmazedMender16** [comment]
Looks cool where do i add it?

**Comment by kangarko** [comment]
Hey, yes, the update will be available in 1-2 hours.

**Comment by AmazedMender16** [comment]
Still not working.,...... Its not teleporting tho its executing the command! Could you make a thing like 

Double_teleport: false/true

so when the arena ends you get teleported twice to your last position?

**Comment by kangarko** [comment]
It works for me, what is happening specifically?

![a](https://i.imgur.com/3O6hnRA.png)

You can just repost me your arena .yml file just to be sure ;)

**Comment by AmazedMender16** [comment]
tppos a player is not possible at first when you're running the essentials plugin.

Im seeing the command happening on the console but the teleport is never happening...

https://pastebin.com/f8PEYAuV

You can also contact me via pm on discord would be alot more easy to troubleshoot this.
AmazedMender16#9294

**Comment by kangarko** [comment]
I just tested with plain 'tp', still works flawlessly, both on arena stop and leave:

![a](https://i.imgur.com/22TD219.png)

Yes we can catch up on Discord but I am doing support in waves, meaning I respond to all three support channels to individual questions rather then have long conversations (don't have time nor resources for that).

Please post me your plugin's list just to be sure. Is it possible that any other plugin is interfering? 

What exactly happens after arena finishes, i.e. is the player just moved back to his original location?

**Comment by LogGits** [comment]
@AmazedMender16 couldn't you just use two tppos commands to teleport them to the position twice?

**Comment by AmazedMender16** [comment]
@LogGits If i could i would use it, But its not working :)

**Comment by LogGits** [comment]
Out of curiosity is it saying the game is ended then tping the player or tping the player then saying the game has ended? Also are you specifying a world with tppos (e.g. "/tppos {player} 100 100 100 world")? Could the position your are trying to teleport the player to be deemed "unsafe" by essentials? Are you using essentials or essentialsx? What version are you on? Also screenshots of the event could be helpful to kangarko :)

**Comment by kangarko** [comment]
@AmazedMender16 sorry for not having it fixed before my travel. I will return back 28th, until then you can just move your arena to an event world where players could just use a warp command to get back from wherever they came from.

**Comment by AmazedMender16** [comment]
Commands are being executed but no teleport is happening 
CONSOLE issued server command: /tppos AmazedMender16 -41 95 -27
CONSOLE issued server command: /tppos AmazedMender16 -41 95 -27
Arena // GG! The game in Desert has finished!

**Comment by kangarko** [comment]
@AmazedMender16, I made a simple plugin for you to test out. Please follow instructions in its config.yml and test if it will be working correctly. You can decompile it with Luyten if you are curious.

[ArenaTeleport.zip](https://github.com/kangarko/CoreArena/files/1603760/ArenaTeleport.zip)

**Comment by AmazedMender16** [comment]
That actually seems to work...

**Comment by kangarko** [comment]
Test 1 or test 2 or test 3?

**Comment by AmazedMender16** [comment]
i have it configured like this ATM

https://pastebin.com/uWE8UdBg

And it warps the player to the warp and when ur trying to do /back you get telleported to test 1 location

**Comment by kangarko** [comment]
Okay, good. Just use that plugin for now, and let me know if anything comes up.

**Comment by AmazedMender16** [comment]
Seems like the plugin you created does not work anymore on the latest corearena version :/

**Comment by kangarko** [comment]
Works for me, except for that I get "kangarko moved too quickly" message. You can increase this in spigot.yml's moved-too-quickly-multiplier

If it still does not work, post me config.yml from ArenaTeleport private plugin.
