### ISSUE TITLE
PaperMC 1.16.3: Announcement when someone joins an arena?

### ISSUE THREAD

**Issue by SuneR-what** [kangarko/CoreArena#362]
Hey,
Is it possible on lobby join, to make an world announcement in global chat saying something like: "{player} joined {arena-name}. Go join them!"
I have a small server, so to make ppl know, that other ppl are playing the arenas, an announcement like that, would help alot.

Thanks in advance.
Sune

**Comment by LeehamElectronics** [comment]
Use world guard with the console command on entry flag to make announcements when player enters the arena lobby region. U can also use placeholders at ur server hub to show people that are playing in an arena or waiting for game to start.

**Comment by LeehamElectronics** [comment]
Was that helpful @SuneR-what  ?

**Comment by SuneR-what** [comment]
It help me, to think, that I could use the console command on Lobby join in the corearena plugin. So now there is a world snnouncement on lobby start. So it was actual possible to do, with the plugin itself. 😊

**Comment by LeehamElectronics** [comment]
Oh yeh I forgot about that lol, that should work fine too.

**Comment by LeehamElectronics** [comment]
Im guessing you can close this now?

**Comment by SuneR-what** [comment]
yeah, just to anyone else how wanna do it, my input is:
Commands:
  Start:
    Player: []
    Console: []
  Lobby_Start:
    Player: []
    Console:
    - title @a subtitle {"text":"Someone has join {arena}, come join them"}
    - title @a title {"text":"Arena {arena}","color":"blue"}
