### ISSUE TITLE
Paper 1.16.3: Restrict classes to specific arena's

### ISSUE THREAD

**Issue by Eth4ck1e** [kangarko/CoreArena#363]
I would like to know if it is possible to restrict classes to specific arenas.  If so I cannot figure out how.  Thanks for your assistance.  And thank you for this amazing plugin!

**Comment by Eth4ck1e** [comment]
Also, players have the class perms but cannot use the class sign.  I don't see any perms for signs in the documentation?

**Comment by LeehamElectronics** [comment]
Signs should work if the player has permission, also if you want to setup per arena classes you can do that easily if you have world guard. Simply make a region around your arena and use the set player permission flag, or use NPC's with the -o operator before the command to bypass player permissions that way you can control what NPC's give what class. If you need more detail let me know, pretty much everything is customizable using other plugins like UltraCustomizer and World Guard if you have the know how.

**Comment by Eth4ck1e** [comment]
Awesome, that is helpful!  I found a way to restrict the classes by just using signs and turning off the class menu.  However, is there a way to allow players to join mid-game?  I also added  perms to luckperms for corearena.class.* which fixed the issue I was having for classes.

**Comment by LeehamElectronics** [comment]
No sorry you can not have players join mid game, however you can setup spectating using the method I mentioned here:
https://github.com/kangarko/CoreArena/issues/361

**Comment by Eth4ck1e** [comment]
ok, thanks so much for your help.  I don't need spectating at the moment but we will probably add it for some of our arena's this plugin is amazing.  And so is your support!

**Comment by LeehamElectronics** [comment]
Glad I could help! (btw I don't actually work for mine-academy, I just like to help ppl that's all.)
