### ISSUE TITLE
URGENT: Easy Fix, turn off the arena end sounds or lower its volume!

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#364]
When players leave an arena or game over it plays this sound each time, is it possible to turn it off or lower its volume / pitch or change its sound?
Thanks!

**Comment by kangarko** [comment]
Sure, I made those customizable to the next version:

![a](https://i.imgur.com/5P5XT0w.png)

**Comment by LeehamElectronics** [comment]
Thanks so much!!! Great work Matej
