### ISSUE TITLE
%corearena_player_player_2_health% Needs to function differently 

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#365]
So on my Scoreboard I have "Other Player: %corearena_player_player_2_health%"
This returns player twos health but I would like it to return player 2 from the point of view of the player asking for the place holder, for example,
At the moment, player 1 sees the player 2 health placeholder as the opposite players health, but player 2 just sees his own health because he is player 2 which is not usefull. 

Alternatively, you could add an extra placeholder like %corearena_player_player_2_health_NAME% to return the username, that way I can have my scoreboard as:
%corearena_player_player_1_health_NAME% Health: %corearena_player_player_1_health%
%corearena_player_player_2_health_NAME% Health: %corearena_player_player_2_health%

Which in practise would look like this:
mail2002 Health: 20
mail2001 Health: 11

I think the second option would be pretty easy to implement if you have time.
Thanks Matej!

**EDIT:**
A  %players_alive_ARENA%_ placeholder would also be really handy for score boards to tell players how many players are alive, just return an integer of how many players are still alive in that arena

Also, another easy one to add is **%corearena_ARENA_player_X_lives_left%** and **%corearena_ARENA_player_X_livesTotal%** for returning how many lives a player has.

**Comment by kangarko** [comment]
Hi Leeham!

Unfortunately we'd have to rebuild the list and change its order for each player, draining plugin's performance significantly, to achieve what you've suggested.

But, I went ahead and added these variables:

- {corearena_ARENA_alive} = The amount of players in the arena.
- {corearena_ARENA_lives} = The amount of lives each player has in the arena (if configured).
- {corearena_ARENA_PLAYER_livesleft} = Lives left of the player.
- {corearena_ARENA_player_X_livesleft} = Lives left of the player.

**Comment by LeehamElectronics** [comment]
Thanks @kangarko that should work well, however could you add:

{corearena_ARENA_player_X_NAME}

To return the players username? It should be relatively simple to get the players username and return it since the other placeholders already exist, and it would really complete all of the other placeholders you have already made for us.

Thanks!

**Comment by kangarko** [comment]
Sure, I will add this as well.
