### ISSUE TITLE
Minecraft 1.16.3 - Chat being filled when player upgrades class

### ISSUE THREAD

**Issue by ThaiWRV** [kangarko/CoreArena#366]
![unknown](https://user-images.githubusercontent.com/67396447/97091515-fe2be500-1601-11eb-814e-5f2707663e54.png)

**Comment by LeehamElectronics** [comment]
Are you using the latest version of CoreArena? Also is debug mode on in your settings.yml? I have not had this issue on the latest version. Perhaps use paste-bin to upload your server log and the settings.yml file for your CoreArena settings.
Thanks

**Comment by kangarko** [comment]
Hey, just reviewed the code but such logging is not in there unless you have something in your Debug key in settings.yml. Set that key to "[]".
