### ISSUE TITLE
Next_Phase_Mode: monsters Arena Ends Immediatly

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#369]
When using: `Next_Phase_Mode: monsters` The arena ends immediately after starting.
If I change it to 'timer' it all works just fine.

Here is my arena YML: https://pastebin.com/h60t1yWU
Here is my settings: https://pastebin.com/7gXEQXzA
Here is the error code from console: https://pastebin.com/crTS3RxE
Here is error form error.log: https://pastebin.com/HLMC12Lt

Also what does` aq error` mean? `[21:09:48 INFO]: CoreArena 2.8.0 encountered an aq! Please check your error.log and report this issue with the information in that file.`
I am not sure what an `aq error `is so I am out of ideas...

Thanks in advanced for your help!

**Comment by kangarko** [comment]
Thanks I fixed that!
