### ISSUE TITLE
PaperSpigot Incompatibility

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#37]
It appears that the plugin is incompatible with PaperSpigot. The incompatibility causes issues with saving arena info such as spawner eggs in spawners, classes and rewards not saving at all and registering when complete debug is enabled.

*Tested on latest PaperSpigot and latest Spigot. It works on the latest Spigot and not on the latest PaperSpigot. Can other users please test this to confirm if possible.*

**Comment by kangarko** [comment]
Hello,

please set the Debugger to [setup] and post the output when saving monster eggs.

I am actually testing releases on PaperSpigot 1.12.2 and could not reproduce this bug, but I have another user reporting probably similar problem, I need your debug output.

**Comment by LogGits** [comment]
See discord I sent you a full detailed post :)

**Comment by LogGits** [comment]
Issue fixed :)
