### ISSUE TITLE
EpicSpawners support

### ISSUE THREAD

**Issue by ArnoPompio** [kangarko/CoreArena#370]
**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
It would be useful for peoples using EpicSpawners
**2) What would happen if we won't implement this feature? How's your server being affected?**
I would not be able to put Mob Arenas in the server, otherwise it would break the economy of our spawners
**3) If suggesting something new - Can the old system be modified/improved instead?**
I believe yes

--> With EpicSpawners, you are able to get spawners by killing mobs (like you kill 500, you get a spawner of the mob. It's called /spawnerstats). ES disables the feature when you are farming the mobs with an actual spawner. You can only farm the mobs in the nature. 
With CoreArena, the mobs are still stacked and players can farm easily the spawners in the mob arenas. So It would be super to put an EpicSpawners support that disable the /spawnerstats when we are fighting the mobs.

Thanks

**Comment by kangarko** [comment]
We received complaints regarding EpicSpawners before and for the time being we're not planning to add them.
