### ISSUE TITLE
piglin, brutes, and hoglins immune to zombification

### ISSUE THREAD

**Issue by Eth4ck1e** [kangarko/CoreArena#371]
You can summon piglins with /summon minecraft:piglin_brute ~ ~ ~ {IsImmuneToZombification:1} which prevent's them from zombifying in the overworld.  It would be very helpful if this was something we could enable/disable in the spawn parameters for mob spawners.  There may be an easier solution that I am unaware of, but this would be useful for any server that uses primarily the overworld for their arena/minigames.  Without the ability to prevent them from turning all brutes become normal zombie piglins and are unusable as a mob in the arena.  Hoglins and piglins change as well but the effect is less problematic.  If those mobs were just set to immune by default it would not adversely affect any arena as all the zombie versions have their own eggs.  So that would just ensure the egg you use is the egg you get.

**Comment by kangarko** [comment]
Thanks I will put that to the todo list!
