### ISSUE TITLE
1.16.3: Crepeers, TNT, fireballs, etc. do not destroy blocks or show explosion particles anymore.

### ISSUE THREAD

**Issue by NightFuryStrike** [kangarko/CoreArena#372]
Greetings, there appears to be an issue with the most recent version of CoreArena which is causing explosions to no longer destroy blocks or show explosion particles/sounds in my world anymore. My guess is this was caused by the recent changes where all explosions can damage arenas.

CoreArena v2.8.1
Paper-250 (1.16.3)

**Comment by LeehamElectronics** [comment]
Can you please upload your CoreArena settings.yml, your startup log and arena.yml into paste bin so I can also see what other plugins you are using. I am using the latest version of CoreArena and the procedural damage system works fine using WorldEdit.
Thanks @NightFuryStrike

**Comment by NightFuryStrike** [comment]
This is an issue that happens everywhere on my server in all worlds when corearena is installed, even when arenas are not running. Apologies for not being very clear in my first post.

Please create a new survival world with CoreArena installed and go out into the world and set off some TNT or let some creepers explode. They don’t destroy any blocks anymore in normal survival.

If you can’t reproduce this issue yourself, I will upload the folders for you tomorrow. Thanks

**Comment by kangarko** [comment]
Thanks will be solved.
