### ISSUE TITLE
Permissions for classes/tiers?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#374]
are there permissions for things like classes and class tiers for use as perks?

for example if i want to give players access to better classes and upgrades as they rank up on the server....

**Comment by LeehamElectronics** [comment]
Check the wiki for permission nodes it's already there @KasearMC

**Comment by KasearMC** [comment]
i saw the permissions in the wiki. there aren't many so i wasn't sure if it had all of them.
are there plans to add more permissions like what i mentioned?

**Comment by LeehamElectronics** [comment]
```
corearena.class.Archer
corearena.command.join.CBD
```

They already exist, here are some examples above. @KasearMC

**Comment by LeehamElectronics** [comment]
I think the permissions part of the wiki needs updating Matej...

**Comment by kangarko** [comment]
Thanks, I or my friend will update it shortly!
