### ISSUE TITLE
Arena schedule?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#375]
can we configure it so that certain arenas start at certain times on certain days?

for example if i want one arena to only run at 3pm and 5pm every day, and another arena to only run on tuesdays and fridays at 8am....
players would have to register for the arena beforehand or join before the arena launches on schedule..

**Comment by LeehamElectronics** [comment]
You can already do this using the /arena toggle command
Just download the timed commands plugin or command timer to make commands run at specific times. @KasearMC

**Comment by kangarko** [comment]
Thanks for answering Leeham!
