### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by shywolf91** [kangarko/CoreArena#376]
Hello

I am an owner of a semi-vanilla minecraft server and my playerbase have been asking for some pvp type additions. I am currently looking at various ways I can accomplish this. The simpleest way would probably just use worldguard but I do feel like certain plugin features would make it more fun.

My main question is would corearena be ideal for a semi-vanilla survival server? I'm not looking for any plugin that would require its own server or add another world. I would just like to add maybe one (or a few) arenas that players can use

**Comment by kangarko** [comment]
Hey there!

CoreArena is a minimally invasive plugin if configured so. You can disable what you don't need such as procedural damage. You can also enable PvP in arenas, so I believe with a bit of a configuration you can fit CoreArena into your server's style :)
