### ISSUE TITLE
1.16.3 paper: clicking rewards in /ca menu gives dyed leather tunic on latest update 2.8.1

### ISSUE THREAD

**Issue by Eth4ck1e** [kangarko/CoreArena#377]
We updated to your latest version yesterday and now cannot open the rewards menu (from 2.8.0 to 2.8.1).  Instead, it gives us a dyed leather tunic.  There are no errors reported in the console or the plugin error log.  I tested a fresh install on a separate server and got the same results.  Then I downgraded back to 2.8.0 on the test server and the menu works again.  This has to be a bug introduced in the latest release.

**Comment by kangarko** [comment]
It was a joke. Just kidding. I got it fixed to the next release :)
