### ISSUE TITLE
Arena Leaderboards?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#378]
does core arena have the option to enable leaderboards per arena?
like showing how many times a player won an arena or their kills?

**Comment by LeehamElectronics** [comment]
At the moment the only place holders available are available on the wiki under placeholders, you can't really setup leaderboards until Matej adds placeholders such as total kills and total wins per player. At the moment you can sill create scoreboards using other plugins such as animated scoreboard and just use the placeholders on the wiki to show stats.

Once Matej adds total player placeholders for kills and wins and so forth, you can use the LeadsrHeads plugin to create leader boards.

Hope that was helpful 

- Liam

**Comment by kangarko** [comment]
Thanks to Leeham for answering!

**Comment by brandcrystal** [comment]
I also would love this feature.

**Comment by LeehamElectronics** [comment]
Now that it's open source you can add this yourself if your familiar with Java. When I get time I'll give it a go but Rn I'm flat out with work.
