### ISSUE TITLE
Arena Teams?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#379]
are players able to form teams in the arena?
for example when players are in the lobby there's an option to form a team with specific players or join teams.

**Comment by LeehamElectronics** [comment]
This would be a great option to add to the road map, perhaps adding the option for friendly fire and combing XP gained and spread it across all team members.
At the moment it's not possible sorry.

**Comment by kangarko** [comment]
We did have this option for Puncher and the code already got removed. When we'll be releasing the next major version of the plugin we'll add it back.

**Comment by LeehamElectronics** [comment]
What's Puncher? @kangarko

**Comment by kangarko** [comment]
A 2017 minigame plugin we had, discontinued.
