### ISSUE TITLE
CoreArena XP does not sync with players actual XP

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#381]
Players receive XP / levels as they are playing like normal, however CoreArena takes too much priority when it comes to storing this data in game.
For example, when I use my ShopGUI+ Plugin to purchase things using XP, the XP and levels are taken from the player like normal, yet CoreArena does not update its levels for players within the arena.
This results in an` out of sync issue.`
I found that after spending all my XP, I go and kill a mob and pick some XP from CoreArena and then my XP levels go right back to where they were before, this completely limits the functionality of player XP and levels thus preventing us from making our own version of the Upgrade sign with GUI's such as ShopGUI+

I hope this can be easily fixed by forcing CoreArena to take the players vanilla XP level as the basis of their XP, so its all in sync, or simply making CoreArena check the players vanilla XP instead of ressting it back to what it "thought" was the players XP.

Here is a screen shot of the phenomenon, as you can see in the bottom left, the player has X amount of XP / levels, and in the top right CoreArena says that the player has Y amount of XP / levels. I hope this can be fixed, I and others would really appreciate it.
https://imgur.com/a/wMZQTmn

Thanks!

**Comment by kangarko** [comment]
Thanks for letting me know, however I will be unable to implement this chance in the near future. Given the project is now open sourced anyone can contribute to it. Thank you for your understanding.
