### ISSUE TITLE
1.16.3: German Language

### ISSUE THREAD

**Issue by OnlyPW** [kangarko/CoreArena#382]
Your update description said:
 2.5.9

        New | Added high-quality German translation.

 kangarko, Mar 4, 2020 
(https://www.spigotmc.org/resources/%E2%98%85-corearena%E2%84%A2-next-level-mob-arenas-2-maps-1-8-8-1-16-3.42404/update?update=321005)

How can I activate the language German?
I have already tried some things with DE, de-DE

thanks a lot

**Comment by kangarko** [comment]
I apology, we had to remove it due to bugs. You can just customize the file yourself.
