### ISSUE TITLE
1.16.3 - Iron block (mob spawners) and dianond block (player spawner blocks) stay visible when the round starts.

### ISSUE THREAD

**Issue by brandcrystal** [kangarko/CoreArena#383]
Not sure why this is happening, any help would be lovely. Thank you!

**Comment by kangarko** [comment]
Here's how to fix:
1. /ma edit
2. remove those blocks manually
3. get the tools, then roll through your inventory so the visualized blocks appear and disappear
4. when they disappear, do /ma edit again
5. then /save
6. optional- take arena snapshot 
7. that's it!
