### ISSUE TITLE
1.16.4: CoreArena fails to load

### ISSUE THREAD

**Issue by IMS212** [kangarko/CoreArena#384]
I am on 1.16.4 with a test build of Paper 1.16.4, and all plugins work other than corearena. Here is the error: https://pastebin.com/YHJ0482L (not much else to say)

**Comment by LeehamElectronics** [comment]
Looking at your paste bin log, I don't think your using the latest CoreArena version, try using the latest one from Spigot.

**Comment by IMS212** [comment]
Version 2.8.2 did not work either, with roughly the same error. https://pastebin.com/arKqKns5

**Comment by kangarko** [comment]
1.16.4 not ready yet, please wait for the update
