### ISSUE TITLE
1.16.4 release date?

### ISSUE THREAD

**Issue by brandcrystal** [kangarko/CoreArena#385]

**Comment by brandcrystal** [comment]
Sorry I clicked enter too fast, I updated my server today foolishly thinking everything would work, now I cannot downgrade. Send help!

**Comment by kangarko** [comment]
Ready when it's ready

**Comment by kangarko** [comment]
Tomorrow estimated time

**Comment by LeehamElectronics** [comment]
I believe Matej is already aware looking at https://github.com/kangarko/CoreArena/issues/384#event-3958899810
For those who forgot to make a backup of their worlds before updating, this is a pretty urgent update

**Comment by LeehamElectronics** [comment]
oops just saw your comment lol
