### ISSUE TITLE
MySQL or Local?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#386]
1.16.3

i'm not using a proxy and i think i'll only have about a few arenas. assuming my server will have hundreds of players online, should i use a MySQL database for CA?

also i notice TPS drops sometimes when i set a mob spawner in the arena (it probably happens with other actions as well). would using a MySQL database reduce the lag?

**Comment by kangarko** [comment]
Test both, see what works best for your setup.
