### ISSUE TITLE
Only bought this plugin for a premium price last week, now it's open source?

### ISSUE THREAD

**Issue by brandcrystal** [kangarko/CoreArena#387]
I would just like some clarification on why it's now open source all of a sudden, is there any rebate to this? As it's not very fair.

**Comment by LeehamElectronics** [comment]
Dammed if you do, dammed if you don't I guess. I'm happy with it, means we might see more updates and features now. When I finish school I might even have time to add my own spin on CoreArena which would be fun.

**Comment by brandcrystal** [comment]
I understand! It was just a lot of money to now be used on every server! <3 I love the server and the development though!
