### ISSUE TITLE
 No potion effects in arena lobby

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#389]
I notice that when a player is joining the arena, any current potion effects are stored and removed when they join the arena lobby, and then the effects are restored when they leave the arena, that is good.

When players are in the arena lobby, they can switch between classes to drink potions and eat golden apples from different classes. The problem is that those potion effects persist when the arena battle starts.
They can restock the potions by switching classes again, or when the battle starts it restores the class inventory.

It is essentially cheating for players to benefit from different classes by gathering potion effects before the battle starts. It also negates the uniqueness of having certain potions for specific classes.

### Handling This:

I don't think that removing/resetting potion effects when the battle starts would be a good way to handle this. That might also remove gear effects, for example using a custom enchantments plugin to give gear certain potion effects.
If those effects are also removed then the player will have to re-slot their gear to get it back.

Preventing players from being able to eat or drink while in the arena lobby before the battle starts seems effective.
An option in the config files for each arena to allow us to choose whether players are allowed to eat and drink in each arena lobby would also let us decide if players can do that in specific arenas.

**Comment by kangarko** [comment]
Thank you, however right now we only focus on fixing severe bugs, we are also open source so anyone reading can take on and contribute to the code
