### ISSUE TITLE
/ma edit when not in arena

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#39]
Could you make /ma edit like this. If the arena edit is toggled and the user types /ma edit but is not in the arena it will disable the arena edit mode that they are in. e.g. I'm in an arena and i type /ma edit. I edit the arena then fly away. This is proposing that if you are no longer in the arena whilst in arena edit mode and you type /ma edit, it disables arena edit mode.

**Comment by kangarko** [comment]
Great suggestion, added right away :)
