### ISSUE TITLE
Regarding snapshots and tall grass/large fern restoration

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#390]
Minecraft: 1.16.3
Paper: 253
CA: latest
WE: latest

I realize that this is probably more of an issue with world edit. I'm going to talk with them about it too but I'd like some information from CA's end first.

The issue is essentially that when making snapshots of the arena (initial and damaged), it doesn't always properly restore tall grass and large fern. I notice that a lot of the tall grass and large fern are only half of their size.

CA's restoration of tall grass and large fern is a lot better than using world edit commands to "//set" tall grass and large fern, so I was wondering if the restoration can be improved within CA?

If not, is this an issue that can and should be resolved on WE's end?

**Comment by kangarko** [comment]
Sorry, we don't modify the schematic file (the one where snapshots are stored) and only call worldedit API, nothing I can do on my end unfortunately

**Comment by KasearMC** [comment]
All right no prob.
By the way, does fast async world edit perform better with arena snapshots compared to regular worldedit? Should I use FAWE instead?

**Comment by LeehamElectronics** [comment]
> 
> 
> All right no prob.
> By the way, does fast async world edit perform better with arena snapshots compared to regular worldedit? Should I use FAWE instead?

Please read the common issues part of the wiki where it mentions FAWE:
https://github.com/kangarko/CoreArena/wiki/Common-Issues
