### ISSUE TITLE
Offhand slot in class creator.

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#392]
Can we please get an offhand slot in the class creator?

https://i.postimg.cc/prKVVDRP/r6hu87r6yd5et.jpg

The image above for example. The stack of 5 stained glass can be that, or a different color stained glass. When hovered over it could say something like "The empty slot to the right is for the offhand item."
When an item is placed in that empty slot it will appear in the offhand.

**Comment by kangarko** [comment]
Thanks for your suggestion!
