### ISSUE TITLE
2 Bonus Maps (Not sure where to message you)

### ISSUE THREAD

**Issue by UltimateInfamous** [kangarko/CoreArena#394]
I purchased the plugin, but I was told to message you for the 2 bonus maps.

**Comment by KasearMC** [comment]
i purchased the plugin too and would also like the two bonus maps. how should we contact you for them?

**Comment by kangarko** [comment]
Here you go!

CoreArena Maps Package:
https://mega.nz/#F!FzRBQJDb!eDg6i4NYGt7zl30NPQ3aIQ

Enjoy them!
-Matej
