### ISSUE TITLE
What is Next_Phase_wait

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#397]
1.16.3

In the arena folder configs:

The warm-up period between switching phases
Next_Phase_Wait: 10 seconds

If that is supposed to give a wait time before the next phase starts, It ain't working.
So please let me know what it's supposed to do and if it really is broken I will open a bug report for it.

**Comment by kangarko** [comment]
If you have Next_Phase_Mode set on "monsters", then the phase wait time is how long we wait from the moment you kill the last monster in the arena before we spawn monsters from another wave
