### ISSUE TITLE
Minecraft Version: 1.16.2 Entire Arena selection deleting itself

### ISSUE THREAD

**Issue by FATGUY46** [kangarko/CoreArena#398]
The entire arena selection is completely erased when reverting to the initial snapshot. This happens when pressing "Restore the initial snapshot" and when the game is about to start. It's been happening no matter what I do. I've tried using big and small arenas, etc. Please Help! 
Sorry if this is formatted incorrectly.

**Comment by kangarko** [comment]
Any errors? Are you using FAWE or AWE? They may have such problems, if so, please try using vanilla WorldEdit.

**Comment by FATGUY46** [comment]
That seemed to work, thank you!! There were no errors and it was just FAWE causing the issue.
