### ISSUE TITLE
Class limit per arena

### ISSUE THREAD

**Issue by KasearMC** [kangarko/CoreArena#401]
Can we get an option in the arena configs to add limitations to class selection? For example a maximum of 10 archers and 10 warriors in the specified arena.

This will help limit the potential abuse of classes without having to limit the usability of the class.
For example if I want players to be able to upgrade the archer to have a stack of explosive arrows, it would be a bit of a mess if like 30 players choose that class.
There would be nothing but explosions. The class and arena would be completely imbalanced when that happens. Reducing the amount of arrows would only make it less usable.

**Comment by kangarko** [comment]
Thanks, however I don't have the resources to implement this right now, CoreArena is open source so anyone can take over this task

**Comment by LeehamElectronics** [comment]
@KasearMC this is already possible using something like Citizens NPC, simply have 20 NPCs and when player clicks on them it gives them the class, but it also teleports the NPC away to another location so it can not be chosen again. Then at the end of the arena simply have all the teleport commands run again causing e NPCs to TP back ready for the next game.

Then just deny them access to the class GUI.

Anything is possible with a bit of customisation👍👍
