### ISSUE TITLE
1.16.3 Seperate arena rewards commands

### ISSUE THREAD

**Issue by FATGUY46** [kangarko/CoreArena#403]
Hey, I have an Arena subserver and a Factions subserver, linked with Bungee. I'm trying to sync Nuggets between the servers, so the rewards will take effect in the server that players have their bases in, etc. However, I want my players to only be able to upgrade classes in the Arena subserver. (Because what's the point of buying 10 diamonds in the Arena subserver? They are useless there but very useful in the Factions subserver.) 

My solution to this issue would be to have a separate command for each Arena shop. For example, 
/arena shop Blocks 
/arena shop Items
/arena shop Packs
/arena shop Class
(And of course /arena rewards wouldn't be removed)

I would use this to block players from using all of those commands except /arena shop Class in the Arena subserver, so that they can only upgrade their classes and not buy useless items. Then, I would block /arena shop Class in my Factions subserver, so that they can only upgrade their classes in the Arena subserver. 

A solution to the problem I'm having is required for me to implement CoreArena on my server. So this is urgent for me.
Also, I'm running them separately to reduce lag for the players on the Factions subserver.

**Comment by kangarko** [comment]
Thank you very much! However right now I cannot take any more suggestions. CoreArena is now open source so anyone reading this is welcome to add this.
