### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Butane973** [kangarko/CoreArena#404]
Minecraft 1.16.3, Spigot and FAWE  1.16.442

Successfully setup the arena, everything shows perfectly. I take a before and after snapshot, even verify the schematic files are good. However, when my players join, it seems when it loads the undamaged snapshot it is switching chunks/sections/blocks around, misplacing them. I tried this with one of the purchased maps and one a user created with the same results.

I followed both videos in setting everything up. None of the config files have been touched as of yet.

I do notice the schematic folder of FAWE are all .SCHEM files, while the others are .SCHEMATIC.   Doubt thats the problem tho as I have loaded the ''undamaged schem'' and pasted it on a superflat world without issue. 

Any suggestions?

**Comment by kangarko** [comment]
FAWE is causing this issue, try using vanilla WorldEdit.
