### ISSUE TITLE
1.16, Map destroy after arena start

### ISSUE THREAD

**Issue by Ciredex** [kangarko/CoreArena#405]
Hi
After building the map, i set the mobspawns, playerspawns, arena region and lobbypoint. The menu said, the arena is now playable. So i startet the arena. The Map immediatly "disappiered" and nothing happend. I did a snapshot befor startet the arena, but now when i try to restore this snapshot, nothing happens. My server has a Rollback function, which doesnt work either.
![2020-11-22_19 43 27](https://user-images.githubusercontent.com/64593302/99914167-d496d400-2cfb-11eb-882c-5e1fc2afa9e7.png) --> This is what the map looks like now

**Comment by enterih** [comment]
I'm just adding the error.log file 
https://pastebin.com/GMAGigHz

**Comment by kangarko** [comment]
This is a FAWE problem, I am sorry. You need to contact their support. I recommend using vanilla WorldEdit instead, because we have anti-lag functions in it.
