### ISSUE TITLE
1.16.4: Server timeout

### ISSUE THREAD

**Issue by brofin** [kangarko/CoreArena#407]
Have had the plugin added to the server for a few days, but have not actually interacted with it at all yet to create an arena. Have not changed any configs yet either so everything is default settings.

Ctrl-F'ing through this shows the corearena pops up a lot. Not sure if it's a conflict with another plugin.

[Console Errors](https://pastebin.com/9tcjyRWS)

**Comment by kangarko** [comment]
I apology, this seems like an incompatibility with some other plugin when we use the NBTAPI library to read the tag of the item the player has in his hands. We do this to determine whether the player is editing an arena, and thus show him where region or spawn points are.

If you won't be able to diagnose this by finding that plugin, write me your paypal address either below or over matej@mineacademy.org and I refund you.

**Comment by brofin** [comment]
Oh, that's unfortunate. Was really excited to try this plugin.
Do you have any tips to how I could troubleshoot this? The server was running for almost 12 hours before the errors started appearing.
How often do these tag checks occur? Or is there a certain event that triggers it?
Because I don't know how to trigger the error messages (other than waiting), it will be difficult to determine what's causing it, even if I start deactivating plugins one by one.

**Comment by kangarko** [comment]
It was called from org.mineacademy.corearena.lib.fo.menu.tool.ToolsListener.onToolClick(ToolsListener.java:64) which occurs hundreds of times a minute on each right or left click (even clicking air). I've never seen a crash from this but I assume your server version is modified (aka not Paper nor Spigot) that causes it. CoreArena and Foundation are both open source, anyone can have a look at how it's done.

**Comment by brofin** [comment]
I am using regular Paper for my server, so nothing modified.

I have a plugin called SimplePets. I have noticed random issues with the Armor Stand Pet feature from that so I’m suspecting that may have played a part in it.

On Dec 3, 2020, at 7:10 AM, Matej Pacan <notifications@github.com> wrote:

﻿

It was called from org.mineacademy.corearena.lib.fo.menu.tool.ToolsListener.onToolClick(ToolsListener.java:64) which occurs hundreds of times a minute on each right or left click (even clicking air). I've never seen a crash from this but I assume your server version is modified (aka not Paper nor Spigot) that causes it. CoreArena and Foundation are both open source, anyone can have a look at how it's done.
