### ISSUE TITLE
[Request] Spawners only active near players

### ISSUE THREAD

**Issue by Techno-Panda** [kangarko/CoreArena#41]
So i have noticed while testing the plugin the mobs spawn from which ever spawner they please to, well with in the chance limits but i was wondering if it was possible to  get it so only spawners near the player are active so we don't have mobs spawning on the other side of the map doing no good to kill said players. if you could add like a radius that the players need to be in; in order  for the  spawner to activate that would be really useful for the non pvp  arenas

**Comment by kangarko** [comment]
Radius to each individual spawner in its settings or a flat radius in settings.yml? Having exams right now so I may only have time for the latter, if it holds?

**Comment by Techno-Panda** [comment]
which ever you could do faster but would be prefer the individual spawner but i know you are busy so which every you think is easier to come out with while you are doing what you have to do irl

**Comment by kangarko** [comment]
Added as "Spawner_Activation_Radius" to settings.yml! :)

**Comment by Techno-Panda** [comment]
so when i requested this i forgot about bosses and it would affect there spawners

**Comment by kangarko** [comment]
Bosses are also affected. CoreArena cannot see whether or not a monster is a Boss and treats it as any other entity.

**Comment by Techno-Panda** [comment]
So um i know its closed an all but i was wondering if it would be possible in the feature to get a different type of spawner that is for bosses that isn't effected by range.

**Comment by kangarko** [comment]
No sorry I think that's just not-so-important complication and I have more important features to work on right now.
