### ISSUE TITLE
1.16.4 Specified max=50 error

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#411]
Happy New year to you Kangarko

1) Put your Minecraft version in the title.

Tunity 1.16.4 #178 - Error: Number of aliases for non-scalar nodes exceeds the specified max=50
CoreArena 2.8.6

2) Be clear: What is your current situation, the desired situation, and your problem?

The plugin will not load. I have reduced the number of dungeons down to 30 and I am still getting this error.
I have no idea where to look for the error and what is breaking to cause this.

https://hastebin.com/moxirumicu.makefile

**Comment by kangarko** [comment]
The haste appears empty for me. Please use pastebin.com. 

Anyways, this is a fault in Tunity as it seems. Test on Paper and if the bug goes away, unfortunately there is little I can do. If you sitll get the problem then comment below (I will read it).
