### ISSUE TITLE
Minecraft Version: 1.16.4 - Arena not ending correctly

### ISSUE THREAD

**Issue by HyplexMC** [kangarko/CoreArena#412]
Hi so i have my config for the Arena set like so (in attachments)
i have set the `  Arena_End_No_Monsters: 4` to `4` and to `5` and the arena still will not end properly
on phase 5 (the last phase) once all mobs are killed the arena just keeps going and ends on timer and doesnt reward nuggets. ive done everything i know how to do and ive got nothing working. 
EDIT: i am also not getting any error in console or in the error log

**Comment by HyplexMC** [comment]
Also phantoms burn in sunlight when the mob burn in sunlight is set to false

**Comment by kangarko** [comment]
Can you verify there's no monsters in the arena using a third party plugin that can count the monsters? If this is too difficult then set Debug to ["*"] in settings.yml and see console messages when the arena should end but it does not.

**Comment by kangarko** [comment]
Regarding Phantoms, this is outside of our control I believe due to lacking APIs in Bukkit, sorry.

**Comment by HyplexMC** [comment]
I am so sorry for such a late response, been super busy with other things and got really distracted, i think i figured out my issue and thats, that normal minecraft spawning is happening in the arena for example a chicken spawns in and my /butcher command does not kill them when i am testing. I found the animal and killed it and the arena finished correctly. My only question out of curiosity would be does the arena on monsters mode calculate all entities (for example a hologram) in the arena before a phase change or arena end or does it only look for mobs?

**Comment by kangarko** [comment]
We only look for monsters.

**Comment by HyplexMC** [comment]
Ok well idk if a chicken counts as a "monster" in your books, but the arena wasn't stopping cause chickens and neutral mobs were spawning on the grass when the arena was active.

**Comment by kangarko** [comment]
This is controlled by isAggressive method that I just adjusted to this format below, should be patched in the next version:

![a](https://i.imgur.com/HzfhMnW.png)
