### ISSUE TITLE
1.16.5 Vault Support

### ISSUE THREAD

**Issue by HyplexMC** [kangarko/CoreArena#417]
Hi, so i am creating a new gamemode and i am using CoreArena as one of the main functions of the game and the entire game was designed around the nuggets and i am now at the last parts of the developing process and it turns out the nuggests are completely independent from server economy/vault. The use of the coins is not a good option to connecting the arena to the economy, what you should have is a part in the main config where you can toggle vault support and so the nuggests can connect to vault cause now i have to either take months worth of developing and throw it away or use your poorly designed GUI system, and i say poorly because there is almost no customization to it what-so-ever. Also you should be able to turn off the EXP drops in the arena cause having them always on kinda forces you to use your "in-game currency" system, why would anyone want to have a currency system thats is completely independent from everything else. Your plugin is not a all in one plugin so people have to use other plugins to make things and since you can connect it to vault, everything gets shut out and its absolutely retarded. POOR DESIGN.

**Comment by HyplexMC** [comment]
I will pay for you to add Vault Support with nuggests

**Comment by LeehamElectronics** [comment]
Haha poor wording mate but I'll link you to a post I made about this months ago before the plug-in was open sourced.

**Comment by LeehamElectronics** [comment]
https://github.com/kangarko/CoreArena/issues/353

**Comment by LeehamElectronics** [comment]
Also check this out, this is the most important thing to be fixed in CoreArena in my opinion, and in short, it will allow us to make awesome IN GAME shops for players to buy things from while they are playing.

https://github.com/kangarko/CoreArena/issues/381

Also sorry I have been inactive @kangarko , finished school and been working so haven't had time for MC or dev stuff at all.

Cheers

**Comment by kangarko** [comment]
Thanks, however we're only providing critical bug fixes to CoreArena right now
