### ISSUE TITLE
git-Paper-586 (MC: 1.16.5): Error: Number of aliases for non-scalar nodes exceeds the specified max=50

### ISSUE THREAD

**Issue by Elioz** [kangarko/CoreArena#419]
Hello,

After adding arenas, I got this error

:06
java.lang.ExceptionInInitializerError
at org.mineacademy.corearena.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:291)
org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50
at org.mineacademy.corearena.lib.fo.settings.SimpleYaml.loadFromString(SimpleYaml.java:78)
at org.mineacademy.corearena.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:246)
at org.mineacademy.corearena.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:326)
at org.mineacademy.corearena.lib.fo.remain.CompMetadata$MetadataFile.<init>(CompMetadata.java:395)
at org.mineacademy.corearena.lib.fo.remain.CompMetadata$MetadataFile.<clinit>(CompMetadata.java:387)
at org.mineacademy.corearena.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:291)
___ _
/ _ \ ___ _ __ ___| |
| | | |/ _ \| '_ \/ __| |
| |_| | (_) | |_) \__ \_|
\___/ \___/| .__/|___(_)
|_|
!-----------------------------------------------------!
Error loading CoreArena v2.8.8, plugin is disabled!
Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 1.8.0_282
!-----------------------------------------------------!
Error: Number of aliases for non-scalar nodes exceeds the specified max=50
!-----------------------------------------------------!
[CoreArena]: Disabling CoreArena v2.8.8

What can causing this issue and how it can be fixed?

Thanks!

**Comment by Elioz** [comment]
Update,

After deleting few arenas from the .db file, it's working,
What can cause this issue?

Please, help me ASAP, this issues is delaying my server opening.

**Comment by kangarko** [comment]
This is a limitation in the library which Spigot is using to save .yml files, seems like some of your arenas had some data in them that caused the data.db file to have more than 50 sections (or so)

```
hello:
  second:
    third:
      forth:
        etc....:
```

So yeah you can just look for those anomalies in your data.db and delete the entire section

**Comment by Elioz** [comment]
I checked what you said, unfortunately, I wasn't able to find anything with 50 sections,
I deleted few arenas again and it solved the issue, right now I have 11 arenas and adding one more arena will cause this issue,
this is my .db file before the removing arenas
https://pastebin.com/B95Lafse

And this is after (which is works)
https://pastebin.com/s3A5vq52

Your help will be appriciated.
Thanks.

**Comment by kangarko** [comment]
Thanks!
