### ISSUE TITLE
Direction of Lobby and Player Spawnpoints

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#42]
Maybe a way to set the way a player is looking when spawned into the arena lobby or spawnpoints. Maybe they hold shift and left click with the item in their hand or something. It doesn't have to be that, just something where I can change the direction the player is facing :)

**Comment by kangarko** [comment]
Thank you, will look into it!

**Comment by LogGits** [comment]
Maybe a command that gets the nearest point (doesn't get picky with what type (lobby, spawnpoints)) and finds the nearest one to the players feet and sets the direction to the direction that the player is looking.

**Comment by LogGits** [comment]
Any news on this?

**Comment by kangarko** [comment]
Yes, I'll be reviewing all improvements on all plugins' pages after 1.13 update.

**Comment by kangarko** [comment]
Thank you for proposing new features. Right now we are no longer open for suggestions as we have works on more prioritized features and projects.

**Comment by LogGits** [comment]
Maybe you can you provide an option in the configuration so that we can manually change it (for now). Players are telling me that it's really annoying that they spawn facing the wrong way. It's literally a yaw and pitch save + teleporting them to the location.

**Comment by kangarko** [comment]
Will be implemented

**Comment by LogGits** [comment]
This is coming up on 1 year to just store a yaw and pitch value 😢

**Comment by kangarko** [comment]
It's not that simple. The whole location system in place is unified and with the current approach we would need to store yaw and pitch for all region points like monster spawn locations etc. Rewriting takes a while due to this unfavorable situation so I decided to postpone it for the next major feature update.

**Comment by imgamg** [comment]
If you want to make it work with previous builds just ignore yaw and pitch if its not specified. Monster spawn locations wont matter at all because they just target the closest entity.

**Comment by kangarko** [comment]
Pulled to roadmap
