### ISSUE TITLE
Issue #419 still exist

### ISSUE THREAD

**Issue by Elioz** [kangarko/CoreArena#420]
Hello,

After clone and compile the plugin with the fix commit in ticket #419, the issue still exist,

I really need your help with solving this since it's delaying my server opening.

Thank you.

**Comment by kangarko** [comment]
Please send me your CoreArena ZIP so I can reproduce this.

**Comment by Elioz** [comment]
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/6302803/CoreArena.zip)

Thanks.

**Comment by kangarko** [comment]
Thanks, I deleted it because it had your mysql password :)

**Comment by kangarko** [comment]
<img width="1025" alt="Screenshot 2021-04-13 at 12 26 43" src="https://user-images.githubusercontent.com/1918426/114538303-873be480-9c53-11eb-8e54-77b20eecf191.png">
Oh I see, the 1.8.8 version of Spigot has an outdated SnakeYAML library that means there's no way to set the aliases option

**Comment by kangarko** [comment]
Effectively that means you need to either upgrade your version or delete data.db and start step by step to find out the problematic arena/class/upgrade and avoid it

**Comment by Elioz** [comment]
How could I forget from my MySQL passowrd???
Thanks first of all,

now, which version should I upgrade? I'm using paper 1.16.5.
you mean the server build or something else?

**Comment by kangarko** [comment]
Yeah I recommend you to upgrade to Paper 1.16.5 because there we can use the LoaderOptions in SnakeYAML to allow multiple aliases/nodes

**Comment by Elioz** [comment]
But I'm using paper 1.16.5 now...

**Comment by Elioz** [comment]
Just downloaded CoreArena 2.8.9,

Still same... :(

!-----------------------------------------------------!
Error loading CoreArena v2.8.9, plugin is disabled!
Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 1.8.0_282
!-----------------------------------------------------!
Error: Number of aliases for non-scalar nodes exceeds the specified max=50
!-----------------------------------------------------!

**Comment by kangarko** [comment]
So sorry, what about this version? Could not load it because I don't have the sola2/3 worlds but the error seemed to be gone.
 
[CoreArena-2.8.9.jar.zip](https://github.com/kangarko/CoreArena/files/6305184/CoreArena-2.8.9.jar.zip)

**Comment by Elioz** [comment]
Seems like it's working now... Thanks!
