### ISSUE TITLE
{player} placeholder not working

### ISSUE THREAD

**Issue by Elioz** [kangarko/CoreArena#421]
Hi,

The {player} placeholder not working on executing command when event is happend (arena start/end etc),
Please find the attached screenshot.
![image](https://user-images.githubusercontent.com/11987095/115075596-fccddc00-9f03-11eb-85e5-16cb2a9b453f.png)

Thank you.

**Comment by Elioz** [comment]
Kindly reminder

**Comment by kangarko** [comment]
<img width="753" alt="Screenshot 2021-04-21 at 12 54 20" src="https://user-images.githubusercontent.com/1918426/115542586-b3cdad00-a2a0-11eb-9c52-e5ad5dca35ec.png">

That is correct for Console commands. To run console commands for each players, set Arena.Console_Commands_For_Each to true in settings.yml

**Comment by Elioz** [comment]
Thanks.
