### ISSUE TITLE
Why the hell are MySQL queries running on the main thread?

### ISSUE THREAD

**Issue by eDexiam** [kangarko/CoreArena#424]
Seriously, this is the first thing that is explained in the spigot wiki for handling databases, you should NEVER run queries on the main thread because if there is lag on the query for any reason it's going to lock up the entire server. As seen below.

![image](https://user-images.githubusercontent.com/29255472/129462621-440fda1f-ec6b-4294-bb06-2abbe872ad4f.png)

You should rectify this immediately, this is not acceptable considering this was previously a PREMIUM plugin which you used to charge money for.

**Comment by kangarko** [comment]
One of the first things when asking for support is upholding a certain ethical standard of communication which you clearly lack.

CoreArena is open source, if you want changes you can compile it yourself. There was a reason this query runs on the main thread which I am not obliged to share with you.
