### ISSUE TITLE
Paper 1.17.1 #224 - CoreArena 2.9.1 and 2.9.2

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#425]
1) Put your Minecraft version in the title.
FoException Report: Failed to setup entity reflection! MC version: 1.17
I also tested this with paper 1.17.1 release221, 218 and Tuinity 1.17.1 release 33 in-case it was an update from their side. 
Tunity 1.17.1 release33 works fine, so there is an issue with something paper have changed in their recent updates and CoreArena.

2) Be clear: What is your current situation, the desired situation, and your problem?
There are no errors on start-up. The error above occurs after the timer runs down to 1 second, it will teleport you to the arena, then on starting the arena it then stops and kicks the players to the Dungeon Lobby .

3) If needed - upload your plugin's folder here and any errors using pastebin.com.

https://pastebin.com/iy76Wj8b

Any assistance would be appreciated :)

**Comment by kangarko** [comment]
Thanks will be updated today
