### ISSUE TITLE
Mobs not taking damage?

### ISSUE THREAD

**Issue by celticpixie14** [kangarko/CoreArena#426]
1) Put your Minecraft version in the title.
**Version: 1.17**

2) Be clear: What is your current situation, the desired situation, and your problem?
**Mobs randomly do not take damage. Some instances they are taking zero damage upon spawning and others, they will take damage for so long and then take none at all. Only solution is for admin to use /boss butcher command.**

**Comment by kangarko** [comment]
Looks like either misconfigured Boss attributes or another plugin causing this, check either please.
