### ISSUE TITLE
Possible Bug: Bosses spawning in walls. 

### ISSUE THREAD

**Issue by celticpixie14** [kangarko/CoreArena#428]
Boss Version: 3.10.8 (CoreArena - 2.9.3) 
Server Version: Paper-249 1.17.1 #249 

Bosses seem to randomly spawn in walls, even after checking config files and spawner settings - ie radius 1 block - all set to this and still having issues. Mobs will spawn at least 5+ blocks away from the spawn points and inside walls. Having run separate dungeons several times, this seems to occur randomly after checking to see if it was certain spawn points. Thinking blocks may be an issue? This has been an issue for quite some time and have tried everything, including, having the spawners set in the air and dropping the mobs down into the dungeon (surprisingly this seems to work in a water themed dungeon where spawners are placed in the ground underwater), but did not stop the same thing happening in a dungeon with no water. Tried resetting dungeons, reloading plugin, no console errors on every attempt to fix.

**Comment by kangarko** [comment]
Thanks for reporting, however we have no control over mob spawners on where they pick up the spawn location as this is controlled by the Spigot API.
