### ISSUE TITLE
Core Arena wont even load up to start with

### ISSUE THREAD

**Issue by Zoneman1972** [kangarko/CoreArena#43]
Hey there,
I have been trying to install this plugin on my server for 3 weeks now and I keep getting the same issue everytime.
It just wont load in.
The following is a screen shot of the console error - http://prntscr.com/hnbukt
Can you please fix this so that I can actually use this plugin that I paid for.
Thanks
Zonemann

**Comment by kangarko** [comment]
Hello,

CoreArena requires a plugin named GameAPI, that you can download from https://www.spigotmc.org/resources/gameapi.48556/. This plugin does nothing, it is just a helper library with functions that can also connect other plugins of mine such as Puncher and AutoPlay.

Sincerely,
kangarko

**Comment by Zoneman1972** [comment]
OMG I feel like such an idiot. Sorry mate, I hadn't even noticed that
update coz I couldn't get the plugin to work, I just put it on the too hard
basket until I got more time.
I've also noticed that there is the additional plugin "AutoPlay"
As I purchased CoreArena in June, can you please allow me access to
download this one.
Proof of receipt below.

Thanks again for all your hard work and my apologies for not looking before
whinging :/
Zonemann

[image: Inline images 1]

**Comment by kangarko** [comment]
No worries, I have added you!
