### ISSUE TITLE
1.17.1 Server crashed

### ISSUE THREAD

**Issue by morphin06** [kangarko/CoreArena#431]
in 1.17.1

I don't know if its CoreArena or Boss plugin
Since i used them both

I used mobs creeper with skills teleport to player in and set it in arena
When creeper teleport to player and tried to explode in arena, it will crashed the server, i tried to test 5 time in my server, i also tried charged creeper but upon explosion. server crashed all the time.

and there's an error message in console it says coreArena 3 suppostedly CoreArena 4

Here is the console error https://pastebin.com/vabYNjgF

**Comment by kangarko** [comment]
I will add a catch mechanism for these errors in the next version so when it happens again you will get a more explaining error hopefully. Comment below when it happens again on the next version.
