### ISSUE TITLE
1.17: Plugin disabled

### ISSUE THREAD

**Issue by ShiroBlank** [kangarko/CoreArena#437]
Version: 1.17

Issue: When putting non-standard mob eggs into mobspawners (e.g. More health and effects)(not boss eggs) the server refuses too load the plugin after server restart.

**Comment by kangarko** [comment]
Please post me the full startup log uploaded to pastebin.com where the error is.

**Comment by ShiroBlank** [comment]
https://pastebin.com/Ad0viV7S here.

**Comment by kangarko** [comment]
Update to 3.0.10, let me know if that is still an issue there. And please ZIP me your CoreArena/ folder then (without mysql info)
