### ISSUE TITLE
GUI for modifying block breaks/interactions

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#44]
I saw a section in the arena config that allows us to modify what blocks can be broken in the arena. It would be cool if this could be modified using the built-in GUI.

**Comment by LogGits** [comment]
How it would work is the GUI would show all the blocks that are allowed to spawn you drga and drop items to add and remove blocks that can be broken/interacted with.

**Comment by kangarko** [comment]
Thank you for that suggestion. CoreArena currently doesn't support any GUI for changing its .yml files, but this may come in the future. Closing this, but I am thinking of porting Boss' GUI abilities to *all* plugins (except ChatControl).
