### ISSUE TITLE
1.18.1: Custom mob eggs doesn't work for spawnpoints.

### ISSUE THREAD

**Issue by TraceLosu** [kangarko/CoreArena#440]
Using custom spawn eggs (NBT tags), the plugin won't load and shows this error.

Exception log:
https://paste.gg/p/anonymous/2ebbeaca96d241489e09743ebd2f39a1

error.log
https://paste.gg/p/anonymous/f7261b5c150a4e4085980ead00144d99

**Comment by kangarko** [comment]
Sorry for the delay, what plugin do you use to get those eggs? Can you somehow save those eggs into a Class you create in CoreArena and then send me your data.db file so I can get the same item?

**Comment by TraceLosu** [comment]
[data.zip](https://github.com/kangarko/CoreArena/files/7931536/data.zip)

Here you go. We use minecraft commands to get these eggs.

**Comment by kangarko** [comment]
I'm so sorry for the delay, after having a look this is a major incompatibility I can't fix right now, at least not with the time I have at my disposal. When I am rewriting the plugin I'll make it more fail-proof to these kinds of custom made items. I was not able to read nor recognize these eggs:

<img width="1022" alt="Screenshot 2022-02-01 at 15 58 13" src="https://user-images.githubusercontent.com/1918426/151992549-8d3145f4-e664-41d3-85e8-c65168212382.png">
