### ISSUE TITLE
Survival items in arena

### ISSUE THREAD

**Issue by francozlex** [kangarko/CoreArena#443]
Hi, i'm about to buy the arenas plugin and i just have one question.
There is any manner to my players join the arenas with their own items and if they lose, they get the items back in their inventories?

**Comment by kangarko** [comment]
Hey!

You can set the "Allow_Own_Equipment" option to true for the arenas where you wish players to bring their own items. We will not give their items back if they lose during a fight if that option is true.

If that option is false, then players will choose a class when joining the game, and get their own items back after the game ends.
