### ISSUE TITLE
PAPI extensions to show Lobby Status and Player Count.

### ISSUE THREAD

**Issue by SkyHazeSB** [kangarko/CoreArena#446]
A feature that let's you use PAPI to display the status of an arena (Active, Inactive, Waiting for Players) and the amount of players currently in the arena. 

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.): It would allow owners to display more arena information for players before they join the arena. I'm using DeluxeMenu's to display the arenas so this would be an awesome addition for anyone else who's also using this or any other scoreboard menu.

2) What would happen if we won't implement this feature? How's your server being affected?: I won't be able to show any information about the arena's lobby or player information before a player joins the arena.

3) If suggesting something new - Can the old system be modified/improved instead? Yes, by adding this to the current Placeholders.

**Comment by kangarko** [comment]
Thanks, just to be clear, would this work:

{corearena_ARENANAME_status} -> "Active", "Inactive, "Waiting" (translateable)

You can use {corearena_ARENANAME_alive} to get player count already in the current version.

**Comment by SkyHazeSB** [comment]
That would be perfect! Also I didn’t even think to use {corearena_ARENANAME_alive} for the player count. Thank you so much!

**Comment by LeehamElectronics** [comment]
https://github.com/kangarko/CoreArena/issues/365

**Comment by SkyHazeSB** [comment]
> Similar read here: #365

That’s awesome, thank you so much.

Do you think you could add the arena status to the current placeholder like kangarko mentioned above as well? For example Active, Inactive, and Waiting?

**Comment by kangarko** [comment]
Sure, I will add {corearena_ARENA_state} to the next version!
