### ISSUE TITLE
[QUESTION] Custom arena with few things

### ISSUE THREAD

**Issue by maxlehot1234** [kangarko/CoreArena#45]
Hi, I just want to know if it wa spossible with CoreArena to do this:

1- I create an arena.
2- Inside the arena, we can have differents configs. (min/max players, mobs list, time, player kits, player bonus, etc)
3- When arena start, players need to fight the boss. They can revive X amount of times base on the config.
4- When players kills the boss, all players that stil alive will be rewarded by commands (money, exp, items, commands, etc)

EX:

1. I create arena1
2. 30 minutes to win (or loose)
3. 6 to 12 players maximum
4. Players coins, money, exp multiplier
5. Players can respawn/revive 2 times ONLY for arena1
6. 20 mobs (skeleton, spider, creeper, magma_cube) adn 1 BOSS
7. 1 default kits (diamond_sword with full diamond armor)
8. A GUI that allow players to buy kits with "coins"
9. Each kits will have a permission that I can give on events, buycraft etc. When player have a kit permission, he can get it for free (permanent access) OR he can buy it with "coins" in-game (temp kit for the actual game only).
10. Player that are alive AFTER killing all mobs and boss will be rewarded with commands.

Also, I want to know if players can join the arena with a simple command, like: ./ma join arenaname
Also, is it possible to make the lobby inside the arena and when the game start, mobs start spawning direectly in the map?

I just want to know if it was possible to do, since I want to do something like this on my server.

Thank you so much for this.

If everythin was possible, I will buy it for my server ;) I will create something unique (At least, I will try)

**Comment by kangarko** [comment]
Hello,

some of the features are possible, others not. You can specify the arena duration and minimum/maximum players. You can specify two lives, normal monsters and bosses, kits, a GUI for buying and upgrading kits (we call it classes) and finally you can specify commands that are run for the remaining players alive.

What is NOT possible, is that when players kill the Boss the arena finishes. It currently finishes when the arena gameplay time is up.

**Comment by maxlehot1234** [comment]
Is it possible to create ONLY ONE wave with a BIG BOSS in it? So when the boss was kill, game ended ;)

lundi 1 janvier 2018 13:09 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by kangarko** [comment]
Not exactly, but you can set the period between waves to longer than the arena duration, so only one wave is spawned, that will contain the big boss. When the arena duration is over, the arena finishes automatically.

**Comment by maxlehot1234** [comment]
So if for example the arena duration was 1 hour and setup the wave to be 1h30 it will be ended when players kill the boss? Or they need to wait until the 1h30 was ended?

When they kill the boss, all players alive will get a reward,right?

**Comment by kangarko** [comment]
When the arena duration is 1h and wave duration is 1:30, ONLY ONE wave will be spawned (the first at the arena start).

Arena ends after 1h, NOT after the boss is killed. This is how the plugin was made to function. I can add that option in the future.
