### ISSUE TITLE
1.18.2 Minecraft Version: Settings disappeared after server restart.

### ISSUE THREAD

**Issue by Thatorek** [kangarko/CoreArena#454]
I Installed and setup CoreArena today, didn't have any issues. Very easy setup, and easy top understand. I even had some players on the server running test games with basic Classes and custom Bosses from Boss Plugin. So the Issue started when setting up "Upgrades" I used the GUI and setup 6 Upgrades and made the signs so they could but them. Strangely only the Hell Fire Item worked. So I checked the GUI and the items where all gone except Hell Fire. So I tired re-dropping the items in and saved, didn't work. So next I tried placing the item in and saving and without opening the /ma menu again I restarted the server. The item I placed right before was now there and could be bought! But at that point the Hell Fire disappeared... So next step I took was deleting all the Upgrades from the GUI and restarting the server so I could start fresh. Once the server was up, everything was gone except the actual Arena config file for the Arena I made. So all Spawn Points.. Mob and Player, Classes, Rewards, and Mob Settings. Region was still there and the snapshots. So I checked the console log and there was no errors at any point, it loaded successfully.

Before this happened I had restarted the Server about 6 times during the day and the Arena kept working all day with multiple people playing and testing. 

You make great Plugins! Love them all! Hopefully I'm just stupid and did something wrong. Any Ideas?

**Comment by kangarko** [comment]
Thank you, everything will be fixed :)
