### ISSUE TITLE
1.18.2: Rank upgrades purchased with currencer reset on plugin reload/server reboot

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#455]
Any time the server restarted or the core arena is reloaded with /ma reload any class upgrades purchased by players are reset
[CoreArena.zip](https://github.com/kangarko/CoreArena/files/8644633/CoreArena.zip)

I have also tried using mysql instead of the built in storage with no changes

**Comment by kangarko** [comment]
Thank you, everything will be fixed :)
