### ISSUE TITLE
Getting game items in inventory after dying

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/CoreArena#46]
people are receiving these items when they die in the arena https://prnt.sc/hx3elb

**Comment by kangarko** [comment]
Any errors in the console? What's your MC version again please?

This can happen if the arena is not running or if the player is no longer joined in the arena. Please confirm both of this was false.

**Comment by AmazedMender16** [comment]
1.12.2 Latest version
No errors.

**Comment by kangarko** [comment]
PaperSpigot, Spigot or CraftBukkit?

All works for me, including when I leave the arena. Are player's inventories restored or can they bring own items?

Is the experience item collected correctly, or placed in player's inventory already in arena ?

![a](http://kangarko.com/artwork/misc/corearena_exp_pickup.gif)

**Comment by AmazedMender16** [comment]
Spigot... might have to with the teleport plugin you made me not working correctly ill test later on again..

**Comment by kangarko** [comment]
Keep me posted and include config.yml from that plugin. I tested and it worked for me.

**Comment by kangarko** [comment]
Closing in faith it has been resolved.
