### ISSUE TITLE
Add an option to disable the arena exp feature

### ISSUE THREAD

**Issue by Jerry-JR** [kangarko/CoreArena#469]
My server uses Exp as currency

I don't want experience reset to zero when I join the arena
Although the experience will be restored when exiting normally
It seems that you lose experience if you exit the server in the arena
I really need it, please

**Comment by kangarko** [comment]
You can convert your experience into your economy currency using the Gold Ingot item that you give as a reward using /ma item then just give this to your players, and they'll convert their arena exp to your currency.
