### ISSUE TITLE
EXP when killing mobs bug

### ISSUE THREAD

**Issue by SeptyIsHere** [kangarko/CoreArena#470]
Minecraft version: 1.16.5 (Server as well)
2) My issue is, when I kill two mobs that give the same amount of exp, the exp item stacks, and it only gives 15 EXP and I lose more because some mobs will be giving 500 - 700 exp.
![image](https://user-images.githubusercontent.com/68012136/175813219-353eba86-9594-441b-b085-1525f30655d7.png)
I wish that it will either separate, or stack the exp and MAYBE (optional) to get an option to only get the exp if you Killed the mob.

**Comment by kangarko** [comment]
You will need to put your arenas on a separate world and use spigot.yml world config to disable item merging there.
