### ISSUE TITLE
1.18.2 : Quitting the server in Arena will lose all experience

### ISSUE THREAD

**Issue by Jerry-JR** [kangarko/CoreArena#472]
Joining Arena will overwrite the player's original experience
Exiting the server will permanently lose the original experience
Please fix this bug or add an option to disable experience override

**Comment by kangarko** [comment]
Cannot reproduce on the default arena file. Do you have the Allow_Own_Equipment flag on true or false?

**Comment by Jerry-JR** [comment]
> Cannot reproduce on the default arena file. Do you have the Allow_Own_Equipment flag on true or false?

Allow_Own_Equipment is true

**Comment by kangarko** [comment]
I am sorry, having a look today-tomorrow.

**Comment by kangarko** [comment]
Thank you, I have fixed that! A new version will appear tonight.
