### ISSUE TITLE
An option that allows multipliers for mobs

### ISSUE THREAD

**Issue by Baktus79** [kangarko/CoreArena#477]
I have a suggestion to add a multiplier on the number of spawning mobs. Let's say there are 2 players playing and a spawn point is set to spawn 10 mobs. So far so good, but if 4 players play together, 10 mobs might be too little.

My proposal is that I should be able to set a multiplier on the number of extra players who join.

```yaml
multiplier:
  enable: true
  multiply: 0.25
```

With the example above, 4 players would spawn 20 mobs instead of 10. `(10 mobs x 0.25) x 4 players = 10 extra mobs`

---

### Why do I want this?
I can see that it can quickly become too easy to complete a phase if there are too many players participating in a round, and it can become too difficult to play with few players. With such an option, it is possible to adapt the level of difficulty in relation to how many participants there are.

**Comment by kangarko** [comment]
Thanks, but we aim to simplify already complex Boss plugin right now not add more features, hope you understand.

**Comment by Baktus79** [comment]
Instead, is it possible to add more APIs that make it possible to manipulate these things? In this way, it will still be simplified and easy to use, but allows us more advanced users to create add-ons that manipulate parts of the phases.

**Comment by kangarko** [comment]
Yes, we do have a BossSpawnEvent, I believe this could already be achieved if you are a developer and listen to this event.
