### ISSUE TITLE
Classes gui translation

### ISSUE THREAD

**Issue by Foxtray13** [kangarko/CoreArena#478]
Hello,

I bought the plugin in 2018, I waited so long for a full translation in this plugin, but I see that we still can't translate certain part, especially the class selector gui, could you please add this in the config? 

Thank you.

**Comment by kangarko** [comment]
Yes I can have a look in 24 hours :)

**Comment by kangarko** [comment]
Thanks, in the next version you will be able to completely translate that menu: https://i.imgur.com/pGxcVUF.png
