### ISSUE TITLE
[suggestion] Couple of convenient commands.

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#48]
Addition of /ma tp [arena] (so you dont have to enter the gui to teleport).
Convert /me edit to open the gui if [Classes/Upgrades/Rewards] are specified 
e.g. /ma edit Classes opens up the classes menu. /ma edit would still look for an arena if no 2 argument is specified. /ma edit arena would open up the arenas menu so they can select an arena to edit in the gui.

**Comment by kangarko** [comment]
Hey & thanks.

* /ma tp will be added tonight.
* /ma edit won't, because you can already use /ma menu <class/upgrade/reward/arena> and it will open its menu directly.
