### ISSUE TITLE
Update on the CoreArena development roadmap (my thoughts)

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#480]
### Some thoughts on CoreArena's roadmap
Hi Matej, this is a continuation of our conversation on Discord. 
I was inactive in the Minecraft server realm for quite a while, so I'm picking up where I left off. I had a few requests that I made just before you open sourced CoreArena, [one of which](https://github.com/kangarko/CoreArena/issues/422) you implemented, but I think it was forgotten soon after and I can't tell if it's been implemented / how to use it as it's not documented.

Another one that was really important to me, was the ability to have shops running within an arena for players to spend their XP to get in-game items to help them continue their battle. The interesting thing about this one is there are no features you need to add since this can all be done with other plugins such as ShopGUI+, but sadly CoreArena [prevents this from working](https://github.com/kangarko/CoreArena/issues/381) because it overwrites vanilla XP (CoreArena must be manually keeping track of player XP instead of relying on Vanilla, this is probably because you wanted to retain the players original XP before joining an arena so you can set it back to normal, which makes sense.) 
_As a potential solution_, you could save their XP data before joining the arena, reset their XP to 0, use Vanilla methods to give XP to players, and then reset their XP back to normal after exiting an arena, after giving them their nuggets ofc.
The second thing that would also be required is enabling the usage of Vault as we discussed [here](https://github.com/kangarko/CoreArena/issues/353). I am aware that you can convert nuggets to Vault, but that's also limiting for many other reasons, including in-game shops and other more advanced currency-related features that could be taken advantage of by other plugins like [UltraEconomy](https://www.spigotmc.org/resources/ultra-economy.83374/), allowing for even more arena customisation. 

I'm not trying to overwhelm you here with demands, I do appreciate all of my requests that you have implemented in the past such as the [advanced placeholders](https://github.com/kangarko/CoreArena/issues/365), but these few things seem to really limit what I can achieve with CoreArena. Most of the time I am able to get around limitations by using other software instead of you (the dev) having to reinvent the wheel each time. For example, instead of people making requests for you to implement an in-game shop feature, people could simply use [UltraCustomizer](https://www.spigotmc.org/resources/ultra-customizer.49330/) or [ShopGUI+](https://www.spigotmc.org/resources/shopgui-1-8-1-19.6515/) or any other software to build it themselves. 
There are some other great things mentioned on the [roadmap](https://github.com/kangarko/CoreArena/issues/4) that would be nice, but honestly, most of it can already be accomplished with some complex use of other plugins like WorldGaurd and UltraCustomizer etc. Heres are my thoughts on some of thing things mentioned on the [roadmap](https://github.com/kangarko/CoreArena/issues/4):

- Invite other players to play while in lobby: Already achievable using [MyCommand](https://www.spigotmc.org/resources/mycommand.22272/)
- Apply glowing effect to mobs far away so they are easier to find: Already patched with the [placeholder request](https://github.com/kangarko/CoreArena/issues/373#issuecomment-720178066). (Do you think you could duplicate this for the nearest player as I mentioned [here](https://github.com/kangarko/CoreArena/issues/373#issuecomment-720202079)?)
- Item Creator: No need to reinvent the wheel, use AdvancedEnchants or MMOItems.
- Per-arena join permission: This is already implemented?

And lastly, a not so important but time saving feautre would be to duplicate arenas fully. Just needs to duplicate all the data in the flatfile while changing the world and xyz locations of everything. Could probably hava `/ma duplicate <arena> <newArenaName> <world> <x,y,z>`. The `<x,y,z>` could simply be the x,y,z of the lobby block, and then the coordinates of everything else could be realigned from that using some basic math, for example, xyz distance from lobby block to spawnerBlockOne originally was 3,10,50, so it adds the difference and replaces the coordinates on the duplicated arena. You could even write a script the modifies the flatfile and makes these changes if you didn't want to implement it in the plugin. (Would also need to duplicate the schem files)

Thanks for reading Matej, looking foward to your response.

Cheers,
Leeham

### Discord convo for the record:
Leeham:
> Anyone have any thoughts on how this plug-in compares to MythicDungoens? Doesn’t seem like any new features are being added to CoreArena anymore.

Matej:
> Different visions behind those two plugins, CoreArena has a "start-game-end" mechanics whereas the other one is more on-demand. Our plugin is "finished", unless specific features are needed there's no point in just throwing more code to make it look "fancier".

Leeham:
> Thanks Matej, I’m only asking as I’ve been waiting for quite a while for some of these requests to be implemented. 
> I think you might have already implemented the ‘next phase mode’: both option for going to the next phase if EITHER mobs are killed OR the timer expires, but I can’t see it in the wiki so I’m not sure how to enable it in arena settings. 
> 
> The other links I sent you are some other really important requests we talked about years back, ones such as player XP being out of sync with vanilla XP, making it impossible to make custom player shops in game etc.
> Do you have any thoughts on implementing  these at some stage?
> Cheers

**Comment by kangarko** [comment]
Thanks Leeham, I have added you onto our wikipedia. Feel free to edit it there directly.

Regarding your suggestions, I am happy with you using our product and keeping an eye on what might be very useful. For the last couple of years however I had to deprioritize plugins that were less than 10% of our entire customer base (90% people use Boss and ChatControl) due to lack of time (I am 25 and no longer in high school), so I wont be able to write these code updates. However I am openminded to adding an experienced developer to our source code so he can apply those improvements on an ongoing basis.
