### ISSUE TITLE
Upgrade class GUI

### ISSUE THREAD

**Issue by Foxtray13** [kangarko/CoreArena#481]
Hello,

Please in addition to the class selection update, please make that we can translate the /ma rewards and the class upgrading part.

Thank you.

**Comment by kangarko** [comment]
Thanks, however with the time I have available right now I am unable to further work on translations. I'll ask my friend @ElBananaa would you be so kind and help with this? Should be pretty simple just copy paste the strings into localization/messages_en.yml and call using Lang.of("path.to.string") class
