### ISSUE TITLE
1.19.2: Can you give a class stacked potions?

### ISSUE THREAD

**Issue by Desjimbo** [kangarko/CoreArena#483]
Is there anyway to give a class stacks of potions? I have a potion stacking plugin that allows me to stack potions, but you can't shift + click any items into the class editing section you can only drag and drop which unstacks the potions. I was able to do it with the other mobarena plugin I was using because they allow class chests. I think it would really help if we could just shift + click items into the item editing section when editing a class.

**Comment by kangarko** [comment]
Thanks, right now you need to edit your data.db file and locate Classes.YourClass then find your tier item and edit the Amount key.

<img width="409" alt="Screenshot 2022-11-01 at 17 11 30" src="https://user-images.githubusercontent.com/1918426/199281741-86c11224-7c43-4673-8087-5724593e6113.png">

**Comment by kangarko** [comment]
*You could put 1 potion to the class tier and then edit it to be 64 using data.db while the server is stopped.
