### ISSUE TITLE
Items that spawn pets to fight along with you in the arena. 

### ISSUE THREAD

**Issue by Desjimbo** [kangarko/CoreArena#484]
If you could put certain items in a class that automatically spawn mobs that help you out. Bone = wolf, hay = horse, fish = cat.

1) It would benefit others by giving them more elements of classes. You could create classes with themes revolving around the mobs that spawn with these items. So for you could put 3 bones in a class and each bone would spawn 1 wolf. Then those wolves could help you kill mobs, or hay could spawn a horse to ride on. I think a lot of people would appreciate this change. 

2) My server would be affected if you don't add this suggestion because I was previously using the free mobarena plugin that allows pets like horses, wolves, cats, etc. And created classes that are highly reliant on these features such as my howler class that spawns pet wolves to fight alongside you. A Horseman class that lets a player ride around on a horse, etc.

**Comment by kangarko** [comment]
Thank you! Right now that is doable using our API so that if you have a developer he can code these smaller features as much as you desire :) Going to place this to roadmap tho
