### ISSUE TITLE
Give players rewards based on round they achieved

### ISSUE THREAD

**Issue by Desjimbo** [kangarko/CoreArena#485]
I'm editing the arena config right now and in the rewards section it seems like it only has the option to reward players with items to be used in the arena after completing a certain amount of waves. Is there any way to set it so these rewards are given to the player after the arena has concluded. So for example if they make it to wave 5 and the reward for that is 1 diamond, they would receive 1 diamond after the arena is finished. 

1) I think this would benefit others by improving the rewards system and allowing you to directly reward a player with exactly what you want them to receive based on how well they performed rather than just giving them nuggets which they can trade for money. 

2) My server would be affected if this isn't added because I already have rewards set up for up to 100 waves from a previous mobarena plugin.

**Comment by kangarko** [comment]
Thank you. The logic right now is that players get points, the more rounds they survive and the more mobs the kill, the more points they earn.

So can players trade these points to get items you specific. I recommend you consider using /arena item > the Gold item which you can then convert into your economy plugin and use more advanced reward system from it.
