### ISSUE TITLE
1.19.2 Could not pass event EntityDeathEvent to CoreArena v3.3.7

### ISSUE THREAD

**Issue by R3voolt** [kangarko/CoreArena#487]
Dunno when this started to happen because in the moment i created the arenas everething was working perfectly !
Now in the moment i join an arena , arena mobs will drop normal loot (instead of xp) and throw an error in the console !

Here is the error that i get in console in the moment i kill an mob :  https://pastebin.com/0dud02NM
There is no errors on startup log at all , everething load fine!

**Comment by R3voolt** [comment]
https://gyazo.com/ab802c14c49c3aca63535e325be14a2d

**Comment by kangarko** [comment]
Try the next version with this build:

https://mythiccraft.io/images/download_free.png

![2022-12-18-09 04-183](https://user-images.githubusercontent.com/1918426/208287759-a09e98b9-36fb-450d-972b-325d686f73ad.png)
