### ISSUE TITLE
1.19.3: Lands issue API is updated

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/CoreArena#489]
Hello so Lands wanted me to give you this:

[Lands]: Nag author(s) of plugin CoreArena. It uses the deprecated LandsIntegration of Lands: https://github.com/Angeschossen/LandsAPI/wiki/API-Update

lol I thought that was funny.

**Comment by kangarko** [comment]
Thanks, gonna fix in the next version.
