### ISSUE TITLE
1.19.4:Arena has been stopped for safety

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/CoreArena#490]
I have found that all the arenas setup on my server after updating to paper 1.19.4 they don't work now and give an error.

error:
https://pastebin.com/2sbRYKNX

There is no startup error when starting the server.

**Comment by Michael-A-Sloan** [comment]
The newest in available at the moment. Best Michael SloanOn Mar 28, 2023, at 01:30, Matej Pacan ***@***.***> wrote:﻿
Which CMI version are you running?

**Comment by kangarko** [comment]
Thanks, for now stay on 9.3.x if possible. I will update all plugins when I get home in 48 hours or less.
