### ISSUE TITLE
1.20.1 changing to Store_Inventories: false no one can join arena

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#496]
https://mclo.gs/fmiLwW1
error i get when I change store inventories from true to false. I have to change this because players are losing their inventories in multiple situations when leaving mob arena back to the real world. I have had to disable the plugin on my server entirely temporarily for now.

Ex:
Hi i was playing mob arena and logged out, then logged back in today and all my stuff is gone.

So once the store inventories is set to false, no one can join, the error spits when trying to join, and nothing happens in game.

**Comment by kangarko** [comment]
That will be fixed tonight.
