### ISSUE TITLE
Experience does not stay. (gear too but i have playerinv off so lets focus on EXP)

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#497]
Hello, recently I had  to disable player inventories because in certain cases, players inventories would be gone when returning to the game...  annoying and not usable like this, so i made it player inventory has to be empty to join.

Its great however.. now i have to deal with EXP being lost when players join. So everyone who wants to play mob arena might lose their exp for playing. And I have to roll it back manually.

Theres just been alot of issues with stuff dissapearing outside of mob arena after leaving mob arena in general. Please help.

**Comment by kangarko** [comment]
Please send me your /corearena debug

**Comment by sennby** [comment]
thats an invalid command

**Comment by kangarko** [comment]
You are right, I am sorry - I just added the command: https://builtbybit.com/resources/corearena-physical-engine-mob-arenas.21643/updates

**Comment by kangarko** [comment]
I told you to open a ticket at theirs or open a secondary account a long time ago, sorry. Just email me for now from the old email and I'll send you the jar.
