### ISSUE TITLE
[1.20] Leaving arena adds total health to player

### ISSUE THREAD

**Issue by Osanchez** [kangarko/CoreArena#498]
I am trying to use core arena, everything seems to be working just fine but when players leave the arena they are given permanent health.

the only error I see in the logs 

https://pastes.dev/XIkMhZJKZP

**Comment by kangarko** [comment]
Unfortunately CMI has updated but their API hook is outdated. Are you able to contact me at matej@mineacademy.org for assistance?

**Comment by Osanchez** [comment]
@kangarko , I emailed you. i'm not sure what this issue is, have you confirmed that this is the reason why player health is being modified. If so, this is pretty game breaking. Seeing as CMI is closed source, I think the next step is to either update coreArena with a workaround for this, or make Zrips update their API hook. seeing as they have about 359 open issues on their github, the course of action I seek is that you provide a workaround. 

would you ever consider making coreArena open source to premium users.

**Comment by kangarko** [comment]
I'll provide an updated integration to CoreArena. Sure, if you are a developer and can sign a basic NDA I can give you source code if you have the time to help. But CMI hook is very easy, I can do this in a few days.
