### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by kipenkipen** [kangarko/CoreArena#499]
Placeholders dont work anymore?

**Comment by kangarko** [comment]
Can you please be more specific? How to reproduce + examples.

**Comment by kipenkipen** [comment]
![image](https://github.com/kangarko/CoreArena/assets/8447233/e047ef53-056b-4838-9255-99a79c0ebf9b)

**Comment by kipenkipen** [comment]
o and can i still use the 50% discount bonus what i got from corearena? 
I bought it yesterday

**Comment by kipenkipen** [comment]
i have placeholder api and the nuggits work.
But the other placeholders dont do anything. even if im in a arena.

**Comment by kangarko** [comment]
Thanks, will be fixed.
