### ISSUE TITLE
External DB server MySQL timeout issue

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/CoreArena#5]
spigot 1.12

(Latest version of coreareanand Chatcontrol - always)

Hi, we get quite a few timeouts with our external MySQL database (patebin below), we also get these with chatcontrol when players join/leave, if the server has been quiet. 

 I'm wary it may not save the relevant data after a timeout,once we have it fully up and running. We have a large number of plugins using our external MySQL , but most play nicely with it :)

Thanks

https://pastebin.com/jFruVjm6

**Comment by kangarko** [comment]
Hey,

I am sorry you have issues. Please look up whether you have "autoReconnect=true" in your settings.yml files for both plugins. Eventually I'd recommend asking your hosting provider for an advice, as honestly I've never received a complaint like this.

**Comment by frizzbee30** [comment]
Thanks, we've been through our server and external db server hosts, who can't find any issues, we do have some plugins that play fine, some that don't.

One dev is looking at  Connection#isValid() as an option, I don't know what you think about that as a potential solution?  I'm presuming most servers are constantly busy if they use external MySQL, although we have been around quite a long time (4 years plus) we do have periods with no players on, which obviously times out the connection. Most I presume just use a local db if they use MySQL or sqlite   :)

**Comment by kangarko** [comment]
Hey,

brilliant suggestion with the isValid() method (only if I haven't delayed your issue, I am sorry!) I will use it right away :) I have also added more meaningful error messages, with that they are logged into the error.log file so if anything appears again you can just paste the content from that file directly.

Please test out the latest version.

**Comment by frizzbee30** [comment]
Thanks, no worries. I'm probably totally wide of the mark, but I have noticed across all of our plugins that use external MySQL, a degradation in connection performance with the later builds of spigot.

 In fact I've driven our db host and server host nut's with request tickets. We always had plugins 'grumbling' about timeout connections, but in a very minor way. Now we have wholesale mutiny with even our most well behaved ones.

I have  tried running locally out of test, and an alternate db host (for testing) to try and pin down a cause, exactly the same result.

So anything you can do is really appreciated!!  :D

**Comment by kangarko** [comment]
Hello,

so if I understand correctly, you experience the same error as you've posted above in CoreArena (and other of my plugins) even on the latest version (from yesterday) ? I have of course done testing myself, sadly (or happily) without running into any issues, but I guess the time frame was too short (cca. 30mins).

**Comment by frizzbee30** [comment]
Hi, we run quite a number of plugins from external MySQL, some do have issues, others seem to cope. Prior to the last few  spigot builds it was really only around 3 or 4 that had a re-connection issue, now it's more. 
A typical example being logblock, which would never complain, but does now any time a player joins if the server has been quiet (but does re establish successfully) However it is muddied as a new version of logblock was released at the same time :)

Chatcontrol always 'grumbled' if the server had been quiet and MySQL was enabled (didnt always use the MySQl option), obviously core arena is a new addition to I can't comment. However it does still seem unhappy with the connection if the server has been quiet.

I can provide the login to an external db host if you need, as it's obviously easy enough to set up another db and account

Thanks for investigating!

**Comment by kangarko** [comment]
Hey, I will get back to you on Monday the 7th and verify that the new code with the auto-connect feature has been included into both CoreArena and ChatControl.

**Comment by frizzbee30** [comment]
Thanks  :)

**Comment by kangarko** [comment]
Hey, I am sorry for the delay. Please try testing against CoreArena 1.2.7 and let me know how it goes :)

**Comment by frizzbee30** [comment]
Hi, there, thanks for looking into it. Still throwing a 'wobbler' I'm afraid. I've attached th elogs, fromt he main server one you will see a few plugins grumble but reconnect, there's no confirmation from corearena/chatcontrol that has happened? i haven't had chance to do a data save test yet. There was a similar issue with https://www.spigotmc.org/resources/restrictedcreative.42790/ but the dev managed to fix it and works great now.


main log

https://pastebin.com/dyjkQs5v


corearena log

https://pastebin.com/8NufmaTb


Again, thanks for looking into it, really appreciated!  :D

**Comment by kangarko** [comment]
Hey,

I have adjusted the code again, this time it will re-connect once before throwing an error. If the reconnection fails, the error is shown. 

Please test :)

**Comment by frizzbee30** [comment]
Thanks, will do  :)

**Comment by frizzbee30** [comment]
Hi, still does lot's of 'grumbling' in console, but it does seem to store player data in the tables though.

https://pastebin.com/hFBtPejr


Thanks

**Comment by kangarko** [comment]
Hey,

I cannot track that error down, are you on the latest version? Also, it just got updated again so I recommend you test it out :)

**Comment by frizzbee30** [comment]
Hi, the very latest version appears ok, need to test more.

Looks mainly like chatcontrol doing the groaning, as opposed to the two  :)

Thanks

**Comment by kangarko** [comment]
Hey & thanks for letting me know!

ChatControl and CoreArena share the same library, which is the one handling MySQL database. The underlying code is just the same. I apology for stupid question, but do you have the very latest ChatControl Pro as well? :) Just need to know because the relevant code has been updated many times through-out the development cycle.

**Comment by frizzbee30** [comment]
Hi, I always run the latest builds, it may still have some connection issues and I just haven't tested enough. It was just something I noticed :)

**Comment by kangarko** [comment]
Hey, I understand. I apology for the situation. I try to make some "special sauce" for your server so it works even when the connection needs to be restored. I'll let you know when it's done, should be 2-3 days.

**Comment by frizzbee30** [comment]
Thanks, much appreciated!  :)

**Comment by kangarko** [comment]
Houps totally forgot about that during Boss launch (a new plugin).

Sorry! I am putting this in my calendar to be solved quickly this time.

**Comment by kangarko** [comment]
Closing since we're discussing it via PM. Please just PM me if it occurs again.
