### ISSUE TITLE
Request: Own command instead of Nuggets

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/CoreArena#50]
Instead of your Nugget system can we have the option to run a command when the nuggets are saved with the variable for the nugget value {nugget} or something, so then we can use any Token/Eco system we please. 

I want to use one of the Many token systems that work with BossShop, this way we have a reliable way to have tokens be used Cross-Server with the full power of BossShop, and this should hopefully fix all the issues with your nugget system not Loading/Giving Nuggets, The cross server compatibility with nuggets etc. I have also never Liked the word "Nugget" Just too many bad connotations with it https://www.urbandictionary.com/define.php?term=nugget

Another alternative is to support all the "points" systems that BossShop does, and also making BossShop compatibility https://www.spigotmc.org/resources/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin.25699/

**Comment by kangarko** [comment]
Hello, thank you for that suggestion, this can be done. I am leaving this open for the future.

**Comment by kangarko** [comment]
We are not planning to include this feature due to works on other priorities.

**Comment by FrozenBeard** [comment]
Tokenmanager has an easy to use API, just support that.
https://www.spigotmc.org/resources/tokenmanager.8610/

**Comment by kangarko** [comment]
As mentioned, I will be closing down majority of suggestions until further notice. Few features will get implemented but not this one.
