### ISSUE TITLE
1.20.1 Airstrike and exposive bow.

### ISSUE THREAD

**Issue by kipenkipen** [kangarko/CoreArena#500]
Arena blocks still breaks with the airstrike and the explosive bow.

Sea added video for what i mean.
Is here any fix for? 

https://medal.tv/games/minecraft/clips/1jX9fO3HQCgZUV/d1337SVIEZ0h?invite=cr-MSx6Z1ksMjIyMDgwMDgs

^^^^Video

Also a screenshot of what my scematic looks when total broken (Just a test arena)

![366d91ca-52d7-4598-bbb5-643240e40442](https://github.com/kangarko/CoreArena/assets/8447233/6f1732e7-c90e-464e-9197-1ff97295d990)

**Comment by kangarko** [comment]
You would need to expand the arena region and add a safety buffer.

**Comment by kipenkipen** [comment]
? The bomb explodes  in the safe zone?

**Comment by kangarko** [comment]
That is intended, there is no "safe zone" marking as of right now. I might add this later on to the plugin. But for now I recommend replacing the spawn points with bedrock or any other durable block.

**Comment by kipenkipen** [comment]
but it wil still destroy the signs? thath is the problem haha

**Comment by kangarko** [comment]
That is a feature, I did not think people would care to save signs when the arena is damaged. I can look into adding a setting to prevent this when I have more time
