### ISSUE TITLE
1.20.1 AdvancedEnchantments with CoreArena

### ISSUE THREAD

**Issue by cobrex1** [kangarko/CoreArena#501]
I have the plugin Advanced Enchantments (version 9.3.13) on the server as well as CoreArena (version 3.5.5).

It appears that the arena is messing with the enchantments and not allowing them to activate or activates them incorrectly. When used outside of the arena they work as expected.

For example the Guardian enchantment spawns a Mob (Iron Golem) to protect them, but they end up attacking the player once the mob they triggered is killed. Also it appears that the Arena then counts the guardian as a mob and will not complete the phase until they are also killed..

Happy to provide more information if needed.

**Comment by kangarko** [comment]
Hey cobrex,

If you have a moment, could you please ask that developer whether or not he marks the entity with a custom metadata? I will add a check to ignore the mob completely if he is marked in CoreArena.

I have messaged you on Discord also.

Matej

**Comment by cobrex1** [comment]
Just looking through and it appears that the Guards that are spawned do have their own metadata

**Comment by cobrex1** [comment]
I am still trying to get a response from the dev on the matadata key

**Comment by kangarko** [comment]
Let's follow up here: https://github.com/GC-spigot/AdvancedEnchantments/issues/3626

**Comment by kangarko** [comment]
Guardians should be fixed in the next release!
