### ISSUE TITLE
Arena sometimes gets stuck on phases`

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#502]
Hi, i have the latest corearena, and latest boss, latest paper 1.20.1.

I created a dungeon using boss/corearena, however it will sometiems get stuck, and at no rhyme or reason.

The setup is as follows:

A big map where players progress through waves of mobs, boss is used for all of the mobs that spawn.
Kill all the mobs, move to the next phase.
I have 25 total phases or checkpoints as i call them for players playing the arena.

I will kill all the mobs in the arena for the phase, and then poof it will randomly get stuck on a phase, usually it gets out of the stuck and eventually continues, others not. Right now for example i am on phase 18/25 and stuck, its a ruined dungeon because of this. Alot of resources and work is put into getting this far into the dungeons as well to make this worst.

Please fix this.

**Comment by kangarko** [comment]
Thanks for reporting, I understand it must be frustrating.

Just to clarify what you do you mean by "stuck"? The boss bar timer stops counting down mid-way?

**Comment by sennby** [comment]
it stayed on phase 18, with no monsters spawned to kill, for the remainder of the timer of the dungeon. Phase 18 mobs spawned, i killed them, and i couldnt go past 18.

Run it back and it might stop at 14, 12, 24, who knows, might go through it completely no issues, unpredictable. Sometimes the pause is like 2 minutes then it advances.

**Comment by kangarko** [comment]
Try setting your Next_Phase_Mode key in arena yml file to "timer", because if you have it on "monsters" then we will not advance phase unless all mobs are killed which might be happening

**Comment by sennby** [comment]
That is not what is happening, i kill all mobs. I checked in spectator all around for 5 minutes for any mobs anywhere else. I have it so its used as a progressive dungeon with checkpoints. Timer is not an option for this.

**Comment by kangarko** [comment]
No problem. Please use the next version I put up in an hour. Can you set Debug key in settings.yml to [next-phase] there? When it gets stuck please let me know what console says, there should be a message "monsters alive" and print each mob that is alive.

**Comment by sennby** [comment]
Just confirmed this is still happening on more than a couple occasions, and I went spectator and flew around to confirm there were no mobs. I also want to say that it is 100% random on which round. I had it happen on round 10, round 24, round 25, etc.

I am now putting the debug key in.

**Comment by sennby** [comment]
It pauses for like 20sec-2mins every so often, more often than breaking entirely, then resumes for no reason. But im waiting til i see a full break in the rounds and for it to not advance at all for a debug.

**Comment by sennby** [comment]
finally i may have found the cause. A random enderman warped into my arena, i found him running around and killed him. I changed worldguard flags to not allow stuff like this. Will update if it happens still.

**Comment by kangarko** [comment]
Thank you very much for keeping me updated and I apology for the delay. Closing this, but let me know when that happens again.

**Comment by sennby** [comment]
[debug.zip](https://github.com/kangarko/CoreArena/files/13506500/debug.zip)
happened again.
I even did mobkill all on the world etc etc.
