### ISSUE TITLE
1.19.2 - 3.5.5: 1.19.2 Server Why does the plugin delete the entire data.db document? 

### ISSUE THREAD

**Issue by Rasowks** [kangarko/CoreArena#503]
Good afternoon, I have the pleasure of trying both of your plugins from chatcontrol to corearena, which are great complements for my clients' servers, but I am having a strong problem with corearena, once I finish configuring an arena for several days. Sometimes very randomly the data.db file deletes all its information and I must then ask the host administrators for a backup of the previous day to recover the progress by losing a day of work in what is ready, could I know what causes this mistake?

**Comment by kangarko** [comment]
Hello,

I assume the data.db is wiped on server startup? Is there any error in the console at that time?

**Comment by Rasowks** [comment]
Hi,

I think the same, but it happens so randomly and in console usually nothing appears, the only thing is that one realizes that I delete the information because it happens to say to have the arena and the amount of upgrades reloading to say that 0 arenas and 0 upgrades have been loaded, like now that I am waiting for the backup as soon as I have it I will make a second backup on machine to document if an error comes out in console, one thing to mention is that I am usually working in the settings file just before doing the reload, could it have to do? a failure in settings causes the wipe of the data.db?

**Comment by kangarko** [comment]
Thanks, please send me anything when you get it.

I strongly advise against editing settings.yml and uploading via FTP on a running server, in rare cases it might happen but you are the second since the last year or two raising this problem so I suspect it might be somewhere else. Try to stop the server, then upload the edited files and start it again to be sure.

**Comment by Rasowks** [comment]
Very good matej, is the second time this error occurs, this time I was editing the classes and the prices of each of them and doing a simple reload lost all the progress of the arena, is the second time I have to make a backup losing a day of work, I really need some help, in console no message came out, the only message that came out is the reload but already updated with the lost progress.

**Comment by kangarko** [comment]
I am sorry for the issue. The data.db was accessed from multiple locations, I rewrote the system. Plus I added automatic backups of that file. You can try the new version and set Backup.Aggressive to true to get backups on each arena edit so you are 100% safe.
