### ISSUE TITLE
Bedrock shop dupe 1.20.2

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#504]
I have signs that have the [rewards]
a bedrock player can go into the rewards shop, and buy stuff non stop with no nuggets.
I cannot do it on java, however he is a bedrock player and can do it no issue.

**Comment by kangarko** [comment]
Hey!

Unfortunately I have no idea what is causing this issue since you are using some third party solution to let Bedrock players connect onto a Spigot server. This is natively unsupported and as a hobby developer I can't debug this in my free time I have for this plugin. Sorry.

Matej
