### ISSUE TITLE
chest refill questions

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#507]
I have been using this plugin pretty heavily for new dungeons and mob arenas on my server recently with different settings and themes.

My current issue is with the chest refills on my new dungeon.

I put gapps and totems in this chest and i have  a optional parkour path where they can parkour and get the chest contents.

HOWEVER, my issue is players can join the dungeon, and head straight to tht parkour, get the gapps and totems, leave, and repeat for a ton of these items outside the arena. This dungeon is bring your own gear out and leave with the drops of the bosses.

Is there anything i can do for this? Or do i have to get rid of these chests entirely because of this?

the intended use is fight 2 waves of mobs then a boss, then 2 more waves then a boss then you are at the optional parkour way or continue dungeon way. I want players to get the chest after they finish the 2 bosses, not before.

ALSO

how can i make it so people cant elytra in a dungeon? is it possible or do i need outside plugin.

**Comment by kangarko** [comment]
Hey sennby,

I would suggest you build the map such that the chest is not physically accessible (be sure to keep it at least 5 blocks from the players) unless they reach a certain checkpoint or a destination. 

You can use our [power sign system](https://github.com/kangarko/CoreArena/wiki/Signs#power-sign) to "move away" some pistons to unlock the hidden door after the waves of bosses are fought by setting the Next_Phase_Mode key to "monsters" in your arena file.

Next, use WorldEdit and capture the initial/destroyed (this can be the same) snapshot of the arena, such that the doors autoclose when arena is done playing and the map is restored.

Let me know if you got any more questions!
