### ISSUE TITLE
1.20.4 Error while spawning mobs Eggmanager

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#509]
https://mclo.gs/LJSihHw

**Comment by sennby** [comment]
https://mclo.gs/WbuF7Wc additional
I downgraded mm to stable, and also updated corearena, still not luck.
CoreArena is effectively 100% broken for me as of right now, and its a BIG part of my server.

**Comment by kangarko** [comment]
Thanks. Looks like MythicMobs has updated and broken its API. I will update in 1h
