### ISSUE TITLE
1.20.4 - STILL HAPPENING - INVENTORY/GEAR LOSS

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#510]
I have a mobarena called village.. You use a kit in there and upon leaving/losing/winning you get tpd back to where u were and are supposed to have the gear you joined with. I made a github for this a few times and expected it to be fixed but it just occured again while i was watching a player.

Player had a inventory and gear on join of the mob arena
player sat in lobby and then left the lobby
everything the player had is now completely gone.

This doesnt occur when i run the mobarena with no kits and player brings gear in.
This is strictly for kits/player doesnt bring gear in.

**Comment by kangarko** [comment]
I apologize for the continued plugins. Can you please drop your /ma debug file once again?

**Comment by sennby** [comment]
This is happening on my server with no inventory management plguin (my ls has mv-inventories) for per world invents.
This server doesnt have anything like that which makes me think this is corearenas issue.
https://www.mediafire.com/file/2ul7f66r7tht6ct/debug.zip/file

**Comment by kangarko** [comment]
Sorry for delays, I improved the system internally. Please set your Debug option in settings.yml to [inventory].

You should start seeing console log messages like these

![a](https://i.imgur.com/kVpjrv1.png)

It should not happen, but just in case it does let me know what the console said.

Thanks, appreciated your patience. A new update will be shipped tonight.
