### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#512]
corearena seems tosaves playerdata and loads playerdata not async so joining and leaving does file saving operation and while that operation is being done, server momentary stops cause file saving is a thread blocking task. Is it possible for you to make the file saving and loading on player join and leave async instead of tied to the server thread?

Or even make it possible to turn saving off entirely, i dont use it personally. I dont use any of the nuggets kits or anything like that other than save inventory so players dont lose their stuff in the dungeons. Running into performance issues with corearena and hoping to find a fix rather than moving.

Also i dont use procedural damage, schematics reloading or anything of that either.

**Comment by kangarko** [comment]
We already load mysql data async. Mind providing a spark report or anything else I can have a look?

**Comment by sennby** [comment]
https://spark.lucko.me/qalBPR4VoM

**Comment by sennby** [comment]
https://spark.lucko.me/bBOoe6fT3z

**Comment by kangarko** [comment]
I will reduce the save calls to when the server is stopped or restarted, it should be enough. Thank you.
