### ISSUE TITLE
1.20.4: Issue with spawn point handling

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/CoreArena#515]
was trying to setup mob spawn point and after adding 1 egg into it closed the GUI, it says the iron block is no longer spawn point so its messing it up
](https://ptero.co/ivucoveguc.properties)

**Comment by Rexmen1** [comment]
https://gyazo.com/fc01ee03dfdee535d1b756e141ec3ce3

**Comment by kangarko** [comment]
Thanks, fixed.
