### ISSUE TITLE
Placeholder for if players are currently waiting in a lobby to start playing.

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#518]
While I can't think of many use cases for why someone might need this, I'm not very imaginative and it just seems like this should be in there by default. I'm sure more people than just me would use it if was included.

Edit: It also seems like a placeholder to represent how long until a game starts if players are currently in a lobby would be very useful.

**Comment by kangarko** [comment]
You can use `{<arenaname>_state}` to see if the arena is in the lobby state. 

In the next version I will add `{<arenaname>_remaining_lobby}`, thanks.

**Comment by zylstra1313** [comment]
I was intending if a player is currently in a lobby, rather than if an arena is in a lobby state.
Example: {player_in_lobby} true/false
This would make it easy to assign permissions to players only in a lobby.

**Comment by kangarko** [comment]
Added "{is_in_lobby}" placeholder.
