### ISSUE TITLE
Mini Spawners and Boss

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#52]
Hello Everybody! C:

I was thinking of some sort of Spawner Who has life as a boss and practically when you create it you can place it in setup mode and players will have that goal to destroy every spawner, and every time the energy goes down, stronger monsters come out. When it is destroyed it makes the animation explosive, and as soon as all the spawners are destroyed in the center, the boss appeares, the central spawner will be an obsidian block, and the others of GoldBlock that connected power the boss, and then unleashes the power that is accumulated from these Spawners, the more time is lost to Destroying the Spawners and the Boss becomes stronger. He will be invincible as long as the core is not destroyed, so he does not take damage and as soon as he destroys the core he will make a random flash effect, and he does random critical damage. 

N.B: I forgot, The hordes are endless as long as every spawner is not reset to Life.

Good Bye c:

**Comment by kangarko** [comment]
Thank you for your suggestion! I am sorry I am not planning to add it in the near future because I don't have much extra time for big new features, but I am leaving this open for the future as it sounds good and exciting.

**Comment by BlackGamer000** [comment]
Okay Thanks :D
