### ISSUE TITLE
Sometimes players log in with an empty inventory after logging out inside an arena. 1.20.2

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#520]
Sometimes when players log out inside an arena they log back in with their inventory wiped. No errors appear in the console and it only happens very rarely. I can't replicate it nor do I have any idea what causes it.

**Comment by kangarko** [comment]
Will most likely happy after the plugin or server is reloaded. We do not store inventories in a player file for now, but that is something I can consider adding later.

**Comment by zylstra1313** [comment]
This seems like a huge issue considering that if you have a server that restarts regularly any player that logs out inside and then doesn't log back in for a while will have their inventory cleared.

**Comment by kangarko** [comment]
Do you type /stop when the server restarts? How is the restart? CoreArena should kick players and restore inventories before the restart

**Comment by zylstra1313** [comment]
I found two situations where it occurs. If a player is in an arena and the server is /stopped their inventory will be empty when they log in next after the restart. The other situation occurs when the player is in an arena and disconnects from the server. If the server is restarted before they log back in their inventory will be empty when they return.

**Comment by kangarko** [comment]
I've implemented support for offline inventory store to the next release. Please consider giving the plugin a rating or rating us at trustpilot, as it took some time to do.

**Comment by zylstra1313** [comment]
I shall sing your praises to all that will listen.
