### ISSUE TITLE
1.21: Lag in report, and tps is low on server

### ISSUE THREAD

**Issue by Rexmen1** [kangarko/CoreArena#522]
![image](https://github.com/user-attachments/assets/16f2fcd7-cf50-4974-a6e6-89ebceddd7e9)
Server is lagging and when doing spark report this is showing most of the lag coming from arena plugin. not all of the but 10-15% so going through all plugins optimization to get this fixed, If you can help me tune that will be great help

**Comment by Rexmen1** [comment]
hmmm but im not even touching mob arenas, they are not being setup for last 2-3 days

**Comment by kangarko** [comment]
Please provide me a clickable link to the spark report
