### ISSUE TITLE
Arena placeholders don't parse in non-reward commands executed by the arena.

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#523]
Basically title, for some reason the arena placeholders with variables don't seem to parse in non-reward commands in the arena. To replicate attempt to use placeholders with variables in non-reward commands.

**Comment by kangarko** [comment]
Please send your .yml file and tell me which command please just to make sure I understand it right

**Comment by zylstra1313** [comment]
I was testing this more today and have no idea what I was doing wrong the first time. It seems to work as expected for me now.
