### ISSUE TITLE
Ability to execute reward commands when a wave is completed instead of at the beginning.

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#524]
Basically title:
It's a little weird that there's not an easy way to give players rewards for completing the final wave of an arena without doing something janky.

**Comment by kangarko** [comment]
Ok I added "Last_Phase" command set to arena yml file. If your file doesnt get updated just write it there below Phase key in commands section.

It will fire at the last phase before the arena ends:

![a](https://i.imgur.com/v0kDzFx.png)
