### ISSUE TITLE
Option to automatically give players the xp of mobs they kill instead of dropping xp on the ground

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#525]
Basically title, a config option to automatically give players the xp from mobs they kill instead of dropping it onto the ground.
In my arena players are choosing non-ranged classes specifically because they don't get nearly as much xp as when they play a melee class because players that use melee classes pick it up before they can.

**Comment by kangarko** [comment]
Gotcha, can look into it by end of the week

**Comment by kangarko** [comment]
I added Experience.Give_To_Killer option in settings.yml (defaults to false). If true, we give the arena exp directly to the last damage cause of a killed mob, instead of dropping it as a collectible item.
