### ISSUE TITLE
Add {corearena_current_player_X_level} Placeholder that displays depending on what arena the player is in.

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#526]
The placeholder "{corearena_ARENA_player_X_level}" is sort of inconvenient to use in things like scoreboards for spectators because you have to make a new scoreboard/line for each different arena. It would be much easier to use if there was a placeholder like "{corearena_current_player_X_level}" that checks what arena the player reading it is in. I think this would make all of the variable placeholders a lot easier to use.

**Comment by zylstra1313** [comment]
Had to totally change this due to a huge oversight when I originally wrote it

**Comment by kangarko** [comment]
Already supported, use corearena_**player** instead of giving the arena name. I will update GitHub wiki, thanks.

**Comment by zylstra1313** [comment]
I think I may have explained the feature request wrong, I wish for there to be a placeholder that applies to whatever arena you're in whether you are playing or not. I want to make a spectator mode for some of my arenas.

**Comment by kangarko** [comment]
I will add it: "current"! I updated the wiki already: https://github.com/kangarko/CoreArena/wiki/PlaceholderAPI#two-arguments-variables

**Comment by kangarko** [comment]
I meant "location" not "current", thanks for suggesting!
