### ISSUE TITLE
Add placeholder for the final wave a player reached to allow messages like "PlayerX was killed on wave X in the "TestArena"

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#527]
From my tinkering it looks like there's no way to say what wave a player died on if they are the last player alive in an arena. If you try to call {corearena_ARENA_phase} after they die it resets to 1. Maybe you could just make the plugin wait a few seconds after an arena ends so that {corearena_ARENA_phase} can be called before it resets?

**Comment by kangarko** [comment]
Should be somewhat addressed by the Last_Phase command section in the next version of the plugin.
