### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#530]
https://spark.lucko.me/Dm60ntnrVc

1) How it would benefit others? Using CoreArena on a larger server im seeing I might have to start looking at other options in the future. I dont want others to have this issue and want larger servers to be able to use this well.

2) What would happen if we won't implement this feature? How's your server being affected? Lag, large servers will continue steering away.

3) If suggesting something new - Can the old system be modified/improved instead? idk

I dont use anything really either for corearena i dont regen anything. I dont want to use any points or anything. I simply use corearena as progressive "dungeons". where they kill a wave of mobs, move to the next location, sometimes a boss. I handle rewards through mythicmobs when mobs die etc.

**Comment by kangarko** [comment]
Thank you. I appreciate you sending the report.

Looks like something's off with your server, where CoreArena waits for "IAsyncTaskHandler.managedBlock()". Can you ask at paper/spigot discord regarding this? I first recommend using plain Paper since we can't debug in forks, but the offending calls are outside of CoreArena's code regardless.

Hope that explained things a bit!

Matej

**Comment by sennby** [comment]
Thanks for the input, heres info i was given:

i mean there is something which he doesnt understand
retrieving all entities within chunks is a heavy call as he is accessing the chunk on main thread
the chunk is being retrieved which causes the spike
[12:25 PM]
he needs to alter the way of how he tracks entities to remove to avoid this usage

**Comment by kangarko** [comment]
Sorry to hear you received poor support at UniverseSpigot. We only call this once every time an arena start to remove forgotten entities and cleanup. **There is no other sure way to get the entities in a chunk than calling the official Bukkit API**, which appears to be the cause of the lag. CoreArena has been used for 7 years now without a report like this, I strongly recommend trying it out on Paper
