### ISSUE TITLE
"Mob_Burn_On_Sunlight" Doesn't allow fire aspect to light mobs on fire

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/CoreArena#531]
If set to true "Mob_Burn_On_Sunlight" doesn't allow fire aspect to light mobs on fire.

**Comment by kangarko** [comment]
Low priority issue, will fix later when I have more time.

**Comment by zylstra1313** [comment]
I did discover that this isn't a real bug and it was caused by me using boss which disables burning in sunlight by default for undead bosses
