### ISSUE TITLE
1.21.1: Endless Game

### ISSUE THREAD

**Issue by Raff120** [kangarko/CoreArena#537]
Hello, I'm using CoreArena for version 1.21.1 and I'm experiencing the following issue. I've set the maximum game duration to 30 minutes and the maximum phase to 2 (a low value for testing), but when we reach phase 2, even if I've killed all the mobs, the game remains active and stuck, with the only way out being to exit the match. How can I fix this? Also, could you explain exactly how to win the game in general?
[CoreArena.zip](https://github.com/user-attachments/files/17292727/CoreArena.zip)

**Comment by kangarko** [comment]
Please try the next version released tonight thank you!
