### ISSUE TITLE
1.21.1 instantly ending rounds

### ISSUE THREAD

**Issue by sennby** [kangarko/CoreArena#538]
![{8AC2C67F-CB90-4A58-9816-0C337F1973E9}](https://github.com/user-attachments/assets/9f18f8d7-91a5-437c-968c-420349f70491)

Since updating to 1.21.1 my "dungeons" dont end when mobs are dead now. they end instantly, so the dungeons get joined, and all rounds run through instantly, all mobs are still there and spawn properly, but the dungeon cant be done because of the instant rounds and the dungeon ending when done.

**Comment by kangarko** [comment]
Can you please send me the arena .yml file? Just that one.

**Comment by sennby** [comment]
> Can you please send me the arena .yml file? Just that one.

https://mclo.gs/UQHoLvl
- all mobs are using meg/mythicmobs.

**Comment by kangarko** [comment]
Let me get back to you in 24 hours

**Comment by kangarko** [comment]
Sorry I cannot reproduce. The next phase is only activated, after I kill the MythicMobs boss. Can you try removing all other plugins except MythicMobs to exclude possible conflicts?

**Comment by sennby** [comment]
Moreso i think this is an issue with it detecting the mobs it uses as they are pigs.
Other ones of my dungeons work with custom mobs but i know these bees use pigs.

**Comment by kangarko** [comment]
Super-strange. Can you test with a Zombie-type or any other more standard mob? I will have time to test with Bees tomorrow.

**Comment by sennby** [comment]
> Super-strange. Can you test with a Zombie-type or any other more standard mob? I will have time to test with Bees tomorrow.

so now.. i cannot even get the arena to start lol. I edited the arena added a couple zombie eggs, re-enabled the arena (its been off on my server bc broke) now it just sends the player to the lobby then keeps them there and the lobby isnt starting. in console i see a arena ended message right after they type the command to join.

**Comment by sennby** [comment]
![image](https://github.com/user-attachments/assets/e57e51ad-72e5-4e11-a10a-0e4729febeef)

So now i just pulled from my 1.20.4 server the beehivedungeon, reloaded.
dungeon was able to start.
When i joined, all of the mythicmobs were spawned it looked like from all the spawners (the bees) along with ONE zombie (it was round 1 or 2) so the zombies were spawning properly. it didnt go past phase 2 since the zombie was alive.

weird part: After about 10 seconds everything in the dungeon died other than the zombie.

**Comment by sennby** [comment]
More testing:

if i sit in the lobby for more than a few seconds the dungeon seems to stop but you remain in the lobby. i can just spawn /dg join BeeHiveDungeon . If i do a /dg start quickly, it starts the dungeon. all bees are spawned, 10 seconds go by then the bees (all the mythicmobs) die.

**Comment by kangarko** [comment]
Might be a third party plugin incompatibility even, can you please upload your /arena debug so I can have a look?

**Comment by sennby** [comment]
I can tell you this exact setup works on my 1.20.4 with just about the same everything minus a few small things like lifesteal vs griefprevention.

[debug.zip](https://github.com/user-attachments/files/17447279/debug.zip)

**Comment by kangarko** [comment]
Turns out Bee class has been internally moved from Creature to Animals. I have added a manual override which should fix that, thank you!

**Comment by sennby** [comment]
Issue still remains.

**Comment by sennby** [comment]
Also the lobby ends after about 15 seconds of existing, so the lobby kills itself.
create lobby
you get tpd to the lobby
10 seconds or so, lobby ends but you stay in where it tpd you. no message or anything. it just stops.

**Comment by sennby** [comment]
-[20:36:58 INFO]: _Senby issued server command: /dg join BeeHiveDungeon
[20:36:58 INFO]: [Essentials] CONSOLE issued server command: /broadcast DUNGEON STARTING!! Enter the BeeHive Dungeon for a thrilling adventure filled with buzzing bosses and swarming monsters! WHERE? [/dungeon join BeeHiveDungeon]
[20:36:59 INFO]: [CoreArena] GG! The game in BeeHiveDungeon has finished!

**Comment by sennby** [comment]
@kangarko ?

where do i go from here??

**Comment by kangarko** [comment]
Sorry, I will addressing this in 24 hours

**Comment by kangarko** [comment]
I can't reproduce the lobby bug, works fine for me on Paper 1.21.1:

![a](https://i.imgur.com/h9M0BY3.png)

Please test on the new update I will push out tonight.

In regards for the phase bug, I figured out it was a confusing setting, I apology for that. Please set Phase.Max_Phase to -1 and keep Arena_End as-is in your arena .yml file, because having both will break the logic.

**Comment by sennby** [comment]
[15:22:38 INFO]: WhoIsSenby issued server command: /dg join BeeHiveDungeon

[15:22:38 INFO]: [Essentials] CONSOLE issued server command: /broadcast DUNGEON STARTING!! Enter the BeeHive Dungeon for a thrilling adventure filled with buzzing bosses and swarming monsters! WHERE? [/dungeon join BeeHiveDungeon]
[15:22:43 INFO]: [CoreArena] GG! The game in BeeHiveDungeon has finished!

**Comment by sennby** [comment]
When i go to this arena and do /dg edit.
Could not find an arena by your location. Despite me just redoing the points.

So i went flying around and foudn i had emerald blocks named as unknown something. so i went and removed teh arena points (there was 3???) redid the points and the issue fixed. So the arena points bugged for some reason on conversion.
I am good now.

**Comment by kangarko** [comment]
Ooh super strange. So it's all good now? If it should happen more, you can - if possible - just send me the server with the map (in private works too) and if I have time I can try reproducing 1:1.

You can also see the data.db file open it with a text editor and see if anything suspicious is stored there.

**Comment by sennby** [comment]
Okay so i started thedungeon. it went STRAIGHT to round 5 (the final round, eg the boss round).

All mobs ppretty much were dead on 1-4 and 5 stayed the rest didnt. (bees)
But the same mobs were spawned in 5 and stayed alive.

**Comment by sennby** [comment]
You can add me on discord: senby8

**Comment by kangarko** [comment]
I am leaving office for the weekend, please send me the environment in private via email at matej@mineacademy.org

**Comment by kangarko** [comment]
Hey, I am here, you didn't send us the server environment to reproduce, but you can at least set the Debug key to next-phase and send me the console log from when the arena ends abruptly or jumps phases.

Just to confirm - does it only happen with the bee arena or with others as well? We have not received any report like this ever, so I assume it's only for bees?

**Comment by sennby** [comment]
Sorry, I just emailed you my corearena folder.

**Comment by kangarko** [comment]
Thanks, requested access.

**Comment by kangarko** [comment]
Sorry but I meant you sent over the world too because the arena data.db contains specific spawnpoints in the world and I cant reproduce unless I rebuild your map 1:1, so it makes more sense if you sent it too, thanks

**Comment by sennby** [comment]
archive-2024-10-29T170045Z.tar.gz
<https://drive.google.com/file/d/1mvW5xzHcRItMX9TS7RKc8MSsjwSQdp-g/view?usp=drive_web>
try this. world is called dungeon its just 6gb with the folders i left out.
lmk if  u need those 2.

**Comment by kangarko** [comment]
Requested access. Please share all files to that email address. I will test asap.

**Comment by kangarko** [comment]
Hey there!

Regarding the dungeon ending in the lobby phase, turned out you had the region outside of the lobby location so players were getting kicked of due to "escape". You need to make the lobby contained in the arena region otherwise we can't protect it.

Second, can you use vanilla bees instead of those from mythicmobs? Just to exclude that incompatibility.

While testing in the next version, set Debug key to [arena, next-phase] to see console logs telling useful information why the arena is shifting into the next phase / ending.

**Comment by tuanhp0** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/issues/4705
GC: "We cannot fix this, only that plugin can unfortunately. They are setting the wrong amount of health player uses, as you can see error is from them."

**Comment by kangarko** [comment]
Please re-post me the error on the latest CoreArena release.

**Comment by kangarko** [comment]
I think the problem is that we save the health at the time the player joins the arena (which is increased by your plugin), and then we restore it back 3 ticks after the player left the game.

CoreArena gets the info from Bukkit's getHealth and getMaxHealth that it's above normal, stores it, and then sets it back.

In the next version of CoreArena that I will release later today, please set Debugger to [inventory] and let me know the console logs when the player joins the arena and when he leaves, so I can see what values we save/restore.

**Comment by sennby** [comment]
Hi just seeing this ive been running it hit or miss with the last wave or whatever i could. But yeah i will toss this in today/tomorrow and see how it goes and report back.
Thank you.

**Comment by kangarko** [comment]
Please do and let me know, thank you!

**Comment by sennby** [comment]
All is well.
Thank you.-
