### ISSUE TITLE
IllegalArgumentException: Health value (X) must be between 0 and X

### ISSUE THREAD

**Issue by tuanhp0** [kangarko/CoreArena#540]
This bug still exists, players still get extra health when exiting Arena abruptly. Console no longer reports this bug but it is still present.

1) Put your Minecraft version in the title.
Minecraft version: 1.21.1

2) Be clear: What is your current situation, the desired situation, and your problem?
This bug still exists, players still get extra health when exiting Arena abruptly. Console no longer reports this bug but it is still present.

Use: minecraft:attribute {player} minecraft:generic.max_health base set 20
This command cannot set that player's health.

**Comment by kangarko** [comment]
> Use: minecraft:attribute {player} minecraft:generic.max_health base set 20
I don't understand this - where are you using this?

**Comment by tuanhp0** [comment]
I use it when Join, Leave, and Finish.
To reset the participating player's health to the default of 20
it ticket #539

**Comment by tuanhp0** [comment]
Since ticket 539 is closed, the player's health cannot be reset anymore, health will be + infinite.

**Comment by tuanhp0** [comment]
Overload is a /ce in advancedenchantment, increases the player's health, when the player receives this buff from /ce, corearena thinks it is real health and will keep that health to reset for the player. And when the player exits Arena, they receive the buff from /ce again.

**Comment by kangarko** [comment]
I have reverted the last patch so the console error should now be visible. The way CoreArena restores inventories is delayed, meaning you cannot really use the attribute command because it will cause the issue you are running into.

Which enchant of your /ce plugin is causing it? I can try testing on my end

**Comment by tuanhp0** [comment]
overload:
  display: "%group-color%Quá tải"
  description: "Cho người mặc hiệu ứng HEALTH_BOOST I(+1/level)(tăng máu tối đa)\nvĩnh viễn."
  applies-to: "Áo giáp"
  type: "EFFECT_STATIC"
  group: "LEGENDARY"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "POTION:HEALTH_BOOST:7"
    2:
      effects:
        - "POTION:HEALTH_BOOST:8"
    3:
      effects:
        - "POTION:HEALTH_BOOST:9"

**Comment by kangarko** [comment]
Thanks, will test after the weekend.

**Comment by kangarko** [comment]
I unfortunately cannot reproduce the issue, the health is properly reduced upon leaving the arena, you dont need to set any command to edit any attributes: https://www.loom.com/share/a3bc41159b6a45c4b6196ead081cbc40

The only issue I have is that the health is only given then I take and give again the equipment to myself, but this is something you need to contact the enchant plugin author about. 

Looks like an issue with the other plugin. I unfortunately dont have that much time to debug issues with third party plugins. I hope you understand. Thank you.

**Comment by tuanhp0** [comment]
Overloads are added to the player's armor before entering the Arena, not in the Kit Arena.

**Comment by kangarko** [comment]
Unfortunately then it appears to be incompatible. We can't guarantee our plugin integrates with every possible Spigot plugin, I apologize for not having enough time these days to add a hook.
