### ISSUE TITLE
Critical Bug - Unable to select arena regoin point. 

### ISSUE THREAD

**Issue by Owizardo** [kangarko/CoreArena#55]
Hi there,

I encountered an issue when trying to create a new arena. When trying to select a block I get a message in my chat that says: "Select arena to edit via /puncher edit." I have both plugins installed and both using the latest versions. Currently there is no errors in the console. 

This is currently preventing me from creating Arenas. Is there any way to select the region points meantime to work around this?

**Comment by Owizardo** [comment]
Updated to the newest release of this plugin and the issue is still there. Please help.

**Comment by kangarko** [comment]
Hello,

I am terribly sorry for the delay. The problem has been caused in that the two plugins share GameAPI library which gave them information about all arenas installed, instead of only the relevant ones to that specific plugin. 

I have resolved this immediately. A new release will be available within an hour.

**Comment by Owizardo** [comment]
Thank you

**Comment by Owizardo** [comment]
Updated all plugins and the issue is still there. I cleared all my plugin folders and the issue is still there.

**Comment by kangarko** [comment]
The tools are essentially the same over Puncher and CA, and obtaining ones from one plugin recognizes them in the /<plugin> tools menu in another. I can see how that can create and issue. I will add an invisible nbt tag to each item associated with the plugin of origin.

**Comment by kangarko** [comment]
I been able to finally reproduce this - not being able to use tools in Puncher, getting a message from CA. I am on it right now...

**Comment by kangarko** [comment]
Alright I had split the tools. After some testing it should work fine!

![a](https://i.imgur.com/m07A8am.png)
