### ISSUE TITLE
External Lobby

### ISSUE THREAD

**Issue by Owizardo** [kangarko/CoreArena#56]
Hi there I had reported a similar issue in the discussions of the plugin. But would it be possible to create a Lobby outside of the arena? Basically I would like to create a lobby with NPCs and Custom Banners Images. 

Reason: 
When you join the game the map resets including the lobby which makes all my NPCs and banners disapear. Also, I currently I have all my arenas in the same world and would prefer to have 1 lobby for all the arenas instead a lobby for each arenas.

**Comment by kangarko** [comment]
Good suggestion, I am leaving this open.

**Comment by kangarko** [comment]
Moved to https://github.com/kangarko/CoreArena/issues/4
