### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#57]
Good evening! Today I'm here for a new proposal for the CoreArena Plugin, Today I thought about adding a new addon: The Achievements.

 Let's start talking about the achievements: The achievements are the goals that can be generated by default during the first creation (then in the code) or through the command /ma acreate Name. with the command /ma acreate name, the message will exit: Arena // Achievement Successfully Created! To edit it use /ma aedit Name (aedit stands for achievement edit) Once you make the command /ma aedit name you will open a gui with various parameters to which I thought now:

 **(PARAMETERS BELOW)**

 Objective Completion Award: Nuggets - Money (Essentials) {Custom_Command} If you select Command the gui closes and the Plugin says: Arena // Now send the Command to be set to complete this Achievement! (Without "/") Set the command to do for this achievement: Arena // Command Added.

Since the idea I want to propose is very complex and takes a long time, I want to say only that "premade words" are set up that will act as Requirements for completing achievement. If instead we want to go by the way the difficult one: We will use the words typed by the users, we make an example: When you are in the arena <Name> you have to kill the boss <Boss_Name>. So in a common day you have to do the one typed in the lens and if it does it will be marked as completed. Obviously... You have to use a specific plugin that has those specific functions otherwise the plugin will give an error.

 Now let's talk about the setup part of the Achievements When setting the type of prize 3 values ​​will appear: GoldBlock: (Essentials Money): If you click with the Gold Block (Right Button) The GUI will disappear and the plugin will say: Arena // Now you can chat in the amount of money you wish to give for this Achievement! 

Emerald Block: Nuggets - Usable for / but rewards. 

Redstone Block - Custom Command

For now the idea is over, and I call it very complex. I hope it's useful, Goodbye :D

If Someone user needs More Questions about this Improvement, Please contact me c: 

(Again, sorry for my bad english)

**Comment by BlackGamer000** [comment]
Edit: Emerald Block i mean Nuggets for /ma Rewards. Sorry For the Error :c

**Comment by kangarko** [comment]
Hey BlackGamer!

Awesome idea(s) I must say! I can totally see how that would enlarge the gameplay and make CoreArena more attractive.

I am leaving this open. This is a very big suggestion that takes lots of time. Right now I have other priorities, but I may return to it or add features partially in the future. 

Thanks!

**Comment by kangarko** [comment]
Moved into the roadmap.
