### ISSUE TITLE
[Improvement] 2 New Features

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#58]
Redirect ===> My idea is Reachable with this link: https://hastebin.com/edujizosiw.sql

Thanks to All c:

**Comment by kangarko** [comment]
> Good evening to all c:
> 
> Today my mind has devised a new proposal that could go for both Plugin (CoreArena & Puncher)
> 
> The first proposal is to include the famous crates, they will be directly configurable by both Config and Game.
> 
> From Game la Crate they are called Puncher Crate and CoreArena Crate
> 
> The Lore that came to my mind is this:
> 
> 
> + ---------------------------------------------- +
>         &cPuncher &7Key
> 
> &7This &cKey & 7is &7usable &7Inside the &cPuncher Crate!
> 
> &8Â» &cLeft Click Â» See the Crate Awards by getting close to it!
> &8 Â» &cClick Right Â» Open your Key by approaching the Crate!
> 
> + ---------------------------------------------- +
> 
> 
> 
> 
> 
> + ---------------------------------------------- +
>         &bCoreArena &7Key
> 
> &7This &cKey & 7is &7usable &cInside &7the &bCoreArena Crate!
> 
> &8 Â» &cLeft Click Â» See the Crate Awards by getting close to it!
> &8 Â» &cClick Right Â» Open your Key by approaching the Crate!
> 
> + ---------------------------------------------- +
> 
> 
> 
> Obviously it will be customizable in every respect. As well as the name of the crate and everything.
> 
> The crate can be set via the Command / Puncher crate
> 
> Doing that command opens a GUI with various choices, to be exact are 2
> 
> First: Diamond: Add Rewards
> 
> When adding a Rewards, a further GUI opens with a tutorial on the bottom right that demonstrates operation using a simple text.
> 
> This gui will have the function of being able to add commands or permissions during the setup of that prize.
> 
> As an example, I add a Rank with the probability 0.000005% (Impossible but ok Lol) So that specific prize executes the command set during the setup.
> 
> This proposal is intended for both the CoreArena plugin and for Puncher c:
> 
> Second Function: Remove Prizes, through that Function you can remove some prizes from the crate.
> 
> 
> Another idea is the integrated particles without using external plugins to Puncher & CoreArena, these particles are obtainable through 2 means
> 
> First: Get it through the crates with the permission CoreArena.particles.Name & Puncher.particles.name
> 
> Second: Get it via the / puncher particles command that opens a GUI where you can purchase the Particles, of course these can be purchased through the Economy of Essentials or the Plugin that uses that server. The particles, however, will be set at the level of use in one circumstance, Through / puncher particles tools you can take the region with the two mouse buttons that will indicate in which area the particles will be visible to the players and to himself. If the server is receiving a lag shot, a NoLag protocol is started that sends a broadcast to the internal server with the type: CoreArena // AntiLag protocol enabled, From now until the new warning the particles will not be activated. Obviously this message is customizable via the messages_en.yml, This function is available for both Puncher and CoreArena, the command for particles is / but particles
> 
> Add, the Crate Key can be obtained through a probability that can be obtained by winning in the game, both for CoreArena and for Puncher, and obviously from the settings.yml there will be a string called Enable-crates: true / false
> 
> For now it's over, I hope it is useful and Expansive for both c:

**Comment by kangarko** [comment]
Thank you for your suggestion! I am not planning to include it in the moment but I am leaving this open for the future.

**Comment by kangarko** [comment]
We are not planning to include this feature due to works on other priorities.
