### ISSUE TITLE
A lot of Big Features

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/CoreArena#62]
Good morning C:

With this thread I will make a series of proposals for both plugins, so CoreArena & Puncher. Let's start:

1st Feature: Command /stats While in the Lobby, practically while you are at the spawn or waiting to join in a game you can perform the command mentioned above to see some statistics related to some PlaceHolders incorporated inside the Plugin itself. Example here under ↓

Example:

Nickname:
Nuggets:
Matches Played:
Better screw record:
Rank:

2nd Feature: This second Feature is associated with the 1st Feature (Lookup). Through a Hologram Positioned you will be able to see the Stats of a Player, The same ones that I wrote the Above ↑

3rd Feature: Adding LeaderHeads, Through the same Plugin without External Dependencies, Basically with LeaderHeads you can put various things to Example: Played Matches, Favorite Arena, Favorite Kits, Maximum Total of Nuggets obtained, and Other.

4th Feature: (Optional) Add the "Victories" for each Single arena. I mean that as soon as the game ends, a message like ↓ will appear

1st Place:
2nd place:
3rd place:

Obviously, you can customize the number of positions you need to insert through the Arenas file.

5th Feature: Command to Give and Take Nuggets to a Player: I'm talking about /p nuggets take {PLAYER} {TOT} and /p nuggets give {PLAYER} {TOT}. Instead for CoreArena /ma nuggets take {PLAYER} {TOT} and /ma nuggets give {PLAYER} {TOT}.

6th Feature: Always Referred to the Nuggets, /ma nuggets giveall {TOT} and /ma nuggets takeall {TOT}. Instead for Puncher /p nuggets giveall {TOT} and /p nuggets takeall {TOT}

7th Feature: Is a Function like a contest but probably useful in some cases. I'm talking about /p contest create & /ma contest create. Through these functions it is possible to create a sort of "Tournament". But before everything is necessary to set various settings. These settings are sent from the plugin to the Command Sender.

Step 1: Title of the Contest
Step 2: Awards that can be obtained from Victory
Step 3: Requirements That are controlled by the Plugin in Automatic. If the Requirements are not met the plugin will say: Error: You don't meet the following Requirements: Requisite1, Requisite2, Requisite3 and so on.
Step4: Commands to be executed to the winner and to the losers.
Step5: Contest Start Date.
Step6: Maps where you can play the Tournament, So in substance this has to do with the maps set with Puncher & CoreArena.

Once Setup is finished, a Broadcast will arrive in the following cases: End Setup to all Online Players, Join in Server, Return to Spawn in case you are still Waiting in Waiting Lobby. Instead to register for the Contest you can use various Functions, /ma subscribe <name> / p subscribe <name>

Once the user has executed this command, a message will appear with the Requirements, the Maps that will be used in the Tournament, the Victory Award, and the penalty for those who lose the Tournament. The message I wanted to propose it like this, obviously it can be customized by the Config, Same for each Feature proposed above.

Message:

-----------------------------------------------------------------------
                           Contest

Welcome {NAME} to the The Contest of The Date {DATE}! 

This Contest it calls: {NAME_OF_CONTEST}

Through this Contest you will be able to Challenge other Players that Participate in the Tournament and if you get the victory you can win many prizes!

Below you will see all the Requirements necessary for Participation in the Tournament.

Nuggets Required:
Mob Killed:
Maps played:
Boss To Kill:

[X] If you are sure you want to subscribe click here!

----------------------------------------------------------------------------

After the Player has clicked the JSON message: the Plugin says: Done! You have Been subscribed to the Tournament of the Date: {DATA} named {NAME_OF_CONTEST}! Good Luck ;)

When the Tournament Date arrives and the Player is Online, it is tipped in a Tournament WaitLobby that is not linked to the Traditional Tournament Lobby of the Maps. The lobby can be set via /ma contest tools
& /p contest tools.

It took me a long time for the ideas to be proposed, I hope they are nice and can expand the functionality of both plugins c:

Good day c:

**Comment by kangarko** [comment]
Thank you very much!

That is a long list. I admire the time and energy you've put into it. I promise I will carefully consider adding what's possible in my my time frame. I am right now quite a busy so it may take a while, and most likely I will take a few features in before others. 

Thanks again.

**Comment by kangarko** [comment]
Thank you for proposing new features. Right now we are no longer open for suggestions as we have works on more prioritized features and projects.

I will add some of your suggested features into the future versions for sure.
