### ISSUE TITLE
MythicMob spawn eggs not saved in edit mode

### ISSUE THREAD

**Issue by rpendrick** [kangarko/CoreArena#66]
Hi, whenever I attempt to edit the mob spawn location, it allows me to save the minecraft default spawn eggs into the editor, but if I add a MythicMob spawn egg, it allows me to do so, but never saves the egg into that monster spawn.  Pastebin of console output here: https://pastebin.com/VWsbdeWx

I am using CoreArena 1.61 and MythicMobs 4.32 on Spigot 1.12.2....

- Rick

**Comment by kangarko** [comment]
Thank you, I fixed it.
