### ISSUE TITLE
[Bug] Player EXP and LEVELS in survival not restored on arena completion

### ISSUE THREAD

**Issue by M2VC** [kangarko/CoreArena#69]
I haven't tested earlier versions of the plugin, so I don't know if this is intended or not, but right now players that enter the arena and exit it either by winning, losing, or canceling the match do not get their Vanilla exp and levels back. Players are reset to level 0, with no exp.

**Comment by kangarko** [comment]
I apology for a late answer, please provide the following information:

* is the Allow_Own_Equipment enabled in your arena file?
* is Arena.Store_Inventories enabled in settings.yml?
* do you have any multiinv plugin or multiworld plugin? If so, which one(s)?

**Comment by M2VC** [comment]
- Enable own equipment is set to False

- Store inventory is set to True

- No

- No errors

**Comment by kangarko** [comment]
Please post me your plugins list for a quick review. What's your MC version?

**Comment by M2VC** [comment]
MC version is 1.12.2

Also here's a quick img of all the plugins I am currently running:

[IMG](https://i.gyazo.com/512ab4af90915d46f8a6adcc63597499.png)

**Comment by M2VC** [comment]
Any update on this?

**Comment by kangarko** [comment]
Hello, I am sorry I was not able to help you in time. 

From my testing, the experience was saved correctly, so I suspect it must be some part of your server that's preventing it. 

You can upload me your entire CoreArena folder in a ZIP package here directly so perhaps I can give it another try.

**Comment by TheWranger** [comment]
I'm getting this as well.
@kangarko I believe it has something to do with using Essentials to keep XP on death. Haven't thoroughly tested but have a hunch

**Comment by kangarko** [comment]
@TheWranger can you test without the Essentials' feature?

**Comment by TheWranger** [comment]
Nevermind, tested without CMI installed and no difference.
Not sure what the issue is

**Comment by TheWranger** [comment]
I'm running the server on Paperspigot build 1427 if that makes a difference.

**Comment by kangarko** [comment]
Is the arena on a different world than the world where the player is respawned?

**Comment by kangarko** [comment]
Also please test with exp saving disabled in Essentials.

**Comment by TheWranger** [comment]
Yes, they are different worlds.
I'll test with Essentials with I have time, but I already tested without CMI or Essentials installed and the issue still occurred.

**Comment by kangarko** [comment]
@TheWranger any update on this one? I was still not able to reproduce.

@BATHSALTZZ what's your plugins list? Do you have any other plugin saving or restoring items on death?

**Comment by TheWranger** [comment]
Are you testing with paperspigot?

**Comment by kangarko** [comment]
Yes.

**Comment by TheWranger** [comment]
I've also been having issues with HEALTH and HUNGER not being restored, either.

**Comment by kangarko** [comment]
Can you please give me some instructions on how to reproduce? What world the arena is on, what teleportation happens between worlds, what commands are used etc.?

**Comment by TheWranger** [comment]
Even when I'm in the same world as the mobarena, I still get this issue.
Gonna disable plugins one by one and see

**Comment by kangarko** [comment]
@TheWranger any findings after disabling plugins?

**Comment by TheWranger** [comment]
Removing plugins one by one.
Currently at 30 plugins, Multiverse-core gone and am in same world while stay having the issue.

**Comment by kangarko** [comment]
@TheWranger can you ZIP me your entire CoreArena/ here to this reply window?

**Comment by TheWranger** [comment]
Definitely not a plugin compatibility problem.
![image](https://user-images.githubusercontent.com/24642838/43138205-746e8f6e-8f91-11e8-83c3-28504d27406b.png)

**Comment by kangarko** [comment]
Excellent, thanks for this thoughtful testing, trying to reproduce right now.

**Comment by kangarko** [comment]
@TheWranger comment removed due to sensitive mysql information, please remove it next time to prevent people hijacking your mysql ;)

**Comment by TheWranger** [comment]
Whoops, guess I forgot about that.
Thanks

**Comment by kangarko** [comment]
I can reproduce. Working on a fix.

**Comment by TheWranger** [comment]
Happy to hear.

**Comment by kangarko** [comment]
Unfortunately this is an issue in Spigot (or PaperSpigot). 

There is a way to workaround that however I am not sure whether that's safe, so let's wait for their response.

**Comment by kangarko** [comment]
I delayed inventory restore by 2 ticks (100ms). Please test the next version of both CA and Puncher.

**Comment by TheWranger** [comment]
Yes, the new version fixes the issue.

**Comment by kangarko** [comment]
Awesome!
