### ISSUE TITLE
unable to register events spigot 1.12

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/CoreArena#7]
Hi, seem to be getting a minor error on boot up with the latest build?

30.07 05:40:19 [Server] ERROR [CoreArena] Plugin CoreArena v1.2.2 has failed to register events for class me.kangarko.corearena.nul.com5 because org/bukkit/event/entity/EntityPickupItemEvent does not exist.

Thanks

**Comment by frizzbee30** [comment]
Hi, not sure if this is related, but getting this on our test server

https://pastebin.com/ygBVvfDL

it wouldn't allow me to use the spade to set the waiting lobby, and then running a snapshot save failed.

We do use Fast Async World edit, which it appears to be complaining about in the error log?


Thanks  :)

**Comment by frizzbee30** [comment]
resolved with a re build of spigot, obviously the build checking isn't quite a extensive as expected!

**Comment by kangarko** [comment]
Good notice!

They have changed the API in the recent version. I have been relying on PaperSpigot which had this event for a long time.

I have fixed it so no errors are printed even when on older versions. Thanks for noticing!
