### ISSUE TITLE
[question/error] Mythic Mobs

### ISSUE THREAD

**Issue by Techno-Panda** [kangarko/CoreArena#70]
so i saw it was compatible with MM so i put some of my spawn eggs in there and it puked out an error when i reloaded the arena. the error is as follows.

04.05 08:38:41 [Server] INFO > Loading Escape_the_death_star
04.05 08:38:41 [Server] INFO CoreArena 1.6.4 encountered a k! Please check your error.log and report this issue with the information in that file.
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO Chyba pri volani deserialize z COm4 z udajmi {custom_egg={type=MONSTER_EGG, amount=8, meta=SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, StormTrooperM]}}}
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO (2) Cannot deserialize {chance=100, activePeriod={mode=from, limit2=1, limit=1}, minPlayers=1, location=events, -584, 157, 2533, spawns=[{custom_egg={type=MONSTER_EGG, amount=8, meta=SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, StormTrooperM]}}}, {custom_egg={type=MONSTER_EGG, amount=8, meta=SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, STCheif]}}}, {custom_egg={type=MONSTER_EGG, amount=8, meta=SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, STSergent]}}}, {custom_egg={type=MONSTER_EGG, amount=8, meta=SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, StormTrooper]}}}]} to class me.kangarko.corearena.nul. .COM6
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO CoreArena 1.6.4 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO Error loading arena from Escape_the_death_star.yml
04.05 08:38:41 [Server] INFO *-----------------------------------------------*
04.05 08:38:41 [Server] INFO CoreArena 1.6.4 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
04.05 08:38:41 [Server] INFO Arena // CoreArena 1.6.4 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
04.05 08:38:41 [Server] INFO java.lang.RuntimeException: java.lang.RuntimeException: me.kangarko.corearena.nul. .k: Report / Could not detect monster type from ItemStack{MONSTER_EGG x 8, SPAWN_EGG_META:{meta-type=SPAWN_EGG, lore=[A Mythical Egg that can, be used to resurrect a, StormTrooperM]}} (data = SPAWN EGG{null}, dura = 0)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .cOm4.int(SourceFile:586)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .nUL.IlllllllIlIllIIlllIIllllIIlIlIlllIlllllIIIIlIllllllIlIIllIllIIlllIIlIIllIlIIllIllllIlIIlIIIlIllIllIlIIIIllIIllIIIIllllIlllIlIllIlIlIIlIIlllIIllIllllIIllIIIIIIIIIIlllIIIlIllIIIIIIIIllIllIllIIIlIllIlIllIlIIIlIIIlIIlIIIlIlIllIlIIlIIIIIIIIIIIIIIllllIllIlIIIIIIlIIIIIlIIlIlllIlIIIllIIIIlIlIlIllIIIIlIIlllIIlIIIIIlIIllllIIIIlIIIllIIIIIllllllIlIllIIIlIlIIIllIllllIIlIIllIlIIllIIlIllllIlIIIIllIlllIIIlIIllIIIlIIIllIIlIIIllIlIIllIllIIlIIIIlIlllllllllIllIlIlIIlIIlllllIlIllIIIIIlIIlIllIlllIIlllIllIIIIIIIIlIllI(SourceFile:90)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .nUL.nul(SourceFile:51)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .AUX.IIIlllllIlIlIlIlllIlIllllIIlIIllIIIIIIllIIIIlIlIllIIIIIIIllllllIlIlIllIIllllIIIIlllIIllllIIllllllIIIIIIlIlllIlIIllllIlIllIIlllllIlIIlllllllIlIIlIIIIlIIlIlIlIIIIllIIIllIlIIIlllIlllIIlllIllIlIlIIIlIllIlIIlllllllIlllIllIllIIIlIIlIIIlIIllIIlIlllIIlIIIIlIIlIIlIlIllllIIllIlllIIlIIlllIIIIIllIIIIlllllIllllIllIlllIllllIIIlllllIIlIIllIllIlIllllIIIIIllllIIllIIIlIlIIllIlllIlIllllIlIIIlllllIIIIlllllIIlIIIIIIIIIIlllIIIllIlllIIIllIlIlIIlIllIllIllllIIlIIlIIIIIIlllllllIllIllllllllIIIIIIIlIIIIlIIlllIIIlIIIlllIllI(SourceFile:166)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .AUX.lIIIIIIlIlIlllllIIIlIIIIIIIllIIIIIIIIlllIlllllIllllllIIlIlIIIIlIllIIlIlIIIlIIlllllIlIlllIIllIlIlllIlIIlIIlIllIlIIIIllIIIlIIIIIIllIlIlIIlllIlIllIIIIIIlIIIIllIlllIIIIIlIllllIIlllllllIllIIIIIllIIlIlllllIIllllIIIlllIlllIIIllIIlllllIIIlllllIIIllIlIlIIlIIllIIlIlIlllllIIlIIllIlllIlIIllIllIIIIIIIllIIllllIIIIIIIIIIlIlllIIIlIIIlllIIIllIIllIlIIlIIlIIlIIlIlIlIIIlIIIIIlllllllIlIIllIIIIIIIllIllllIlIlIlIIIIIIIIlIIlllIIllllllIIlllIllIlIIIlIlIllllIlIlIlIIlIlllllIlllIllIIlIllIlIllllIllIIIlIIlIlllllllIlIIlIIIIIIII(SourceFile:160)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .W.llIIlllIlIllllIIlIIlllIIIIllllIIlIIIllIIllIlIlIIIIIlllllIlIIIIIlIlIIllllIllIIllllIIIllllllIlIlIllllIlIIlIIIllIIIIlIIIlIIIIIIIlIlIIIIIIIllIllIlIlIllIIIIlIIlIllIlIllllllIlIIIlIlIlIllllllIIIlIlllllIIIlllIlIIllIIlllIlIlIIIlllIIlIIIIIIIIIIIIIIIIllllllIlllIlllIlIIllIIlIIlIlIIlIIlIllIIllIlIlIIlIllIlIlIlllIIlIIIIIlIIIlIlIIIllIlIlIlIIIlIIlIllIIllIlIlIlIllIIlIlIIlllIlIIIIIllIlIlIIllIlIIIIlllIIIIlIIlIllIlIIlIlllllIIlIlIIlllIlIIlllIIIIIlIlIIIIIIIllllIllIlIlIIIIIlllIlIIIlIllIllllllIlIlIlllIIIllIlIllllIllIIlI(SourceFile:463)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .W.IlllIIlIlIIIllIlIlIlIlIllIIIlIIlllIIllllIlIlIlllIlIlllIIllIllIlIlIIlIlIIllIIlIIIlllllIIlIlIlIIIllIllIIlllllIIlIIIIllIIIIIIlllIlIlIIIIIIIIlIIlIlIIIIlllIIIIIllllIIIlllIIIlIIlIlIlIIIIIIlIlIlIIIlIlIlllIIllllIIlIIlllIlIlIIIIlIlIIllIIIIIlIlIIlIlIlllllIIlIlIIlIIlllllIIlIllIIIlllIIIIllIlIIlIlIIIIIllIIlllllIlIllIlIIIlIIlIllllIllIlIIlIlIllllIIIlIlIIlIllIIIlIllIllIIIIIIIlIlIIIlIlllIIlIlllIIIIIlIllIIllllIlIIIIlIlIIIlIIIIIIlllllIIllllIlllllIlIIIIllIIIIllIIlIlllllIIlllIllIIlIlllllIllllllIIlIIllIllllIlIIIIIlll(SourceFile:426)
04.05 08:38:41 [Server] INFO at me.kangarko.corearena.nul. .COM2.handleSubCommand(SourceFile:20)

**Comment by kangarko** [comment]
What's your MC version?

**Comment by kangarko** [comment]
Closing, no answer provided.

I tested with MythicMobs 4.3.2 on Minecraft 1.12.2 and without any problems. Write below if still having issues and provide information from your errors.log file.
