### ISSUE TITLE
Arena specific kits.

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#72]
It would be awesome if we could set kits per arena and not globally. This would enable a whole other form of customisability to the plugin 👍

**Comment by LogGits** [comment]
Oh yes, my apologies, I was referring to arena specific classes.

**Comment by kangarko** [comment]
Hello, okay I understand. While it all seems very appealing right now I have other priorities so I have to delay it, but I will definitely return to it or at least make it so you have different classes to choose from, in each arena.

**Comment by LogGits** [comment]
Any progress on this?
