### ISSUE TITLE
Pvp damage types

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#74]
Ability to allow specific types of pvp player damage. E.g. snowball damage, arrows, swords. This could allow for custom types of arenas that are themed appropriately.

**Comment by LogGits** [comment]
I'm referring to the damage a user takes. So we can choose what damage they take per arena. This would allow, for example, snowball damage only, in a spleef arena.

**Comment by kangarko** [comment]
I see. For now I have higher priority tickets but I will return to you in a reasonable time frame. Thanks

**Comment by kangarko** [comment]
We are not planning to include this feature due to works on other priorities.
