### ISSUE TITLE
Players_End command

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#81]
Hey thanks for adding the Players_End feature 👍 

Its an awesome addition its just missing one small thing. In the arena file, in the commands section could you please add a Players_End command.

whereby there is a placeholder {players} which will run the command for those players alive when the arena ends. I would like to utilise this to give winners rewards for winning.

**Comment by kangarko** [comment]
Please use the Commands.Finish.Player and Commands.Finish.Console section (if you dont have it just open CoreArena.jar/prototype/arena.yml) and place the commands there ;)
