### ISSUE TITLE
Remove 0 nuggets message.

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#82]
Is it possible to remove the nuggets message when 0 are given? 
[![This message when you receive 0 nuggets](https://gyazo.com/7659fece2189286e32a87c99a6e7678c/raw)](https://gyazo.com/7659fece2189286e32a87c99a6e7678c)

**Comment by kangarko** [comment]
Not currently, but I am leaving this as a suggestion.

**Comment by LogGits** [comment]
Ok thanks, I just think its unnecessary to show the message if they don't get any nuggets.

**Comment by kangarko** [comment]
Fixed.
