### ISSUE TITLE
Class sign question and issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/CoreArena#84]
Is there a way to actually open up the class gui with a sign? I know there is [class] but this gives them the class defined. Maybe a [classes] that opens up a gui of all classes would be useful.

Also people can use the [class] sign while an arena isn't starting. Meaning they can enter the area get the class and leave and keep the items. Could you make it so there is a message that says "you cannot use this until you have joined the arena using /arena join" or something like that.

**Comment by kangarko** [comment]
AutoPlay has [classes] sign, which I could also backport to CoreArena.

I will look into that bug.

**Comment by kangarko** [comment]
Added those signs, and fixed that bug.

**Comment by LogGits** [comment]
Formatting for sign doesn't update. e.g. [class] turns to **[Class]** but [classes] stays as [classes].

Also the bug was fixed cheers 👍

**Comment by kangarko** [comment]
Yes, classes have no formatting, they are always the same as you put them ;)
