### ISSUE TITLE
Chatting inside the arena is being sent both globally to everyone online and locally to players inside the arena.

### ISSUE THREAD

**Issue by mibby** [kangarko/CoreArena#88]
ChatControlPro v7.8.25
CoreArena v1.6.8
Paper dev 1448 (Spigot 1.12.2)

@kangarko Chat is being sent globally through ChatControlPro to everyone online, as well as locally to everyone inside the arena. Would it be possible to add a setting or force isolate chat while inside the arena so it isn't sent twice and only sent to players inside the arena with them?

The plugins MobArena and PVPArena do not have this issue, with the latter implementing a prefix in chat when chatting in the arena so you know it is only being sent to recipients also in that arena.

https://github.com/slipcor/pvparena/blob/4ad9a4f41a7173ab478e1e1c361a97604b0c7d33/src/net/slipcor/pvparena/commands/PAG_Chat.java
https://github.com/slipcor/pvparena/blob/07b253aa57aff77e0195f9c7295c65be2d05ee2a/src/net/slipcor/pvparena/listeners/PlayerListener.java#L166
https://github.com/garbagemule/MobArena/blob/42416cab2f6f92c10ddf3c6fb9b82ced37012383/src/main/java/com/garbagemule/MobArena/listeners/MAGlobalListener.java#L268

**Comment by kangarko** [comment]
Thanks for reporting, but let's continue the discussion at one place: https://github.com/kangarko/Puncher/issues/21

**Comment by kangarko** [comment]
Thanks for reporting, but let's continue the discussion at one place: https://github.com/kangarko/Puncher/issues/21
