### ISSUE TITLE
Per-World Command Restriction

### ISSUE THREAD

**Issue by frizzbee30** [kangarko/CoreArena#9]
Hi, would you be able to add world restriction? 

We run multiverse, and it's nice to keep some commands restricted by world  :)

Thanks

**Comment by kangarko** [comment]
Hello,

sure, in what way it should be limited? Do you mean restriction to use commands? Btw, if only this is the case, you can use any permission plugin like PermissionsEx to give negative commands permissions in those worlds.

**Comment by frizzbee30** [comment]
hi, yep you can add perms etc, just to remove the need to negate etc and add more nodes. We run multi-world with multi ranks per wold, gets to be a very very busy few thousand line PEX file to load lol  :)

World restriction for commands etc, I'm never totally sure if world restriction does only block commands, or keeps the plugin out of that world, I'm guessing the former.

It does make it a bit easier when watching out for perms and so on.

 :D


Thanks as always.

**Comment by kangarko** [comment]
Hey, I understand. I have my plate currently full as it is with the other feature requests, and since we both know that it is possible to achieve (albeit a bit costly in your case) via permissions, I am pretty sure that there is a plugin specialize for that. Until I add this, you can also consider making a rule into ChatControl:

```
match ^/(arena|ma|mobarena|corearena)
ignore world arena_world|another_arena_world
then warn &cWe are sorry, but the command is disallowed in this world.
then deny
```

**Comment by frizzbee30** [comment]
Thanks  :)

**Comment by kangarko** [comment]
I am closing this currently. For the near future I have more critical updates and patches, tonight's a new release as well. If it doesn't get implemented and you will want it to be in the next 1 month, please make a new issue :)
