### ISSUE TITLE
Keep Inventory on Death

### ISSUE THREAD

**Issue by TheWranger** [kangarko/CoreArena#93]
New option for arena configurations that when enabled; automatically removes empty bottles from players' inventories.

**Comment by kangarko** [comment]
Or even better, make a boolean option Keep_Items as you suggested earlier with the option Keep_Blacklist where you specify POTION and it will match any potion so they won't be kept.

**Comment by kangarko** [comment]
https://github.com/kangarko/CoreArena/issues/92

**Comment by TheWranger** [comment]
@kangarko What I was suggesting here wasn't to do with death; I want an option that removes empty bottles from a players inventory automatically once they drink a potion. Similar to what some dueling/practise servers have.

**Comment by kangarko** [comment]
I understand okay.

**Comment by kangarko** [comment]
Had to close due to works on other priorities.
